vmetrics:
    auth: ENC[AES256_GCM,data:dVjQnGv/QmL0k7U/m7OwSqD372mGb5FQw79wrm2kkoaXPVBbNFdIBfM/PoRb9APoPKjVeRBK/X+KI3YQtuuDIp11rkKUNmueUoT+WCpJFEqIy6iRNVV78cuBBxW1MWe8uOFWe61qYYR86Q31incPgH2m/sY9dckuzq1PWAGVVqXy3nnOmprbeueVSRZMl+rym6Avr6Py+aZYSNAayVEie6d2/hwis+vjfOakVw==,iv:Q49WI+0O4MzeLK7TbKZFal5Q37UVjZ7+J2uyBQkgzd0=,tag:UagPOG4yb5vpuF9GixPs+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdkQzV0FYSzIrY1hJQVpQ
            S1VnMi95S3FWRmdQcTMxbmlYWldrSTB4c0RBCjhobU9zQWZLN0wzMGRwbXlYdDJn
            V28rMFZiZjlNQ3dQWm11OVdNb09SMHcKLS0tIDlYVUZmZlFoRFVlRUNiTnVaWDZ6
            NGdHREJOWjdNMytrOEhuV1V6ODkwWmMKw5nl+xRzXiRlqUzOVSJEBnWZLwEEn4dm
            Aq2/rYhLlhE0Q8MqCR9USFooPhIpNZ0wOM+8NKigcMCDv+L6wJnyyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL0dJcWhaM2NlZ0gxanJ2
            ZmhNU3I2ZEdvR2tnRk9vSnFNNGlvMS9CUW5vCmhGYXVURmVrcFNDWWUwZFM0YVNt
            dGg4V29TbkxaTFJOdEUxcjJrM2E0Yk0KLS0tIE12VGQ0WlVmRkhxV01KUis1Wm03
            N0pKU0ZzQTZ6SU9FV3M5T1VWN1VxWGMKtTRn3q/+7TU/ZW2885wdIKAOsIo0jMJN
            vn5dYHZqzdPwIHYVmQ2SPjSd/JcRIUTm6RqRERaOXYuc1mjPCdtV3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezx4f7szu3mf4e84de7vlw0aaxshfr3tjt6dm356g578ujkck9mqy6ff8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OVM4amhia3k2R2g4dzNy
            dXJuOTlhTC9qZnB5RzYxWlk0dzh0THFHSFFzCnkwSE1VQkxOckNhSGIxZkRuUElL
            Z2VUSm51WG9WZWZVUVdGS1dWZWQ0akEKLS0tIFJlQTBjdlFNcFZSRHZKS0FFQTF5
            Wjk1UWNhNEF4MlBwbUhQZTdNNzB1NDQKlEF9PM1chdZGv89qjiT87dWIweyI0+K8
            C+Q2tYjPFPe7yU/a2jZA4LyU+KMZq7WlPdtvJ5KUMCjZ7ciyx6IKwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-08T07:32:52Z"
    mac: ENC[AES256_GCM,data:UAj+Zl1B4NQ2y6MSHZ0yznn7Q9cX+T1KCI1fy9Yo63Jr1QgNwKaRYkgReuSz7kTh7oHItg26ygEUeMBNNqPxdxPuGOmRDu9qzjqNVsWWUY/uNrAV0p2XKgjSZrW9b9KUAcTcTltyMaWPCoBTpb1ivt+W3qhH9yW6e87qttawYf4=,iv:kaU/9JkiyW64q/ruVCV/S55CrBJVR9FDdTwCdW06KLg=,tag:iLbYXrgQjEEh3/+GXaMzig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
