vmetrics:
    auth: ENC[AES256_GCM,data:CGuIuTlPaf1x59Wf7vtmUi1HZTqv5MwJglv6vrj0aQucLaInj7NLsau3aelmwiIqdghZhAgZguqPtO+JsnEhoaFKkD/KonZ+b1HINAO3+EQ7Vl1mYTrnoIwOrw13RERubingvRhG1sYm/swcLpR9uMxccOev6M/i78XvcqDRx1uC9IdAvN7iXAg1fggIchNWMoYZdJrsTeMCprNRt7FadVzapYFL35jQsnImiQ==,iv:Q49WI+0O4MzeLK7TbKZFal5Q37UVjZ7+J2uyBQkgzd0=,tag:tLjxouPYP2loIAOpQfj0sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dnFnQ1dzdlIvTE4xTGt0
            THFJMlBPaTlOSXFFK3RpNFAxckRPNjdPOGhZCnBFRnk1dW1WUEZDQ1Fwa3duRzFa
            V0dKNTJXZWpLbDJpMmUrOXN0RWpRTU0KLS0tIFNtQ2l6QVU2OGtZeVdnaHpzZ3R5
            a1YycStPZXB4UDFMeFVnWXB6elJxVm8KfbPbMc8ZRkNi7oLoRLk3Xg2Su4UTl03V
            n3ffV8JCc2IQ5CDiDYuOJ+Zv2Nfspey/ohABSnF7KgksksOuXkq6nQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMXF1cFVKcGtHNFFsUFFa
            YTlpSHkwNmNCaTRWeFUxR0VRa2cwMkovbEhnCkRDSmJGUFkzOFJHbUtsOFdFS2Ny
            TzNUeGh6SzQwZ29mNWhuRSsvbWEyL2sKLS0tIFJRZWtrVDV3cThITWxMRDlLc3cz
            KzZsYkJHKytJVFdOdTdUWnhEMkE3Z2sKPRWtF/1DzwMBFk+T/jLrAjIps33SYtpF
            6s4TobNlIySkMqqpi9mxcnCnR8PIPmmTG75VcGu4vbv+S1PVN8MbQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezx4f7szu3mf4e84de7vlw0aaxshfr3tjt6dm356g578ujkck9mqy6ff8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTnIzZFg4ZS94QXkreWx3
            dU8zL2h1SHZ3ZlhrTm5zSlpCaFFrK2QraEU4CmNlL0xuZ3diMTYzdlQ5L1AyTkNu
            ck10UENZL21YeWtzem1sSnZ3QWhJTUkKLS0tIHBtRms0bWpYWmpFbEVVY1lvNWVv
            UjM5QlZXcjhucXJVTjNtL0JQemI4bnMKA9MQ+J3sufLbM8H06WND9eJHCnTiQEoS
            UiowcLUZzb5u8g3NjBcVADW6q08K5B1+r4FHmo77fPRlupx+nwNjBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T08:08:01Z"
    mac: ENC[AES256_GCM,data:GY/zkObmBlCNh4BdQPWRWLU4/aU0V/qv98yvm+xbkHKZBIFNcZL4TBYZ7XvMZW9B05iL7GaAoBjc4rehCraXTjHv3RDkSDJcdJNIe0t19SrqYuzS7lKTBGIERUNiLmsCIFl/qCcGym0Jqmxp6z5mEywd/f9j1BbOMK1JGwbWZmQ=,iv:xBmlvfagHEho9qU8ghMvNc2v8yVtcLfxLsJTJcWX86E=,tag:exjG5QGqUsq5KeRDCvT/0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
