vmetrics:
    auth: ENC[AES256_GCM,data:qwcrHuOFlTIpeay3dQsERgXnefynfVahZuRMDwPh2XjROeRBinxlpEAEzTuRfsf9yg6dla1jgLSBLqd3oT+as4YZ+RzhaWV6+4661gHKTrEXSw4rb/+PtbGCqRfcx1OKFmr4ioNNGAj5wRYm+87pTdTo2cdPpk10+AoXcORKS33gzGl1WTOZ+jSxj/FRU1o8664z+MRX6yqL9QPu7a5gpey5PR1FTv8tFVY2vA==,iv:Q49WI+0O4MzeLK7TbKZFal5Q37UVjZ7+J2uyBQkgzd0=,tag:ttCLsOecH1BlVBNRcGZyGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRGNycjV6bFoySE1qWWFN
            Ynd0dEdWMlJsVHUybmJxZTY0ZldTZEpVcEEwClVPY3lGcG5uWmdWalVZSEdFSVFD
            UWdoRStaZklLUjdFa28zN2tDcUMzeEUKLS0tIDVackhEcG9UcW14Q1Z1WHgwSHJD
            bnVkSTZPM3VkYzJ3OUlhZm91UDVySm8Kb53bIZbq7zbjY81+E1zEmxK2BA95/pS1
            L2W0gNdPtNhi4ZjQmd0nWNnFQlx6mleL5w2c+7ZOFS5raFthB/qjRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbFhkeXV4Unp2MEpwWHJr
            NW92dUpRcnpWemlMdjhYZTBkTi9GdWpNY1NzCmxoS0VCUm5JRVBCd3h3V0tXNlFx
            ZXJHR01KZnZPbUExdGV5WXlZQUltWE0KLS0tIEl2RUZkUCtnTFJHZWprVklPRjZD
            VGkvdkZRVDZRbWpDUzQ3aGhnZFUrUzAKNWB5eAhy8rDrFAf2Bm+17vnmSNz8Iur5
            JVEE/hMRlza6w1MqfxLrNYuhCBGIr3/0D5WwAvTBGpCy+nkZA5m2Yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age132qsqclmp5d6x968x5y8amdn90v64rldy3assprr8g8wjdpecvmqwryah8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRUtqOFhvSXZ2b0tpZHcw
            OFBlcWZXNGVpakpKRXB1bGdkMWhpTDBQMlhRCnRyNE5rUTRnb0JqOXhSRDM4T25K
            S2F6cXR0N0tNaHN4QUtrTHhBK1ZHQmcKLS0tIGtXakRYc3VMTk5QeEszU0tjSTNZ
            ejhlVzBMMzdUNmxvZFFYYlE3dFE4RlEKmzv0p2vNGCVcbdrhtJst0XdAY8QtWp4N
            QGFhJwXSux7JKBlcg4e4KsME6/NnAjaIuCck+2vDzBqIKO+OyAjqXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T10:27:47Z"
    mac: ENC[AES256_GCM,data:452QnpF8g1dHceTmy9u+HtCWpMRdCwPrSbtTOCrWVqptpHUbhLu7YToDVnbvd+6WacaIBvWYEIYCweqxripAouvV0mf8MzsiqdBe9iUYdxS5cODbvnRR/iSzKv+TEZYzdgq25HWxkDJqIqbsmwI2+wHDMfPpYDwl3LrbWjwhpIA=,iv:686VqsBAWue2uMfvB+dmI2B2qwQYeUXkKJGxidvitWM=,tag:++tAUr7wzgsX0nrl292Q0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
