vmetrics:
    auth: ENC[AES256_GCM,data:g6965LDe0AdjH1ri0zpFkyJKnw/pmNZY95XBQUqfvjlRZEh/JZ+4HH0IkEUo6+XvPZYqI77Wc8yJLfct9Xi4c1eTCn49xHtp1eKi7UDfwErUP3bQnSN0tRJTVidAipwFtEWn7QGLCsTzhtjr8TIiGwU22oWdXFbCQFE9cF0JwYkcHKYrRfBVwjuujBKiRcqRYZfiJ9Ngl4WLq59o9KcuOzv3cVM/ZE6XHs+yBw==,iv:Q49WI+0O4MzeLK7TbKZFal5Q37UVjZ7+J2uyBQkgzd0=,tag:TOAXptEhlOHv4WNgQ0e83Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseWxFZjNZVHJXNmVrdXo1
            TlZlUmRVVUo3L2RNd2JRaW9meXJreitzcHpBCittYnd6SzFUVmdXL3pFZXo1R0tD
            eUNxNkdFT2lONHFhUndYV002Um1MV1UKLS0tIDYvQ3NsR2l3Wmd1N0hEV2NQVnN0
            aXNySGFoZlFSS3RXWnRML0p1dEJKRVkKCq3nICRZjmPjRejJarOHCTJ/3J12SjTD
            P7B3zCrZSC2ZAiuudqjRG1f6/f6w4D/jdUCsgRs497OqmqyYriqsvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWjZkRFRxNUFHK0hSUzJB
            NG1tVFV3Zy9MK09sSHZsY0JwZ0UvVU9ZeEZjCmFQaUk3R3JYdGd6K0FiV2ZCMHJ5
            STBZcE5PdUpwdjNRS2NNdUliU01ZSEkKLS0tIEJoQkdlNVhVcWNlS1A0a0swbmhK
            blh1Y0hBdjJmN3QxVXhCbTBqT2dYZ1kKSMlQrR4IcFHvVUN14WDywc7WZYBbv8Zt
            jOeIl3zZcyuCY+9eu5BIr0U1x1UGOM15NZBgTLV1HdIrQT47zUdzWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezx4f7szu3mf4e84de7vlw0aaxshfr3tjt6dm356g578ujkck9mqy6ff8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WWt0d1lXRG1wUnUyY1g2
            QjBhcmYxTkkrL3YzWjFnclV2ZW5GbmlMbVFzCjQ4dm85YmZBT1dtaUQxN1JNeU1J
            VGs0TkZWdVAxZmFiZmpsbUJQNERDUEUKLS0tIG9aUHkrelJFaU9kSFJKNWJ4TlBL
            Y3pZb3ZjaUVMNlpiVzVJV2ZmVEoycjQK8IHIx8Fd1iHkiiexzQpaKEVTaBj6vZfu
            MP3v10GLDG05MY5RVn4sL1zqwPHsfwRfZ7hlOZIsMV59wQ4rJloZVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T07:23:23Z"
    mac: ENC[AES256_GCM,data:OQp4n5kDeKtWDajT6bSEDSZpjsjEsjepgZZc0Dslir6Gd/aJ1t4k0hWq4N8ziQ1/42+eHDAkJpDFMzcX3BnK91YQIHowhu8zb42mG6XLZYeP2FhpIZRbHKa+3oyjc5N8ioPva6jJtNak10Q5HheGFrggQvTlDWmB4qmLxSnwK9A=,iv:qY8lq9qgLApXoXOqi0E1cI/4J7uZNc7fR5aQBEzAc9Y=,tag:chXOcx9bHKnc5fksVh5v7w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
