vmetrics:
    auth: ENC[AES256_GCM,data:Mxr5/RN/cHbZTlGBMhtZ3qM/gavzdZ5QZm/Z+cWCayCxzer+dk2LV18W/3Fb+k6ylQDuBYoo9PdnwOA20IvRkdnmUPFI5z7dvmG3sFlM79uL5bzXl8E1AncAAWFbrVaFy9ip8O5vo14iMGP4quxIU9GVRYr2L4NI/7Nc8oCSl/kUQil4wIOn46AsCALalwrgPUzyTi1i5+6L/xSE6pXz15GSjy3G2+FhjxIp2g==,iv:IXgBGWvPGVVFg8NAbrnSr/a+E8k+punmkH1sowXXpFo=,tag:b46Xevxomq3ZXqmXFsThWA==,type:str]
lego:
    cf_token: ENC[AES256_GCM,data:qxF3WPZlhX3G,iv:kNFCT0zJype1OrAqngAOsQRp1zxzGIUJfhTBwhACxTs=,tag:Z6W4fKvGQAfi3ATWaTGg8Q==,type:str]
buildbot:
    token: ENC[AES256_GCM,data:S02GVtA9CAlevVvzjP/S4NvRK0F/qhc0GWjL75+7nSXAezPwAIla+zt7ErApkz3zwd3WFl92P0ljE9bUlvEiZYjMMsBn4ggQMO6NmzsEFxOnLjhhWA5faX+w32J+UOWxOBSgBoPJG3Q+KxMMJLiieTHbn4Vfp8SzleG9wvqu/MdbCOVa6YRm7IMMMS6Ac1klPJSbSkQLCiRM8VjU/a1da3qwjLgHtDgyLU4W+A==,iv:6l09P+B816Jsyee8OlP0qAm/V9qQ4xLcqI92cRhyx/Q=,tag:4YLQu+7i2aBWoE8Me+1wrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZHFaYThlMFhjVTJlN2g4
            UFhSUXMvZkNJdFJPc3BlM2htYzJkMncvZUZZCjZlY3p0NWRienFmTXFIUkE0V2JI
            SW9PL2kxMkN1cElqOUlXNWZQYm91Q3MKLS0tIEpTVlhaeWVIZGZqMndRd1N3VHFW
            RjFxeVhzSnZYVHM0OG1DNUR3U3A3RDQKonQfiJhuDh45/JJk/JHb6xXqgPj78CTy
            PP6MhdGdOwXoXcPVQ8O6Cjg0OHgPHDxzpGFp60rTqMYwXpBQE6FGOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cExYaytQcWtyV1JSQ0tw
            OUtqVlNIVzNDLzJGQmdtb0s5a0ZidDBCUjBFCnd2WXlHVU16ZXJ1YW9NUVE5MkRS
            RGxxT2poRVpkZ0lkZDNMODhKZGk0QzAKLS0tIGdPNDdwaDJnS2QwT3BhZUt5YzlU
            Sk9veE1kbTR3cldJQTV6N3FxYVhjYzAKRkJzC8WcjLXTuruKsnh4ILAvxJMR422e
            e9+9VxPomv4dEtr8z2WHlENeWrUGoshOt52JT7U8awghAfSvP7CmJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hfx22rxmqsc6yzecnyld9lw7x6sqxrhx2svaz80ll2wevnfsvqpqzuy9sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVmoyakFvNDNnRnZuQitS
            L2g4SWpTS0FJWVdDWXdXTmVKSG1sS3hsdlVFCng3TE1qQStrUEtPQ2gycllTeU5a
            ZzRsYTR4S3BoaDlBbmFtViszN3NGcHMKLS0tIExTWldyQnMvZm5rZGRmZWNCV092
            S0lOdU16bXA5cGxVcHc3VzBWenQrREUKL1AQpV36+pBph9nRNgPQnnBZ/CJ/2R6C
            Gz3Uus0Jf8hLe6fWCnOOZFcI/8JibSBJs0x5LWwC04CJ0J2eWSMHIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T08:51:04Z"
    mac: ENC[AES256_GCM,data:XFdQLiSC9andNwHW8DBkfYuJ07eBaRPU3bsdXsT3QZge9fdHTMHMYiVL+yo3uhHuruZp4UWXiA97GZo/R+eN1oenkEjnrrdxl0ntQs60xNrsdZ+hltG25JcYlwRP6U8E9wkHaPTbwbHDBikpCPnUS6rVW+4ngZJrmnMGstPvVd8=,iv:6MgoDofvekrENhWnV4XgVwwFOGPF/mYx1FwT7jY+ZUw=,tag:C8l2A7wDRtt2VG6HRuEL8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
