vmetrics:
    auth: ENC[AES256_GCM,data:gSEqRzpqSQ5EoZKxiwimvq+UcCpQ94SDexsea+GbeiOtsN3wcyH8yKmH+Dlgy0VTO6dwOyEx4F+Le+frUlSEVjLnJbaNPv/Eh8CGLhLheCjqOJfA6mfuiWXBVm1W451YZ2KOubeJZzc3n8tEj3u/Kj30N6mjv7J/+B5gI8cDAjeALsn5QmyncVPyWg1Klam4YKe+Yy+J3sHtNxkI8BB1K+L4uqYh0e0gEbq74Q==,iv:x65jPFbodvp3/v09OJ0BIgxMUFOLBkpiKRVMoB8seP4=,tag:ZqofUypiY3voZscsM/tqvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeDFPcGV6MmZFQzJ3d3Rl
            QXBNKy9aN1hER1c1YUtrYzZRNkc4Q2FBSUVFCnUrS2ltWko2a0pLOEppd1pmcTQx
            aVBmZUtNZ1FRQTlyN3dKcGgwR3NieW8KLS0tIEhSc09RQW83Ris5ZWdZbEF2dGh4
            YmJQSmJDVjdGNWxSdmEvbHc3VHBzczgKrlRbe+hk6ilLCCd1Qem+QWyCjXzesxyZ
            kbHwtyPsfMK1AUfPjYsywune/HEdYNnk9TLCL9j0HbfhpquJFoOoMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZUp3UHZPTlpHRjZsWk1w
            RDhFcVZiOFFSNXNDTWhQYmU5SE5LOGNsaG5NCksyMnQ4TmNtK1I0dEtGLzIwZDVK
            TUs0TW9Zd1NFU3NlbVlPMmxKMXJiMDAKLS0tIGtmZXYyUmR3blBhZG5JaVc5cjVM
            SStOc1hGRXllTDJ2TnpXdGpjQnJYNDAKSXVd/7kRvMzOeDi2TS3j6LCiMmriSU0B
            99s3pecPuhFtZxJLe5J932p7kUNLdR1I+u7GVXXSDJsZmOBVkx2yUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p6n5yh9fy09xspwf29klfsa4zdrhp04q22gvxkz2vvm88vt9tunsdn020s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWkJDNXF2Wk96NWRkejM2
            eFBxeFUwNmhjd3ZPMTJ6NzAwMzBnay85aVNzCjh1UGtGRFltSDN5NVE5U0tyUC8v
            WnRzYkRIaHptRVRjTDlGTFJrUHdvSjAKLS0tIDJXeGNPbUVlN2ltdEh2MmdGRG1s
            WlRib2RvenAvMWlZM29oV28yR1JldFUKxksN0eFamYALF/TyvmwRVSGPUEGmLl+g
            v5r5uRQRw5E9NggUTyfH/AiDoC5luwDCO5hegxqN+YlQSLndI4I5ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T08:08:01Z"
    mac: ENC[AES256_GCM,data:GzN3XPtcTuscVuXWYKsuH+uR+kxBpKj2Q6mbfl7KEDvPNevvdASjpz9Up4Mz+WxVD/L+Co5h8Y74i2VhkXspYgcndd7o5a4dyzabfrFQwKNDwlGyU4KbRhbpStVBSfvWbu5hpSpSjKan97eDnTFC8p00HTKR1TKjEmbB3Z1vTHA=,iv:kk3S4OzWZ+GzYgtUkWSZpWGKp0Wch/gAAJR5ehd6WVg=,tag:5Pcy8vwoLwSlQLzYRM/cdQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
