vmetrics:
    auth: ENC[AES256_GCM,data:oxbj18DlfPJ+PEdIj6YEdF66ZZNar1l9Mak0Bmqu2AOZWlhCo2aRlrcGfvs7mORplvQmcfh5MwjTqGExjQX4ke28SZ7pszoLMGM3XR2BdedPNsO0KcI/zV19dAL1wijBr1c2qqDJGqqO1P0UzLaUbonl9bskG8L9+lB2pr8aU7z1Unejd/Qq2Ae/3x9Ku82deeP5jGWJkeUae9wADEsBPdbqRbv1bpW5zzmc2A==,iv:x65jPFbodvp3/v09OJ0BIgxMUFOLBkpiKRVMoB8seP4=,tag:wz5UVNBJoSl2994GYjVgpA==,type:str]
buildbot:
    token: ENC[AES256_GCM,data:38NXxDghxuRLPHaDqJ3iUqfewImSNAmMOEcc1+/wt6ser9KKpoO2nZBGrTOJF8DvsHHKYj4hPsBXBRtKVQy2f7eB2RkMjOTWZY/Q9+KgGFy5QEu1YdEPZ897Gk/E6APowQCRfJZ/ExUoxgoUumQSqMy2I++NuPQzlUI10yDDC0HwzLErnfWJDct+XoYdral2OG9GhMI0aglrlLtYHAPG7+dvqGm1N5jhQBrkOw==,iv:yZKW7ssLp+gy204C5ikwh3ivSrEtEl/sH+t17rsaMD0=,tag:umxk8szrR94gDFc7NZP4IA==,type:str]
minio:
    root_user: ENC[AES256_GCM,data:yOb0rhdGKjvFe1vX,iv:cKpsXvA660YL0+ut6cOOmXunFhserBOJslVehITNyog=,tag:7Ak5YnVxlGl7bacFWuoyyg==,type:str]
    root_pass: ENC[AES256_GCM,data:WR1nmwMZSKyiB+hG9zsYeDIlwLU5evSplS+F8hWnK/F8OdlrUgdgpAr6hHSHNv7k82cOtycKRUq0JlhKFVzQTcjvvGOPt5ftg1lteGJ+Nc0MYm5MHs+jfh3G5M+/9w7wnWgi6pYjWSjGKBPL0pIdR/bTYkzNbPGrYOIqhUjeaKYOXJTF77OypJAkCGijeKcTLkrf0j+5My1k4GiVHWbo09o9EryiJT+YuDdoBw==,iv:wWIk7CuOeN0V1qrICoKNGuXZdbXmK0niFFQvgJJdKNw=,tag:7KS2x+/qkqy5y4LqWNIsVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS1NickYrNUFrWS83bUEz
            bzIrNUxYdy9zYjVaMVZDVi9PNTcwdmgyekF3ClUyTDhFallLTU9aWnk3Qk8wcHF2
            VXJ6UjROSEJiOWNBdm1YM3ZYMEVxUHMKLS0tIHFEbzdaM2FBQTh5d2tqbUVHMmM4
            R0dpU2lNaHBDVFlrekpwbVgyczQ2MGcKA855+mgYImDqlENOYINg3SMfml9UOcp7
            z7RJaRIybWxd/usOdaCyfYtDqJTzZT9qNdZCm4YEFVYk9HZ4fHUzOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aFJGczBvVmQ4aUN4OEZL
            MngveEx5dHVCWERicmhIK1BDcGlSZFJJQ0NjCklvYjRXQ3prREppemdWc25CdGMz
            UEhzQlhWQVh3azdYYVhNR044c3lZRk0KLS0tIExUYmVVYzR2ODI5S3dIS0ZISitm
            Q1AzM09MSENFV2R4SDVkY2trcnVrTFkKjnsHGr/CkW+xW1owa4WYk2x23luUtQJT
            aC1kfRw5hjo5byMTb+NfKzW5Ogj2QRyHKxRhAkWvYGr7oSonnzd2Ig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p6n5yh9fy09xspwf29klfsa4zdrhp04q22gvxkz2vvm88vt9tunsdn020s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQjRMcEVyVFh5M2FaQkNN
            WDBoeklpS05xdUlNSXBSa0svYmpmQnRDSXdVCk1tc0s2WW9vajBLTHRyR0YyMnRr
            ZTl3N3ZDb3hBa3V1cWJoYlhZdGo4TlUKLS0tIEliY1I3VysxdGY5L1hZRUVDdXZj
            S2duS3ZmMVZJYW9HOERMc1FadlZIekEKaXDFW+Szv9WlqQMIr6Mc5qYlMyt8M19u
            DmMZu5Mzl2bLQK5LQvT/iLktWZZidYKfOuP73HpAFf8iIhYXBOLKMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-13T17:40:39Z"
    mac: ENC[AES256_GCM,data:91bqz+E6GInVIiZ67UR3u+ZGs7BjKgck5gNazotgNT+h9WzXLjR4ASahi3ZRmLb8aAJ/dkkq++oXDYnSN3r2NB4z0UXfD+7/Ic7ZxTjOcj7GiN6enVSndEdtupyc2qhCqRolQbGloaAkUj86QeB8CvoOM/rg26ErKEXIx07MYm4=,iv:XWfTe2vKiMSuV0gUKdn+rygC98ZVNO8f6uGhFLHJs2o=,tag:YJdBi6uzo8EJqU/6cLPzew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
