vmetrics:
    auth: ENC[AES256_GCM,data:B/6ZJhOopN0Cw4j4mgGKvpQAX4IZ93JZJl26SPEmarMUiN94F+6/rXmuh2m3Mmko3ZkQcjLL8sNc280qoKtdENpiNBQnEnvf+LR27EluJgK4uY3A7YLvSK0Gs8CUh2KxwdO7VIE+GCd9a5wAZ+y7n8s0ngwDmgGsrvYsyFzMovNiL3RYeGaSiH9CWgnHW6XqRtrwI6cWz9+GTXam/F6c5pYWVYcjY3BuQKQHJg==,iv:x65jPFbodvp3/v09OJ0BIgxMUFOLBkpiKRVMoB8seP4=,tag:TIqXt7dXh1wAW/+Hs9lv3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVnFsWUg0NUYxaVo4djQw
            Wk83aHcxWHdFSURRbVc5L2VQS3p6em4zcVhjCmhqNmtGWXFEeDB6SktBK243YzBi
            aFBNdjEwMFY4WTUxNW5WMXloRy9JWmMKLS0tIDNIcDZhVWc4VzJYSVQ3dVFLNGFi
            dklHVU8zWnVtOU5vd2F5RnJyZng4cWMK7WnaDfkuSQ+eh1o7+jLdNzyiRFYGiIY4
            7KJu3E+mgSEmmLqno78eyRpcBL9VrskYmMzeN2RIiImx1NpGJ1Nc5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZ3JJbHhrMEF0eDdqNDQ1
            WlFBV3Z5T3VFVXlWNkhVL1lVZ0FMNmNvYkJzCmEwazdVTFE3SUQwM1Zjc2dMTllO
            NUF0cy95ZFBFZ05mMjZIQnNteUJSZmcKLS0tIGlzZXpCb242WGlXVnJiT2hseHVS
            cVhORHFLcmRlNG9ISUUxYW1LZ3gyUUkKpt6UYVuPzmFlLoIS2Hm8fqc6icCkwtUT
            sCk3Y77BdzfoiQeEPi33wJKOfAgmpxq8w+31NFLGUqUlPbXV49babQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p6n5yh9fy09xspwf29klfsa4zdrhp04q22gvxkz2vvm88vt9tunsdn020s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WkRtOTJRaTVjUFdWOW1M
            ZFlEbXRXMklZbzdYNkVkenJsL2NvN2dpWFVBCjhXaGhRREVXSVFYeHpYVnBnNWtp
            VXR5ZVE4bjBnRFY5UUFBQjhuck5XekUKLS0tIDBUWXFYRkNRTitaQk84Ri9hUjZz
            YVNQZmpYaDRCM1RSaVhyQnA3QnM2Qk0KxJnF0ENOz1x6h/PdQ+ZYZQrQkyO9hZTQ
            Hlv8eANCXabA9oW80XI9grTpnjC7wfS2ROxh+gi0yTbdZzz39V7QDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T07:23:23Z"
    mac: ENC[AES256_GCM,data:vG0BlNkThnocP1R8S8bTg02tDBi6/JMV2WdENRn4U/k1rJwmOUia/gmqpzPSAtqKKmFEMUNFJT92aN4B+6NAckvXqdUTUCwqwwvQo0269LgSpMrYursroqICnxm9jw8qctxJ03vjc16Mb6OxjGLSw9PbzSD7WceAE2AhkIw8cDo=,iv:MQsZMPWCuQSf+ybSi6dC1+Pjad2nTZQAgeDeHURakjM=,tag:aLA2WK9yVWAyBEeU17xYPA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
