vmetrics:
    auth: ENC[AES256_GCM,data:xWAQoiWkwYrscZa5dXYI2D+1cpuR8zc/ttjBf7xgHzuxQRHc03nRCpm1K52q0K3m+xMLjeEvF5Tmv1n6cqKVlkuQWflCq4tyD3cr+JhJHQkHRlAS5Yx+AQQsIV5gDldMpZ/GiecsOG/Ry8ghxPOUjO4E/gQu7DK1jVY8p4nfvOOSr1mrYs30lrtDbcRp9hmkWyzfp6Y67u32LV6YBL3BIDbD3L5qi4G6psIv2g==,iv:x65jPFbodvp3/v09OJ0BIgxMUFOLBkpiKRVMoB8seP4=,tag:cNyMhNIzDX3lnw+TQf2+VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQzdyS0JycVJTWW0xTHRS
            elp0RTJrUFhrbDRrSUZqRFN4bHNNbGhTRDJrClFTbTNIVnJPNngyK25HdDdWSHNC
            bHB5MUF5dWV5TkhYTy9GaVZVTVVVU0UKLS0tIExkbVJzTWpqSG8wdFNsS3JDcG45
            T3dRbVNOaEtYMmVzWkhRaXRWL0JJLzQKcGmF078Je2JlLW9YkWPnPR52vY7WxCHC
            mISVjQHDQXs+SGa5uiwNK7riTN3qVLrFzl7CyIbI0H4/Jc7TjgfVMQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORURRNVlINFV0cG9BNGdC
            cFpCbTdJUG53OFJxRkFDODJSNmo3YWtwUDBjCnhaNFB5WkZNWXJBdjdVTElWcENY
            SWszQ3QrQzhSQk5YSGE5d0V5UnJ3bHcKLS0tIFNNOGlualc2N245R0xjR3hjVitt
            anQ4b2pRY1A2amppZmRteWhGbXdCeEkKnbX6bZ0gcK4LHe14r0Pmda6kfojNfJ46
            TmqxpRzlZVIIZGHSOZ5JWeQ7zDiU8EgI8pj/G/vvuxrZfTG9g3jQPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p6n5yh9fy09xspwf29klfsa4zdrhp04q22gvxkz2vvm88vt9tunsdn020s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTEh0amJJVk52UDMvUkcx
            N1dMUk14VDdIQVVrS1k2d1lvUGlGeG5qTHdJCjA3WU1tUFZlbERYcDk3Zm5NTFMr
            YXRETG1rKzZVaVEyMmZYVzh0Z2w2eEEKLS0tIEgvQTlZcVl0bGdXdlFEUjJ1KzB3
            eXVVVU9kcUQyOEdPMnBMV2ZCZlBVekEKwDsOpSkv0Hj4ETUxr7dWGxR3hv31Ptjd
            K6n34r2DgmSafTj21GcjCYc5pcMVtD6GUDSlVK6M2qOP8IGluXGjXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T10:27:47Z"
    mac: ENC[AES256_GCM,data:fypNpC+X50eXFx0RqnENBdWl4whp7dajItH5C3y9gOnco+g0T7fWMUFv2VDCvIrkOdb4QnBGiC56vEwGx7GBSN4wluTsYkY1TxR4et/U4E1KnuDi2IT0WnNa3tAEqzIsCdY0tvKjjiDuSxk0x/uC4Tgxp48XxiafiKftcalpfgs=,iv:iYCfqprUU6w/kEiDkZe5q9d8gce7vBqIuEdg90qz9i4=,tag:/gV43ErB23+n7PO1PAF+Kg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
