lego:
    cf_token: ENC[AES256_GCM,data:IDdfb3fMq0xbs+7tmkmNtdpWhV+0NYekCDYry2YXoIpfvSlntvseLA==,iv:oO/tPda0vvW564z6EPaqvrS4U2UGQH8nGSPmaQeBtSk=,tag:nov1Vbd+ojvyeIsGjKIH4g==,type:str]
vmetrics:
    auth: ENC[AES256_GCM,data:byIwlV1MaFLg7BqImVc0qYkzntGxCIXgCEtRLlVtvaaqrgotKhNO1809W3sfWxk1CxlzDNx9cRglcJavckx0dWJeoZjwck5NsMhxqlABsMAzDi2eftRozfY0QPZY0ERpzAaqjOtgQ+DTWR9IW8PP9fck/LJ7mZlGMiLQ4eiG3SyRjWnlMb3i9BKqMui4N/VavV1ofR/GrqjjytFilnZgnDgy39YmwVhuTq8flg==,iv:w5fvbIwKablXI6xmGAJcVLC1Zb1WrifLyzsEXfA24TY=,tag:dJAAIPY4F73RfWNq1roPHw==,type:str]
hydra:
    signing_key:
        local: ENC[AES256_GCM,data:rLYv0jASbJyA6Pe3AyA7Bb2JTNxLLC7MCrdktkR1rgG/pKLy3XIMUeXYfOG/F1wJtkRUPKrFhWlyiqRxpv930i8/4+pBoxv1pNSzOR3/zwcDsp2Cy8t9002xLNc4YZ1SNkCHBnR1x2E=,iv:DS9xhapQ/pTZ72LZgRRO8To7euHqQCGecfC9SoPfwvI=,tag:eyiUEFLNqzcAeuFKGaHjVQ==,type:str]
        r2: ENC[AES256_GCM,data:bKBqCfw9GZgryVf2NwZbajnzb5aHSQ2Gioi+wVdnuksvo6f62H1bUlcjhzxVz5SgjZSmaiL78hg0JOYXA3SbRuRvvLYEVOluhlfmljOILA7S4gtN8aE7/vUs/No/nMwpibeFf4qL2tdvGA==,iv:NIrkN62yd6dT+SbY+/bwHhwSovUUpDUOBKtHXea6xJI=,tag:G0gk3es5Xj8bkva13BbBtA==,type:str]
    s3: ENC[AES256_GCM,data:H7E5pbCxoEbB6ztxulQsxp2O10WZ/0VGWJcC7FFC6WjjJG3aq1W4OJjUNqzGmhNwiudItqPprQ6uxDxPrRJjVhKRFUD4f2qMoZhcNITtdAMIM8VKUV/H+L6wj3IoaTgeA9i38t928PnUAlZ8dOUDARIAP3ngUiIoo97rjnP04dOvedMf5B5hfOMGPg1nROWUfJ1AmXDL1tDJhBWP5tgEcgHeksGtzg==,iv:27WxlgaF+L6OGPtmWebYPEl7wM85UB9W7u+o+3VbeMU=,tag:nkmFDJnIKCfebzirqli7UQ==,type:str]
    auth:
        gitea:
            cassie: ENC[AES256_GCM,data:Pu2MWhWqdhBDAUBz3/snZiZ1xx5Pz9dy5evzfHrW/W+WxAosZ3QZjw==,iv:4mVVPqO4U66nG/ZYdJ+l77vUnvmOtYNAEZ47Wf69PUA=,tag:f7Um5KUWRqKAwUdNWHfDaA==,type:str]
infra:
    wrangler:
        account_id: ENC[AES256_GCM,data:aepb/23BHoL47/gsZli0MFeCR++gIQmvEkZLIDhVp3c=,iv:w2o9HNN9KhpUGt9yystqtmMZRTohU3Q/EmtvmhST3JE=,tag:BBQapWfGz2b9iPwjVfIMhQ==,type:str]
        token: ENC[AES256_GCM,data:HKUcMjBwYpeu/kdD5pZPvAGZHNr2UBqdJORCoO6nqFlgPMmzRzjg2g==,iv:imXyYC/ts36JTpyGxbAIAZevxCQXcwQtMMDaO+Pe7Y0=,tag:ytChoyeApliB3xahVJGa0Q==,type:str]
gateway:
    db_pass: ENC[AES256_GCM,data:AEnZVnv6uX3GzNsgQbwDZ8kTX+nohhYvbQeEFZ68ebGAVbqZhAF1bbx7U6DBzLV3XZLMhfet195qs9XirYPHCw==,iv:II/TQgRp0xBOibNPlsO8e4g0SsMjnjm+nKEb+GuZvs4=,tag:5oAb+ILx7r+LWkau50tOTw==,type:str]
    secret_key: ENC[AES256_GCM,data:dU7W9xYXz4FS+FIzRy2JUka9Ny7vw4a4WTFgJSE1Q65/bsXPu+PnJqSqlpilP7YIpoNNvHf1xQouPGSRbMcNuYsih7xzkZv9P6EIBHtjBXA=,iv:t7CwUCAr/nGPU6cYyc3OpAR3xpJ+Lx444Eo0THsnuQw=,tag:8zgsFkEnAasCOBwEBk4Zjw==,type:str]
    email_pass: ENC[AES256_GCM,data:unww3z0BDeqKk0e1rOf49XWoG5sHt2KgoGtWbLd+WsrZlz9HxIQnqZ/QSHTQ1yHFT8o0PSNdL5RLsVDA0bG7u1cWOCFX/4LZ3TmWhUmx3P0SVizAPIhOfQ==,iv:/HdegQ1LbGZb1vduxFxPP0gie0P+fsqRJW9pgW4y+Ik=,tag:aFha44hReRbh/6FnnMknXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWklBT1MxaU02WklXZnh6
            QXJBQlZzamRZK0hsOHk2eWtGeW9ydmZIN2lJCkVqY3UxT2c2NGJobVFzV2lGbHIr
            L1ZxaFl2QzZ4Vjh2N0RrTlI3Uk03T1EKLS0tIGF5STVTZW9sTDZ6Y0dKeGdndmtM
            YmJneC9xc0lCK0p3T05EOG9ROVN4bk0Kr+u7qxZ/3xrGgrA5XHUnHz0MKI3t+RXO
            0+1nGTarKTw3HsYHIxZuMuK5aqlJZJH6oniSkUDjAB3cotGTbmcpyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWGRlZzlqbnRQT1NoSFZx
            aGFLQUgyVmlYa2NmaGRrcmFiTFlOT2tqK3hvCjNYOVF2eWlIS3BXekR2YVFwTFFq
            L2RIUEd2bzMvTUo5Szc1NkFoczlWU1UKLS0tIG1EbCtIRFN2UjYyeVZxUGwzbFI3
            dmRvOEJKYWQ2VmhlbXdaazNaUTh2Vm8Kjiwv7uGYE+E28k10O0nK9Bh5I/KwOyJY
            hncrRa63T6PCshmK9yGMeagoN7mkL1e2PDNHJMSiomPS+9E4+GZKFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7l663nmqq87e46893dngcy8uxpfeuxlp42a3ma0x4wyuxltjddsecy06p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNy9CYjllcTJWbDc0Yk1M
            MURlWENIN25uWUJtYjYxMjVHQkdNbm9sNXhNCmVjOUtlaHBaUUp1YjFLRjAxbFlE
            MGxud0wxYXl2YjZwQUg2TTFPUzVTNG8KLS0tIGxwMldqeEZOU3ZsUFhkTnpIb3Fs
            UExkZFJlMi80KzI0bkZGK3k5c3UxZGcKWnkWj1F5blbat1fmwHLi42UmmcFuoteu
            d7KY7b6jb8LVSjQsAtZdMw6pWHW+i+/sX2fszIVH4+FcxCTcu4U+aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T08:08:01Z"
    mac: ENC[AES256_GCM,data:mF27iQOukU1zCiCwgnZ90QK4vCzrevpt+hMPngIQ5uW01UJIhmF0c04vRpbxQP8Yq5n4k7Tb1dsfwwG2uomSMT/mdXQrNJ5v1hUc0w+LsEY1CNfffGrP2+gpJJGdxKMmnAU+OplZJcF8kF1jAIX8wcsBUcCC0ZJbkcsLkpsAfuk=,iv:AKa59XCt4Sxn2Ei8Y7hegBoLTykQYpQAV2Fadu4pYr8=,tag:c7p0NQ36YNnAWdC5c4rS9Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
