lego:
    cf_token: ENC[AES256_GCM,data:XkoVqohA0yDBiiOcwuckcq7Md+qiy+bw3bZDXa10VVb/oIOAibi9yA==,iv:oO/tPda0vvW564z6EPaqvrS4U2UGQH8nGSPmaQeBtSk=,tag:CukJmfRWrioBStLjC0wBvw==,type:str]
vmetrics:
    auth: ENC[AES256_GCM,data:WKgG+0Aru+vXa5SV+FHn7A89oNU3Hc6GRxy5e4FMthugMnCirw3pY+llm/p6jEzEUUL8+dAsUkYKpMHpUvjJJDgZinkQFoL2OKowESJkSJvcogdeFGEMCZlxtYxqjyyktsPa3MnSZnefuicBvTvjsc7AXR+1tVP/Oqesf29214k1gZYDTw5td92KEGkdI1nf4BsA80UGHA9jDIaUB1PmfZcrX4yK5GwitpHV0w==,iv:w5fvbIwKablXI6xmGAJcVLC1Zb1WrifLyzsEXfA24TY=,tag:1S+faetlrYArRBcUtp6/gA==,type:str]
hydra:
    signing_key:
        local: ENC[AES256_GCM,data:3IceMcpCOXrWi0ttv8d5oVSbnF6PSsS8TfSFF6xvCYp8I6BuhzorG0envw4YMNrVz2n4n7yzwa0eXFt14ekSj75jGKq0y22GRaIMGiCUQbDNG6IqAyc7JOWs8t8rrG/owdz9/roCatA=,iv:DS9xhapQ/pTZ72LZgRRO8To7euHqQCGecfC9SoPfwvI=,tag:Udygs/yA8PYC3claQ8c/WA==,type:str]
        r2: ENC[AES256_GCM,data:/0a93HqlUxFa3I5HkInB+RX4L37XPujX0mIyEPW2BUI522RPgmVZsbzv9vsI/K7rKeFu33y8uPwPsAUCz/Po0XwQ+na4yVrd6vxcHrKYD0pea1j1B1BSpcK9TRXu/4nAx/QTpViE82YPww==,iv:NIrkN62yd6dT+SbY+/bwHhwSovUUpDUOBKtHXea6xJI=,tag:qC0V0T21cyox0O6PNOYL+A==,type:str]
    s3: ENC[AES256_GCM,data:6csZoQFgwNi4YH7Rg+pA/iyPV1Glska0w1IG0+9bscnIWpwpBBeIiKYPXnhIsgh5m7Rua6bkyWS9tgPNk9sVueXWVuIQ7zeuj54jwVOHyZZ3f3xBmH+BMGbf2LHZV6/5i0fh1KaKDs/GKQntbc4fvguAFgC3zsLJwtu8ulDJrEUqXZ5/NzC0MIx5TEMnFDzkds8IoCcq1xUMH+ApDZtKmuxQSyYshA==,iv:27WxlgaF+L6OGPtmWebYPEl7wM85UB9W7u+o+3VbeMU=,tag:QLg9AtiwL0wKf3KnvCVVgQ==,type:str]
    auth:
        gitea:
            cassie: ENC[AES256_GCM,data:fjDua36VNykAp4vZ+9J5Pa/KjTUUNMOmP504ChLsSfmw+G+KGKrnpA==,iv:4mVVPqO4U66nG/ZYdJ+l77vUnvmOtYNAEZ47Wf69PUA=,tag:r9czBVWGG6uen/Bv7X4aHA==,type:str]
infra:
    wrangler:
        account_id: ENC[AES256_GCM,data:vM5XSi4gEhrp8ayUltd9bYfC+7Ly/IApsAA4Xp0it+4=,iv:w2o9HNN9KhpUGt9yystqtmMZRTohU3Q/EmtvmhST3JE=,tag:cHkdrYjhZHLN8pyFmMlvFg==,type:str]
        token: ENC[AES256_GCM,data:AmQ69ObdOmdLAL8bCRO4UD3mYUzZetPKtj97MjzIjf4Fv7V3B6LMuA==,iv:imXyYC/ts36JTpyGxbAIAZevxCQXcwQtMMDaO+Pe7Y0=,tag:HsSMydbDsAA5s9aZNTDQiA==,type:str]
gateway:
    db_pass: ENC[AES256_GCM,data:0ogT8DeqaHC8Nk8xVrTNdOuwC53SypicH1yNrWmUhSIePKcFZRifdnnJ3+q/BMMTh5AEcuz/GKScUXv7x/cI4w==,iv:II/TQgRp0xBOibNPlsO8e4g0SsMjnjm+nKEb+GuZvs4=,tag:hnB+S9h8QY0LPNK2rLABMw==,type:str]
    secret_key: ENC[AES256_GCM,data:egCJodYW69YdTdapIdydZ3+bAsfpgWNmz/FjWEUSfMCXfA96v6u0AGHlr8u0iEDf6xDmMP4tbiSJqiwoAiljmF0r5hDQWS15Tpo/T/DdgpQ=,iv:t7CwUCAr/nGPU6cYyc3OpAR3xpJ+Lx444Eo0THsnuQw=,tag:6T+666zNd7lMX361tOnq9A==,type:str]
    email_pass: ENC[AES256_GCM,data:5K9CbyR3ZLKZldsx7oCC7AeNYI82YGjnli26/PmeO40mdZdy+yEiZ7yYJjZVOWTXLWajfc0jsYcodPxKGPyZ5I4O1nt5jk4jwzHyswvisGsMTJKJHSo2XQ==,iv:/HdegQ1LbGZb1vduxFxPP0gie0P+fsqRJW9pgW4y+Ik=,tag:N8FIY1lYjdo5botMChwgaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwREZxUTJmeGlYNDJxQWRY
            OEJPRW8zQXdVVnJUdStxeFJDZW9vK0o1K2xjCktUT3RIbVJkVFBOd0cveFozNEVG
            OVZma3Z1ZVFzQWxMWUwzRTl4YVhaSEkKLS0tIGtHSVlsTWJwMmxlYjlLNDd3V0N0
            cjJ1WjhpbEhQVnNZYS9YeFJUNCtYNlkKTxqQoqRCe402ryPn/tXAUbR8VWBZBjR8
            pMVP/wZjngoz4Z5b3G1DObTE3HIngcFsaAoBCWo/6Ze+AqGqsF/R6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVDN1MzRKNUVnd3VyeW54
            RnV2MWg4eVFzZ1cvWmY5bWhoUHlyT1hITENRClpjNmNTNVluaGVjT09NalNMM1Zr
            ZTkwM3IwQ0pqQk1kWEcvVkg5TGc2cWsKLS0tIHVicHE3d09nVWNBVzV1R2s5U25M
            UWEvUkhqWlJsRG1TS05zM3poR0QzR3cKpSh+FVWiXXhk5dOxeD++/ba/rBuzYMqK
            v831qPF86OH2w+1oJLk630ERjObxkwQqb9/q5qfto7sMbRM0PNoPkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kdctxllje2rw3kwpzell0rt6t7mruc3h3j5zfjelnpmahchjlaqs9v9vm9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL0Vnc3ZCejNMOExWUkdt
            eDU3c0RSRzAvK3JQMkU0cDU4NHdwWHpzYkJvCmxhMHlJVnBXWmMyNDA5eGdrc1B5
            M3ZhNjVmQkJKWGh6a2IvUGtScDQ0ZGsKLS0tIHFRWXVvaXhDVzkxUmp3SDU3WXhK
            U1ZKd3VwZmFGNDJsZjRtUENiNjFWUUEKz2qKrpapPG7ftskAnhCYAdp3UKksxMKb
            KVXNCwjl/2uJ7dKQB/xyFdHr+r3/99LXNWZeKg2n5tA+HrcfVSFIng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T13:14:54Z"
    mac: ENC[AES256_GCM,data:MmRkkStwrRrDgoFSW/OyAlfI1aa6ZfPls6V7nel9a1a0nkvlJCufduL+UI2KuhWXFwI7Asr9cji1IVlLilJGiSuzmmPB4QU+xd5BegkGuZ2FlCbMbdWPM8xWGXh+dPubMLswHFPIRJkV7zfiQfisyYri0SkpM//+nqq7532I//Y=,iv:jSSFlbJtWvoknwFFow92/AmJa+I0WqDzE9xP5VW3Z+s=,tag:6xHeo4zCsnPWLAwN0yTulw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
