lego:
    cf_token: ENC[AES256_GCM,data:zbrPOAwWv6EYctaMRBkEQ3kwU8teIN/VXsihFwrdWPBxvFLrlgwb5w==,iv:oO/tPda0vvW564z6EPaqvrS4U2UGQH8nGSPmaQeBtSk=,tag:akwcRi+wPQFYhYFVtNoIcw==,type:str]
vmetrics:
    auth: ENC[AES256_GCM,data:e0RX7CfosEaKd+EjWS593lNL2/O7XkCpLElhcaN+yXMX02l0DCMLZTSqupV3WRj+ygHiSJPuHr5AsID62kHfByej49vsbvaXeG/5ng6Ii6bwtivchH6Tg/58en8cY8VQzzK82opdlaB783o1AA1c5SMAVCWyEcBLhgsDCH1iyJ7EXWMbPlV8vw8a7bBgGxoHhDcI/4Y0TjtMqi1qvAg6uvdlrkFYaftBmMPrPQ==,iv:w5fvbIwKablXI6xmGAJcVLC1Zb1WrifLyzsEXfA24TY=,tag:1NIbtpgQp7aZlNLMpxiqaQ==,type:str]
hydra:
    signing_key: ENC[AES256_GCM,data:Rpjab/F1sDpSUaTF14dmtr6ywGmai2wCA2Ztl1zuooeLulhAhp7yaluvRQi6jAdDnqfMzp0w38Qr+D54NnEP7FnCqsif4d6ii6AKchcB4XM7d6pZLOoAUnbdn2nRxEPTRyXHAeYjqZQ=,iv:pVJtNzo5SeBq25ow1UZvnYb/iMO4CabFX6mgYFMKuZw=,tag:hRtCBmoEwTm7dODkmeiY/g==,type:str]
    auth:
        gitea:
            cassie: ENC[AES256_GCM,data:NE8opbgw2uwjYLdFt29Z3r3KVtlzf2WvrqSqXNxz7wBFFeNqoqShxg==,iv:4mVVPqO4U66nG/ZYdJ+l77vUnvmOtYNAEZ47Wf69PUA=,tag:Es50PfFeeNGxMZo/v2OYQg==,type:str]
gateway:
    env: ENC[AES256_GCM,data:RokIWwWygIJgL+tht1EB9NbE7VRUi1aoPZe8uiPiKMZd+kw/hR6kWYXv4n+ntU+QFDFrURDqga1oqg/ARv3NJpfGe7m+2sUUSw57qbz3vy+iEKrbXnbb23+4ei97+cXMd5e4IRJscPhgqavTaHQEqLbYL/wzvLbMB9s+foOBJuR/2ZUpNOELfjcZawRC+XMxOJCHQmnDDX9C3lYKFKCkxkAK2oI58oRh9l4CLAa/p5h6Ww6aoNz3eoBS5L7cegO3SMa93eFAOl6mLlOvZxSJCSc+NC4t3W4Ov07yT2+wbz9E5FamEs7SVTLIbXlvyEPu2JPt0mfk4EygsiBD1BktBkVRHz6O8XGE+kSLU3mxVPMCsO9ft/qE8KneTrIpERmt5r/vOdqQ4rx0gOKeoqVMhJ9geBkgntbXthFWQsQ6p9l+ml+QP1stwE1WvNGD/SlC/BVQ1ECL3V9zCMFkzRaG01SgbmmC,iv:NzgtRLQbf1JpaqKntSPHYOSoqE4yWV0PaevCvu9O0S8=,tag:YsDE/3l2Ap6Bd1hx8ly1Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMm9oaFRWLzZnZ3BuOGhB
            R3FIeExwU29XZHQrbHc2ZVgxd2RFejlJUUdZCnRLemJhaXRPLzNvOFB5aVYyM0lQ
            WFNIZTY1Y2hVYk94WnRZaWFha05wQTgKLS0tIFBpWCtwNG1abnhxT2F6YlpzMmJI
            WjJHbzRWTW8xVUNSOHUyQjdoZ05ORlEKb1YGrBcUMC+HMuxTkcA1PGHWHO2HSnKp
            FAwLKnD7WlyUsjFCKvBbWoj5ekH+5qivIBdRFJga+7sm8LzBaUddug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb0Nnd0dtazdGQy9iblEz
            T29BT2JhUmZ3RTJ4MHQ4YnZlcG1nc2pMaWxRCmdpUG93Wk9vcEhlUTY5S3NrYkV2
            TlJkU08zSkMwdTBNMFJ0Q1VVdmUvNGsKLS0tIHdZVjZ3YWFSN0E2ZWZDOUFvOW5J
            UktWL3FiSy83bTZhMHdyTWpudzZDUkUKO3vcI8QAlxsNeNIuXuIe27IhjcqiHNYg
            LlWsJ+2hHlAyL41J4MXIvSLRdnUlDQT+PhxGZkaoNN0l+wrE/1Z95A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7l663nmqq87e46893dngcy8uxpfeuxlp42a3ma0x4wyuxltjddsecy06p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN01sdTByNy9pTHJmaVhu
            WjJxWjgzeFFreEUwRmM5ZkllZ2UrejdVUGpRCkN2RDY4RnF1MW81UUtHWjA4V2Fa
            Ym1acnp4Nm9rZEcvS3lLZzFTWWRhQVEKLS0tIGMxY2QreTcxZUtiV1YybVJrS1lV
            VjMvS0tjMkdYZVlvY1dCdXJWbWF0aDAKAZOSW6P2L2OdnS0+Gn9ShmgUJQoLwS21
            mP898906/DbL+r6HZcVeF+17zOkKHNFcJn4vjPcKAEAfyNLxP6dSEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-19T07:28:03Z"
    mac: ENC[AES256_GCM,data:C94oO8rNZm8zo3+kgzdxYP3PpJ2/yOXa05kffV+Oh4hAPY8NtDXH/Oxy0IMS6LCAhwl6+TYM3zC49u8ncuQi5BvcnL8zGi77cy+5TMGcsa0IvQ4OcGpoeBuGRy+0I6BcR/uveBEURGqbAszCeeTNfbeQkv7jzkaSt65N6pZmzIE=,iv:RVWWsAm96mPIxnXtO3n1IU68Qnzd8rELFOVfmPYkSDk=,tag:npazrFcGVUYnvc6NyFTcrg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
