lego:
    cf_token: ENC[AES256_GCM,data:Qsj6O33goPTXXls2/abZz92V7trkR6u7XKnWiEEA4roFMtfOXPqpdQ==,iv:oO/tPda0vvW564z6EPaqvrS4U2UGQH8nGSPmaQeBtSk=,tag:mG1Kd2ZwuI2hViJAauOlDg==,type:str]
vmetrics:
    auth: ENC[AES256_GCM,data:gr6DjsBoQKJp1rW4C71ww9nej2BgQf2iPOKoD4A200/G3QLJ2HprAiq70cc9jJ/pXYEkQs63vaW8k5Fgb3E6fBPCW8D926KYl0OpKTrWbb1fmjGaZ2jnATjkgq3WMXb4xVEloG2SRDz5TamY79dQUBfpTGSsfGvrenVoBBxpLy7kxAInCWeHSo26wUXxDcmzZjLuLZW6eEQVV7gJx/ym2WL49IlMnoWTSm797Q==,iv:w5fvbIwKablXI6xmGAJcVLC1Zb1WrifLyzsEXfA24TY=,tag:2u20JHSEUVveV+acGmrzzQ==,type:str]
hydra:
    signing_key:
        local: ENC[AES256_GCM,data:7X5oO02P2fLPImaVIiaRB73bqqHwa1pzxZ/jGO9JktBpeyKq8d1BOeqzWhzSEaIsKlv+S5vIUGbpUVKNgN90NCqRREvsrKsPZCc8IEzUU+tBFflTK6IshVTQvTQaBENQcBKkendr8v0=,iv:DS9xhapQ/pTZ72LZgRRO8To7euHqQCGecfC9SoPfwvI=,tag:pkgpNGd+7WjmRsoR5Iq/9g==,type:str]
        r2: ENC[AES256_GCM,data:NsmuseqjpaNHBAIim/Gdj4ahpxdk66NAwWwpMtgfxdMmq6OCkfLaqbKs4p9CIb4ojH7BxOZ0oM3VHhK6+JxqqYrUHsfP+JSbYk6q87ke+CSLrYA0Wv6vSm+d57LyeYPLcK5vn9rCQnD93A==,iv:NIrkN62yd6dT+SbY+/bwHhwSovUUpDUOBKtHXea6xJI=,tag:9DKgTXtz01VdXcIk5C6GtQ==,type:str]
    s3: ENC[AES256_GCM,data:fIp2C6kyEHioWsoUZ4JKWyB1MZvp0aOwY+Pt+Oyi35dnkWrj/PurExujJaBNgYGpQwPCcx9vpgMpN+xZqjVyVC899N5PhZzasTf5QmGbqo6U+0vw7xJfaogvR9EuShRu3nRpUxG+ekoC2yJB3l8l6tWP+JPmZZBdKs+tvOeTFsCiU96U5AR+zQr/7ylEFCmDOCZ+ElBd/adeqYdplnKJApO56cQbaQ==,iv:27WxlgaF+L6OGPtmWebYPEl7wM85UB9W7u+o+3VbeMU=,tag:aYQES3nyAkznt9u2/P283A==,type:str]
    auth:
        gitea:
            cassie: ENC[AES256_GCM,data:sbweBSR5L70juVUPSnjhOwH0RX2m4EoHbgvKMN419MBEriCsZZSV9w==,iv:4mVVPqO4U66nG/ZYdJ+l77vUnvmOtYNAEZ47Wf69PUA=,tag:QNvipdSMQYUFFoyew0/6Pg==,type:str]
infra:
    wrangler:
        account_id: ENC[AES256_GCM,data:n1Nt81FDDl8bQ4AXcCdJfj8IdOJDUNByWMHazR/T0Zk=,iv:w2o9HNN9KhpUGt9yystqtmMZRTohU3Q/EmtvmhST3JE=,tag:zLjk+iOHyYZJv1/6LEGMZw==,type:str]
        token: ENC[AES256_GCM,data:dPQ4htEtlcymq7YCZF805JUUd+IvhhhiOWoVClRv1TkJ60YtHQjZvw==,iv:imXyYC/ts36JTpyGxbAIAZevxCQXcwQtMMDaO+Pe7Y0=,tag:Ygt+TjFcRWu59xx61nzOaA==,type:str]
gateway:
    db_pass: ENC[AES256_GCM,data:CD202LVzC3RzJMIVEomhjgHqytYu7AVgnzpOAFQ2wC6NuHVgBgw0I08/JbLkfoZJcNEbbvyS5uNBpXlX2T9KKg==,iv:II/TQgRp0xBOibNPlsO8e4g0SsMjnjm+nKEb+GuZvs4=,tag:edcVl0YHgETYm8Hzcn6UWg==,type:str]
    secret_key: ENC[AES256_GCM,data:i/kfFTk8zKV0McMg8bvhvszMfFqHapqDiI7hgWKk9/7tKLh/nV5W2B8j3xK6v7xeYWxHqlcvYI10GV9B3oA/qb3di5ami7gUdQgqCVZCyns=,iv:t7CwUCAr/nGPU6cYyc3OpAR3xpJ+Lx444Eo0THsnuQw=,tag:Hrj49yqag0euI5wTiiB8bw==,type:str]
    email_pass: ENC[AES256_GCM,data:JBJZhsW2AjZzwZrBE+/5te9+41kdu0zzq3Tv9msKCIXfjyXt7IRBt0zcIp6FNvBwUDC8BvFIcAAejbX/k5qrvWWk/NYkIrmjjNt3wBKqfL8QX8x1Yln+TQ==,iv:/HdegQ1LbGZb1vduxFxPP0gie0P+fsqRJW9pgW4y+Ik=,tag:ekaU/et9K2Ovey6HgqAkWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNGZ3ejJ2bFZISkg4eW81
            YWdEdmJkUTJyaExhVWZRVWRsb0g3QmJlb0NjCjV0YVBYaVluOTJybUI4STFaSXhV
            VG5aRzVjRmRML1ZtNUdrTzdRckZYejQKLS0tIEdyQk5qZ29mTlRxSzdUSzl6S0M5
            OUVlYzNUWWlIYm1CK1VaVnoxZDc3SGsKRgiaOtXaPKbabtNj0PqWqZavJ/yE29rI
            dHc9cqjM3Ap2cyJ7xtyjjR0OMRBUylZSqhOKDZ43xlN6UAY1auj0CA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMkQ5c3RKZkZUMjRxSlJw
            QlJzaXdPVzNkNUIvU1RKSml6SDZqSjg1M2tRCjRCUWJZMTBwdVJ2MGRPUlhjaldn
            NGJRY29BYitkRDNvQ011ZDJVb0RXVlUKLS0tIHZWVHhNUEJmV2djbWFrdDlnSS9Y
            YlFKYk5pVUNBaFJ4NWZMWVlCZUpocFEKV21cYFUtJx1veuBR8FU/VZYPHXuW027O
            kA894CVhxj3Zs95VtS7XHkJLBlUf/sPXj2Ago7R5MeWzVptW+ZaykA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kdctxllje2rw3kwpzell0rt6t7mruc3h3j5zfjelnpmahchjlaqs9v9vm9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OXBZa1pISkUxZnJJMXFy
            K0xiMkdwZzZmYllKbzlvSUNKaStvY1NoNWdFCkNsQmZHKy9KTm9SalptQVlsY0Qv
            UERIeFpMbmRPK0VWMU9sTCt3ZnJxZlEKLS0tIGI0K1dGUXBELzhySy8zb2piMm5Y
            d3FkRHZOaUtrZ3VNRWkzWk1LRjZFMU0KPaa6p+x8gzWOFltGrW+E+IcHc/f2dKzc
            4M4QJFPhru49M7Jdg6vQDggfg1FIcrzAxHCyinyCijFBe6w0wD6pjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T10:27:47Z"
    mac: ENC[AES256_GCM,data:qI4yr1tZEZYbmUifJuto8wf0kecj0ZqwtjJyuhzrnXZ44AihPWsVzQ4ANEEJboP6QKrbVzwhCMm3HXnk1VG5O+q/LsTUhSgOS1L1ncCOT0/xN0zeQESFjXmE4tGI9izvPlQ8QdRVw9DoJYeWdf9slGTfiBoPwqh4nctSu8Jux0U=,iv:U7wXDN6MSEGuJV8AVUfsDtR5aTXBgWX5h1VSIh752zE=,tag:yvhDhGZa9dI825JO4ag4hg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
