lego:
    cf_token: ENC[AES256_GCM,data:zbrPOAwWv6EYctaMRBkEQ3kwU8teIN/VXsihFwrdWPBxvFLrlgwb5w==,iv:oO/tPda0vvW564z6EPaqvrS4U2UGQH8nGSPmaQeBtSk=,tag:akwcRi+wPQFYhYFVtNoIcw==,type:str]
vmetrics:
    auth: ENC[AES256_GCM,data:e0RX7CfosEaKd+EjWS593lNL2/O7XkCpLElhcaN+yXMX02l0DCMLZTSqupV3WRj+ygHiSJPuHr5AsID62kHfByej49vsbvaXeG/5ng6Ii6bwtivchH6Tg/58en8cY8VQzzK82opdlaB783o1AA1c5SMAVCWyEcBLhgsDCH1iyJ7EXWMbPlV8vw8a7bBgGxoHhDcI/4Y0TjtMqi1qvAg6uvdlrkFYaftBmMPrPQ==,iv:w5fvbIwKablXI6xmGAJcVLC1Zb1WrifLyzsEXfA24TY=,tag:1NIbtpgQp7aZlNLMpxiqaQ==,type:str]
hydra:
    signing_key: ENC[AES256_GCM,data:Rpjab/F1sDpSUaTF14dmtr6ywGmai2wCA2Ztl1zuooeLulhAhp7yaluvRQi6jAdDnqfMzp0w38Qr+D54NnEP7FnCqsif4d6ii6AKchcB4XM7d6pZLOoAUnbdn2nRxEPTRyXHAeYjqZQ=,iv:pVJtNzo5SeBq25ow1UZvnYb/iMO4CabFX6mgYFMKuZw=,tag:hRtCBmoEwTm7dODkmeiY/g==,type:str]
    s3: ENC[AES256_GCM,data:XhXZcXyBtpvqcAN55zE6T6JcjuqPxtJebPoP42tVbgLsNMHUzG9uUQ6soPy+WZI9Cvx3iF/DaWQtkweVYS+DjO3/MOtQo6A4RVxcMoHqRWqxlN16PLwLsGeB/SCX9AZs7aZ7taMI+u/n/SwX23eGy7ryeUwEawSyGcpja04KuK527pLcitBU9IxMTAn3ZuB6lMWnrbwMxKDgJA393WgwE2k3vV6Guw==,iv:27WxlgaF+L6OGPtmWebYPEl7wM85UB9W7u+o+3VbeMU=,tag:vmMTxf5M0W0ditxgShlCBg==,type:str]
    auth:
        gitea:
            cassie: ENC[AES256_GCM,data:NE8opbgw2uwjYLdFt29Z3r3KVtlzf2WvrqSqXNxz7wBFFeNqoqShxg==,iv:4mVVPqO4U66nG/ZYdJ+l77vUnvmOtYNAEZ47Wf69PUA=,tag:Es50PfFeeNGxMZo/v2OYQg==,type:str]
gateway:
    db_pass: ENC[AES256_GCM,data:crbRmfAcONIlvCKf/CGktTjg40BdqfnPs5cHcJzu0LS1Qvxl27TZQMDnRehOS7/W7Gu9GMugzVkipbSohBIZmg==,iv:II/TQgRp0xBOibNPlsO8e4g0SsMjnjm+nKEb+GuZvs4=,tag:lOZs/0F7VLRn2ExZAkF6sA==,type:str]
    secret_key: ENC[AES256_GCM,data:vjuPOs3KuI/3YJLBIaB5QexHz6qiuvz8P31BvpqQjx+JOD3bAyWyDeRhF7pyilTthzeIf6fKNeqSivpxqKD27rIm1nkEGwJfbDpxs1P+pYc=,iv:t7CwUCAr/nGPU6cYyc3OpAR3xpJ+Lx444Eo0THsnuQw=,tag:Yf+OlZcl66DnTYZoJBDxsA==,type:str]
    email_pass: ENC[AES256_GCM,data:Ay0NaTb7mn+QCZZ+4MhoEZ2NZCev37HU90zWAnTTfY4n4g618mv8/w39dbkKQEyKWzDeOWnmqMGaFf5kfBxa7bG7rWu5KbIBKQFHr4QxlqS+Tc+Sk/sCjg==,iv:/HdegQ1LbGZb1vduxFxPP0gie0P+fsqRJW9pgW4y+Ik=,tag:CW94o62FK1xhcAnRM/eCHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMm9oaFRWLzZnZ3BuOGhB
            R3FIeExwU29XZHQrbHc2ZVgxd2RFejlJUUdZCnRLemJhaXRPLzNvOFB5aVYyM0lQ
            WFNIZTY1Y2hVYk94WnRZaWFha05wQTgKLS0tIFBpWCtwNG1abnhxT2F6YlpzMmJI
            WjJHbzRWTW8xVUNSOHUyQjdoZ05ORlEKb1YGrBcUMC+HMuxTkcA1PGHWHO2HSnKp
            FAwLKnD7WlyUsjFCKvBbWoj5ekH+5qivIBdRFJga+7sm8LzBaUddug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb0Nnd0dtazdGQy9iblEz
            T29BT2JhUmZ3RTJ4MHQ4YnZlcG1nc2pMaWxRCmdpUG93Wk9vcEhlUTY5S3NrYkV2
            TlJkU08zSkMwdTBNMFJ0Q1VVdmUvNGsKLS0tIHdZVjZ3YWFSN0E2ZWZDOUFvOW5J
            UktWL3FiSy83bTZhMHdyTWpudzZDUkUKO3vcI8QAlxsNeNIuXuIe27IhjcqiHNYg
            LlWsJ+2hHlAyL41J4MXIvSLRdnUlDQT+PhxGZkaoNN0l+wrE/1Z95A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7l663nmqq87e46893dngcy8uxpfeuxlp42a3ma0x4wyuxltjddsecy06p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN01sdTByNy9pTHJmaVhu
            WjJxWjgzeFFreEUwRmM5ZkllZ2UrejdVUGpRCkN2RDY4RnF1MW81UUtHWjA4V2Fa
            Ym1acnp4Nm9rZEcvS3lLZzFTWWRhQVEKLS0tIGMxY2QreTcxZUtiV1YybVJrS1lV
            VjMvS0tjMkdYZVlvY1dCdXJWbWF0aDAKAZOSW6P2L2OdnS0+Gn9ShmgUJQoLwS21
            mP898906/DbL+r6HZcVeF+17zOkKHNFcJn4vjPcKAEAfyNLxP6dSEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-01T16:29:00Z"
    mac: ENC[AES256_GCM,data:kqgGp/WlEu8VZoRVFQKapQOf9FhwbMJvoZwqisyeRQ8Jd4cR+NfcT2d4KPCfkpd8oNB9Niefv66IIJrefCSq6tHF3x5FKmylaAs264e3d2oc8nzYp3npa7m+p4EcH6QhLWsM/XHrmkd03f3UJ2wBBtxVzs4+HnjV9DltlprOQ3s=,iv:qacXLWKboIIn3X8h8vXvrCE10U9Kj5AiPGhtcnojUBs=,tag:CcfJFlJNF1pgNzMadF/q3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
