lego:
    cf_token: ENC[AES256_GCM,data:738sCW43okkI2nAP2y0f81RXbmlqXSuF8f1sAbxygapw28USirAO8w==,iv:oO/tPda0vvW564z6EPaqvrS4U2UGQH8nGSPmaQeBtSk=,tag:H1N52WRqVZ0cAa+PaHGgVQ==,type:str]
vmetrics:
    auth: ENC[AES256_GCM,data:aD8sgN2aNyGLFFPWkxMB4/VTlgXmVDu0v/lcvVkuNN4WBSISvDjXDvlqgzrUXUlh0u33khwL5bNZ3NaF1TQXQ29RG9gkrmryDJgFqcHInFllTm02v2uGizBmcEJ04mIJUHTu9N6RiOOhx0U9vomysTRZW1rr+sSCisQuphq0kHvLaBxuqaOQdc4BUKSiGAJs2A+Aotc/h6R9XXidP48PGePIBCe3ExeGgrf8Tg==,iv:w5fvbIwKablXI6xmGAJcVLC1Zb1WrifLyzsEXfA24TY=,tag:bq3z9pZMAVmpYMzvI0Cn/Q==,type:str]
hydra:
    signing_key:
        local: ENC[AES256_GCM,data:iKhS1Zwk6IhtuubJSlJLX33OhpTMsHBCwBhTcdVYomcILo074Dnrb7pJfflC2A+2mzFo4zUsNqj1Firx92orwFh1M/qbP2SnT3Vy0EQ6GMZs/66YJ28RrAIajzv5Xc1Jzyl6Iui3x+U=,iv:DS9xhapQ/pTZ72LZgRRO8To7euHqQCGecfC9SoPfwvI=,tag:ssG5K3D4DDq2m+QmSVwojg==,type:str]
        r2: ENC[AES256_GCM,data:rOg7+swqip2RKW6lnVvgPPf67AZXUuLvI9oEg0Of7VOJ4jZXBq7N8afn0+/guMGkSbE4URaKhAGhnOq47RRs3NLVMSfriw2tnJ0KfKrQSibHqFRpj/Fd8o0EdW/lEu+hOCVz/7raWoyacg==,iv:NIrkN62yd6dT+SbY+/bwHhwSovUUpDUOBKtHXea6xJI=,tag:TSECplmrYNuLlhiVL4JfNw==,type:str]
    s3: ENC[AES256_GCM,data:emut/m8IwtcFI5arBPyAsp0ET5tnzA8Jv7jgwL/Nd6qATrbFo6w2DUC20PhWFxGITennG2y3tTV0GYcDrOzhDrtndo3QxaPzrT7BfbmY1Eg4pniSGgApXpyGUbx7j9j7O6u1X6Q2AOKFe8ShAFgu77Lr34skvdCaJ15n1/sxQ7TaEwalQsgzfQBFmy7fkf45N2pPrKZBfphFbNwrHifTh3wc6gOnng==,iv:27WxlgaF+L6OGPtmWebYPEl7wM85UB9W7u+o+3VbeMU=,tag:sOGsl5CJG4wZSVdSACNytg==,type:str]
    auth:
        gitea:
            cassie: ENC[AES256_GCM,data:3DWjlXJ7jHuErqzcvIWzxtCEnWjYWlkcq3fR1gpAtMl7GQmY3affwQ==,iv:4mVVPqO4U66nG/ZYdJ+l77vUnvmOtYNAEZ47Wf69PUA=,tag:ohUmmha7lmuQe30rMnF5nw==,type:str]
infra:
    wrangler:
        account_id: ENC[AES256_GCM,data:Dcy5Dwd3AZSAZ2hJhh7r2M4dTakRduvf76ZynCjdeFQ=,iv:w2o9HNN9KhpUGt9yystqtmMZRTohU3Q/EmtvmhST3JE=,tag:u7ZalSZy3x0R8UtEsSoQ6w==,type:str]
        token: ENC[AES256_GCM,data:3LhIBgfjQ91EPEI5sJAuYQDmdPpJ0gbVdtomm4zQtbxDVfWP02PyQQ==,iv:imXyYC/ts36JTpyGxbAIAZevxCQXcwQtMMDaO+Pe7Y0=,tag:blEbWd/QL2Mefq1xfLUziQ==,type:str]
gateway:
    db_pass: ENC[AES256_GCM,data:b2GZ2R0Ncihfy+HJyBZOcgPo+tyZ2sIBJfSWwFR4vdrjgR6gddva099gQVf4qFH4lnSEQce6pdRrnS+EUwwVxw==,iv:II/TQgRp0xBOibNPlsO8e4g0SsMjnjm+nKEb+GuZvs4=,tag:uG+EUXwg2XgvwG40eAyqgQ==,type:str]
    secret_key: ENC[AES256_GCM,data:IpFz86T9Ghcfs+fSGSqf+lr79xGrLs+UQcs/WpicNknVKyCSracCb6y2AwtZuhORIDZm5ntPJN7UoOzdb9fcHMAId8Guz7Y44ONr80AN/oA=,iv:t7CwUCAr/nGPU6cYyc3OpAR3xpJ+Lx444Eo0THsnuQw=,tag:izTh1VBVSys/xhJDAZmPig==,type:str]
    email_pass: ENC[AES256_GCM,data:rLB7QNYqlMSHVzn0FP1xGvuztObImH2Bv6/ESpn0T/xow1af3CU+c3Ug7x3JGLsRJOSIFThDkgE9N4w+N5mCWlVvEnIWiJ85QLcM5l2JJXWL2tSSByujCw==,iv:/HdegQ1LbGZb1vduxFxPP0gie0P+fsqRJW9pgW4y+Ik=,tag:d1oBiUJdG1fGQ7jxZ0oFVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeXpONHRSY2ZzV1pncUw3
            Y1V6dXdIbG5aV01oMDUvNktkc0Fnamp3aVd3CnoyTUZrcXFwME9LZm0wSzZNTTEy
            a1JORjZWbmdyQVp2eHNHWWFPSTJ0UUkKLS0tIFUwMnBtejd3azVWWVJrVjZqL2lx
            c2l4OFpiNmhHVERkNFdJZFIza1lQQVkKhJs7izcglJcAcEatxzxkA7ueQuLGtoxU
            TWb2xW9vLTZR2CDUgcxSyXZav+qP5PoH5icjmai7BFZTyjGayW/E7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMUJ3eTVsWTdrUW9nR2Nl
            WW4zMnJzMktyZGFzRVRwUUFURnR1azlrdlJjCmhxaFNxZ1dRUUpyekRwRXh6dWxO
            cWtTeUxjdVoyNHNGdjlSZzMzS01pTGsKLS0tIGxFNUpIamYrS1M1ZytMV1Z4ZVhu
            bjR0cEpiYVlSeXh2NWtGbWRlbmxUU2cKB++5SXu+pKs1zLjao5TJHHuERadegbYR
            C2KE2k81w1gyZZ9PUNlTByM7eBQ3dCc7UrWYxLUqE3nxS3K/XXpnyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kdctxllje2rw3kwpzell0rt6t7mruc3h3j5zfjelnpmahchjlaqs9v9vm9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNTR0QmZ5NE5kK2Z2YnRY
            VlRjTlpSQkgrZHV1UURBSGdabEF6WjljSHp3CjM4NGQyc3J6RDZyTHRObmdGZ0dO
            R0s5NStQWVdtYStRMmRsVHFQRC9SZWcKLS0tIGlYRFU0UWpha3JENzZ1VXRGMWhP
            czdjT0FiOXZvaHllQW5KRnhKYzhadzAKL9Q27IV0w0mpcIhptTLJGY+ZpG+zfa/B
            hPg6o0PTxBR3FuIuBsjuxuQTxyab0WvBHs20Hlm6wMdXAfISHIHtYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T07:23:23Z"
    mac: ENC[AES256_GCM,data:e8BPHL9Cnf8ohSicuuYecdfnxMna+TUhAwJecZ2uB8lxhLJtYkgHCyJDP3fG6rQoYXACFsNMnP8HHfnbQGo33Rj59IdnFIutBIIvNPYvDrWwCYYtrxYyS4S1L938t4SUUKue7Pkk8sgPtgqwfmQzkjANpgqDTLqsjMVz6S9OhzI=,iv:7eKJtULoifmbAXO5+57PS1KnmI2Uv83VtvA0t0pxJEg=,tag:fmouu6Z7UxQe4U7OW+Dauw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
