lego:
    cf_token: ENC[AES256_GCM,data:YoJ7YTpLv0GNXwuxaG5KzXFyUS4eTXdTAKI0EGc6hD4pkbP3djAaxg==,iv:eeC0GdKrb7V1UCUKYQKL1BLbdl3efi0JDFFtnr18Zn0=,tag:15j80Gbcx6MvEu5nwH6WJg==,type:str]
vmetrics:
    auth: ENC[AES256_GCM,data:TyxIlSEkwCB6yZNL5fJZ6i2hMDH+cAtfIzAjPkUpfxnEQg+zzi0m007bB+REV7eaCCcRKk0wyUKuz4vkYU6Xm0crPQMGphHaqxETOFQkwhVdtNsh3IqvPt+W2LFk5vZHBSell3B2CyHAp1rFWBYgv8E8366+N2y3tZrqXqTrZJHAVUE4RTJi4l4S+ZAsSYEZQLWmNmsUFEUkp2byIsn6cVldluZfm2bSyONwsg==,iv:FJPyNYYtFqKK2CsrN2IHkIkJLwt4DYmzyIUarwrlfng=,tag:iK1UPKSq9/RE75joGno03g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDejZrcVBLVFZXeVo1ZE1H
            Qi9tdlhkUHBOclhhTTkxY1BqOE1nOXcvbXdRCkV5WDIrOGVrWS9GdXVUbHAwSFFq
            a1I4M3puempJNXo0cXZSMHFucXdWNDgKLS0tIHMyb2k5bld5c3dudGZmNE80cTdE
            QjRReFBzZmxYYzdrbU1zdUIvRGczSG8KWTqkZB1yaiJQ0MJZj3ofQv2tl8POfKz2
            8VfC40nRjbcT14whhp8qW7qz1ZkMNNRQYWt9segarl2DnU9FB04rVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZmdRalIyOGk1S3ZDL2xo
            Z2hvZ2NUY1NEVXJESWh4SHo3dWhGWUw3b3dFCnVoR0hobGdoK0R2ang3ZDJNNmVQ
            NDkvYlFTNFU5QVIzZUFiUUV6OTdqMncKLS0tIFlhSi9vbmN1V3c1YlJjalNQbzBB
            dXVyV0czT1d1ZDhjU1ZJZEJ5Sit2VGMKopcRtN8qRWf+3keep4mFXLzMSsj4f4Nw
            vJP1j2gUc7dA5ASAXIkPzA+Mre9nbsnI9Z2RQR4ed5BEwOs7T52xtA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z48mx0tgfe9x5srtthqxllz03rfmtg620waqlplxmc0xvykatfdqxa0xwp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TWhmWWw2SmdpMnlOQTZV
            dXZORCszOGlkcVJxV2tMOEJMeHVLNWZXc2pvClpxcGFmTldRaklRM2tBSHdYZnZy
            MW96RmZDSU45Mlk1NU53V1hSemtad0kKLS0tIDdITUUzV0psVHFEN28wYjFkazEr
            aGdZOFYzZDYzcDJKZUo5aG5pUEFQTk0KG1eO13Niix522aYJrQm9JlE/5kG18/n/
            JjS99m4/KEQBQaiO+0G+hSk+Af3p8RF6zkEIOwJq2LmmPLf+6ZpXYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T08:08:01Z"
    mac: ENC[AES256_GCM,data:NKaemyU1o+cDgVGpGPFVsoPfvFR+eKZXv7qH1zznGpdD2xPr5colGThJLSQN92GyozcA2DuHgw7GGxCybOV2rfPY6VOMnXCxp/JY+rwUQm0Ptlc1ay5FYrhvxG6WbumUr3Xrk6YfuUrwcB7IwQvkTjKzxMfHF61mm5+AxVtiX9Y=,iv:hDcWSckebGhrmqC898pkTFIh/WPT8VRUzIB4uw9Bqno=,tag:jhADdV8hALejWGJT0pQrbw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
