vmetrics:
    auth: ENC[AES256_GCM,data:MSCf631ybwUtawFOj8KgxyQHagnbrN3GGTi2oCt41rPwG91l85n/gjzwQ+/cVsO2MzVPk00P/TgxLjm8ISGlL8tPgq1xmBKx8eDfg0EojzxvPf6RzIe4/iAv19MV63Xd25hbgUbQZDuyzi3MXYriB7AT1vn6eiYBQzuBFpgwn1DOo5ZC9JBraXwF84DI7eJ6nZZnBzKF6SOsFA543/DQVopSsB946elxGYZiOA==,iv:abGTu/sywBaDpBYYExivqxaHpk3rTOCKmcf8USczVXQ=,tag:FVEFa5ZoRDjbPb2GnPBPgg==,type:str]
lego:
    cf_token: ENC[AES256_GCM,data:lYBSkK4q6zYv8n0wP4EojdtBguTl3qlKdzcwa1fCyP7xkJkhSZH7FQ==,iv:mSrMj7ze50ue7V5/3PO29Wq38iUDxzXJ96DUeZU1RwU=,tag:pZl9XIj2ecxbEvOhuLx/ig==,type:str]
dovecot:
    db_password: ENC[AES256_GCM,data:W7Wq4G+cRpPSSgj93ZraEKQrD1bzev+Gzjj7Z5/BHpr/7guu3FQUZVwBUNj0VtAO7GPSU7LqPwFqw0yyBWGPXsqXsF/rbACgS1eWxL0KTG+fSU9rk9+DAfYPDYH/0Ipp,iv:dX6HkDhz3r4huRWtP9UlxhKycQg5TMG+Wwei9rtVz0I=,tag:/NfNuuKae3arWymXMOtULw==,type:str]
rspamd:
    controller_passwd: ENC[AES256_GCM,data:eOd42iMz82eC9Ntavi9PUGNu7C258kirgxtcGXDiJKR98DuSNZk/oGjNU8X1HkiaGCnOvTNvSQE6p6okHXH0NMjkdnsh9+aiaBnmHUKn4rpIcAcR/CUbLg==,iv:Tp0vQji0u7aPydZLB6ARMhkLv5BGj4KjOzVKkWXCUlQ=,tag:klJHk3cdL4+X+BbX6G34rA==,type:str]
keycloak:
    db_password: ENC[AES256_GCM,data:t0avCZw9/QMYDCYJ7Ze26olpHKueCEbbMqCTrqy5XjMXOC7TGNc79dIXWU4=,iv:DZYnh2gXk4dLWEQiiJQ+264yyXgIKaPQ/KjLirNCMJw=,tag:y4cjEnWGdeWt3hKxd4Dy7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SElPbWZxSkViSWJWYlZV
            SVhyZFBBemdoaW1GdVdxemhOc1YrSkt1dkdnCno1eks0eVlMc3FKdDhPRHNDUUZ2
            dHF2Y1ZDdGdjMDQ0MFdtcDBOSXlWcFEKLS0tIHdDc3dkcFdwSDlzU2VaK25sdXh4
            bWg1cGJzZHNHRlNkZEtteFo4Um9YNHMKYwXVTnifRlsXz4j6FbVf6lT88fp4HYTS
            C4Bm8jCpj7hhwp8l44Yy0AJAbcVI/MKjB65E6IfETJuBIHTAfE1S3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNGFiU1pvZ21DSytwSlEr
            UTBoTzErSzRnL0RhY3BreVZ4SjIyTDgyTXhZCktsbVRtVnFwRGtHcTlEK0R0TVpB
            bXNheDcyYkxJZmhiRDVneFREdUF5NWsKLS0tIDdDMDVSb285aFIyMEdHYVZGVGk1
            SHVQcktZRytjLzFQSDZQclIxNzRHTDgK0U9txM4A0h2hM0Gtgr0kOMqM6ZZSKh7G
            xfBQANSGjxZWEIJDj+tOIKqEn4otTlaHuZ9uK0Av+3uIT04IDN7i2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qzma7prftj6d4atqcmatdl9le0tuuqzegm6f8e9gkwrp3pja0aaqs49g7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ0IxTWI4QzBoRm00eVRi
            WVpSNGVSVnpQbU4xR1N3cnMzbk5VYWUvZ3pBCmc1UURQNkRFcWI1eGlTaDExRStS
            OVFKRnFybHBMWU0rNlVuSXlhR3UyMlkKLS0tIGVwM3p1V1V1MWJQV0lYWXNhbHQw
            aUp0RzdGVnd4b21POFE2SlpHZWpRaWMKwrHS97XKl88gZMCPzJpL3FsVx9SLc8rp
            sgS2BnnrycdRtmm6wUnX/z2BO+XJIuK/P4J2Z6HlIWUNxBZU0EhPfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T12:25:55Z"
    mac: ENC[AES256_GCM,data:c+JgH0+Vz3kEqEo6JbB98WqMnyoPMG4scwcy5SzZIBC3Rv9+HC3P859oszv4J7cgVfRm6g9RQnawPaThElljs0FecsyHwX3OUrvk+ZTcFwpLDjx35PorpLXvj8LsweRyKGpD8EybefMVDv5Eyc2LsEAjh9FZxJHvJsjNm31rQBo=,iv:iaeq0CEVCoc5SYlt7eAXYdT67op59B6OJ6D5UOLH2mY=,tag:vKmQaNGteuzumP4vgOjwBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
