{config, ...}: {
  services.maddy = {
    enable = true;
    hostname = "mx2.soopy.moe";
    primaryDomain = "soopy.moe";
    localDomains = [
      "$(primary_domain)"
      "services.soopy.moe"
    ];

    tls = {
      loader = "file";
      certificates = [
        {
          certPath = config.security.acme.certs."kita.c.soopy.moe".directory + "/fullchain.pem";
          keyPath = config.security.acme.certs."kita.c.soopy.moe".directory + "/key.pem";
        }
      ];
    };

    config = ''
      auth.pass_table local_authdb {
        table sql_table {
          driver sqlite3
          dsn credentials.db
          table_name passwords
        }
      }

      storage.imapsql local_mailboxes {
        driver sqlite3
        dsn imapsql.db
      }

      table.chain local_rewrites {
        optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
        optional_step static {
          entry postmaster postmaster@$(primary_domain)
        }
        optional_step file /etc/maddy/aliases
      }

      # catchall routing - thanks:
      # https://github.com/foxcpp/maddy/issues/243#issuecomment-1406567636
      msgpipeline local_routing {
        # mailing list lmtp here

        check {
          rspamd
        }

        # do the rewrite so + addressing and stuff are correctly handled
        modify {
          replace_rcpt &local_rewrites
        }

        # destination_in block takes priority over destinations
        destination_in &local_mailboxes {
            deliver_to &local_mailboxes
        }

        # deliver to final address if we handle the domain
        destination $(local_domains) {
            modify {
                replace_rcpt regexp ".*" "cassie@soopy.moe"
            }
            deliver_to &local_mailboxes
        }

        default_destination {
          reject 550 5.1.1 "User doesn't exist"
        }
      }

      smtp tcp://0.0.0.0:25 {
        limits {
          # Up to 20 msgs/sec across max. 10 SMTP connections
          all rate 20 1s
          all concurrency 10
        }

        # checks
        dmarc yes
        check {
          require_mx_record
          dkim
          spf
        }

        source $(local_domains) {
          reject 501 5.1.8 "Use internal submission port for outgoing SMTP"
        }
        default_source {
          destination postmaster $(local_domains) {
            deliver_to &local_routing
          }
          default_destination {
            reject 550 5.1.1 "User doesn't exist"
          }
        }
      }

      # enable port 465 implicit tls and disable starttls
      submission tls://0.0.0.0:465 {
        limits {
          all rate 50 1s
        }
        auth &local_authdb
        source $(local_domains) {
          check {
              authorize_sender {
                  prepare_email &local_rewrites
                  user_to_email identity
              }
          }
          destination postmaster $(local_domains) {
              deliver_to &local_routing
          }
          default_destination {
              modify {
                  dkim $(primary_domain) $(local_domains) default
              }
              deliver_to &remote_queue
          }
        }
        default_source {
          reject 501 5.1.8 "Non-local sender domain"
        }
      }

      target.remote outbound_delivery {
        limits {
          destination rate 20 1s
          destination concurrency 10
        }
        mx_auth {
          dane
          mtasts {
            cache fs
            fs_dir mtasts_cache/
          }
          local_policy {
            min_tls_level encrypted
            min_mx_level none
          }
        }
      }

      target.queue remote_queue {
        target &outbound_delivery
        autogenerated_msg_domain $(primary_domain)
        bounce {
          destination postmaster $(local_domains) {
            deliver_to &local_routing
          }
          default_destination {
              reject 550 5.0.0 "Refusing to send DSNs to non-local addresses"
          }
        }
      }

      # implicit tls port 993 imap
      imap tls://0.0.0.0:993 {
        auth &local_authdb
        storage &local_mailboxes
      }
    '';
  };

  networking.firewall.allowedTCPPorts = [
    25 # smtp
    465 # submissions
    993 # imaps
  ];
}
