python_executable := if os() == "android" { "python3" } else { "nix develop ..# -c python3" }

list:
  just -l

# grab a new nitter guest account and save it
nitter-token:
  {{python_executable}} nitter-guest-account.py tokens.json
