synapse_comment_unencrypted: See https://github.com/Mic92/sops-nix/issues/120 for synapse.yaml quirks
synapse.yaml: ENC[AES256_GCM,data:ptKtwfXdbLlO6gSoQ56Y8SVA8jzrd4ePaxykBHQFpxPo6Rb6WxNwYX2TulrGWEj2OiCNwtJ3zOAwxcIIxKn+aP6iPnE4jJ2RlpcJHbm/woBpaYS1GtoxrKDeNcSg+WfqYC+XXNKNSh8tu1HUSaHY50vsTIVIXqPS0CA9i4cLPoNsiG4dDse7wv7U3yEdwTTIDfy/N4BKZKXxe02y+u2RfOEZTE67vnZI/AkuEbOSywezD2Eg+nut4/MJmeMylbDa5CGBJB8RBFdMxsXWG7QNi9MkYWU4eLAzA47YKgK6YnNxugcW3AbB6JQPPt1H8aFGhtWBjm+/Iq76dfd37eGFNauC1n/dkdZk1XvhSSK2vcjrk9VQPsLX9/tWWaGYCHiVBMcGqCJagXWW8LBN1x0hQUxgUTUAuBp349SF+l7KvuKpB08YrcTZh5lerHHEGrPQuhN1rlbEdxPwbJbJYD6633pSwVLMTVsDHM/fPyAGlv6alVCDa/VzgsvtVzN7w29igiW/FOpN7qeHzJkLNZKN9X9tRJMnrlijqMCrYfQfh4b6lQKRcjee8Bp1R8u/dvkbKfNyTU9y0Aqyn/Ixnuj8/Jq2jUnf+yIgfEBm5b0mO+UdhWuVw7IcORhrmwHpbuzaBmsaXXFhkZ9oqLiSRAtSUWjefV+Fu/OnV5/fOf+/sRChWjPLPH/jWPcDuQuec5JlrN7J1kjkkolNs+d8dITnKF5LQ8pW12OkWOM8ZsZHlag5bI2B9JSX2dMhI2pCbWH2g58mC4AaedXfgNMeGZdX1SQmy8TRyaeit2krgJiUuKoiNzjmLgQxC5Z2Ial2Z4SryI2h/OPOczXhT/4B+wWq3p2+/e+1si4+ORCo9w9tAYoo8wt7EFRaOpjZNv/QiphEkPjOu7+BOvY5AeIpH7lvY37N6DLdVWWDTn9Q6A7KhW9wR6gCxM6vd2HTCpJIWFgqLsV36NKPnqIC5mjRrWz/PGPYtw6/wXl6,iv:fvaZQ66VKU+uzvn5AwTIFgzz+F2kJ8/QR2AfmynRfGU=,tag:EhWIjKg0VRVCi4JjuYisLg==,type:str]
matrix-signing-key: ENC[AES256_GCM,data:B0HOWAeMDxI0pGmAHAfbF0cxumJQtcdkFhFnDG2MVP1EUps0geld023i7v08dMOvC6B6tRV9c1ddcw==,iv:abvwkrNe324QCbWLwiPY0UwqezS0wbyk2Fvi0vs3SI0=,tag:n+K5bx/+A2yYWv1nQJA6lg==,type:str]
matrix-sliding-sync:
    secret: ENC[AES256_GCM,data:LNHjqs9rOQzoBdiADGryiYumgu1f7rMXm0fWhunRzmGnuFtwkGfGqj8Kq0CvuzuOP1mkmB9D08yazmBJCuMOzvd002bBmTub9Whh7dX6kg3UYfNUdzb897qXK6AcR79gcA2LNuCup7v6MVh2oeEcWrnUURKBHBcBHxq1KLBvgqRiFjVmLToJ2oa/1VV6nmV7QBeqTkPb+RVBAmu77bLAQokhloDNwbSdyADGrojv9cmSsO3gYAnLz8XHkLpUMET/e7yhpc244QsoMqVvLLqTywKhS613Oqs3BjRDpjB84qUhEEHM/z9LRmdaBqsmrEc3FOOlPJAUALq4Yuq16fsoAQ==,iv:JR9Hz+rmfGeJ+JfDugkI7bzh3wb/o/5CdrzKPXfVTL8=,tag:qr5wiLXXySAJOXywbomwqQ==,type:str]
    db_pass: ENC[AES256_GCM,data:JDhfxIwtjcXeL0WQlMa8SdgSdbRlh4MftnSMX315MHlVyOR42DBLLvdTwgYc9TVrYNdswTcOjQpPR0aglwzPSy8QfnaA/CpeyGKH1dOdv+jfWzipmyvZuw==,iv:fKdDDkfGhzCeSB/wBcz9YJwJ7pF7hYP8chAJ04GZRDk=,tag:+9NOxwTygU2/lEzchyMlQw==,type:str]
akkoma:
    dist:
        cookie: ENC[AES256_GCM,data:0y2/cygtQbuKbUmNmClPwz/QBhSpez3k6T8/xeD0Lvevx21uGYJ78gC+Vs3cZMSFmrqldBUnTS/OeacP9rK8Zw==,iv:V8+MpX/IEc57zEfhNGX5f+eMyipraaXDKPDNDOy0Ieo=,tag:fyLDMGNg4tS5Cw9y1h54xQ==,type:str]
    endpoint:
        secret_base: ENC[AES256_GCM,data:YglaQ5/Ur+D7/jjJJZMqrhe+d8FUQEPpw2+nAhz9E7d/qLb76ysNJUrPvUOT+Erb3WYDbWhBzTGifWwS7ciXcg==,iv:/x0ydo2gOPrhIZI7at877bzfFgMpraauozfLq95aHCk=,tag:cVWZLAKuySLq0GaLgwh6PQ==,type:str]
        salt: ENC[AES256_GCM,data:CJFhyxA7dB4=,iv:aSun7ABJdbDQrFcrGQMM9H1/7d5lJqeMwO08gUYrD2A=,tag:v9FBKRSkz1ilBQqaqetnRQ==,type:str]
        live_view:
            salt: ENC[AES256_GCM,data:w2A4qbgJumo=,iv:ZvWKutuMTOm2X8w8a0fOTq+ldrXemayIUY2PUcurY80=,tag:RS41Mkc4KsHvUhCp71jSwA==,type:str]
    joken_default_signer: ENC[AES256_GCM,data:PVnA8E//OpZzs2I0bSJhocTLwK6wxg01x5sgUR69iuPEQzV337m0dbf4R3s9FxftFo02uVEuluwJFro6fVeU8A==,iv:Yk1f/fzzbruW64mvTTeiyTlbrOO/G47CKKfr9BLtQ5g=,tag:lT9azG71QJrCIwTlGacxPg==,type:str]
    search:
        meili:
            host_unencrypted: https://megumin.soopy.moe/
            key: ENC[AES256_GCM,data:g+fMrD3ztCvD91WjYr/PThhMOF5J2UyjcwYuw735IfR/eLmKmXsZSVYYaSybvAH9vxZN0yIy0vRLsgbwi5oyHw==,iv:t0kQUCmjhFw8Z2CTmYOPUNFvyiYfsXETU8GSxhRR5KE=,tag:SCGLYMbyAD6C/437ZLr+Uw==,type:str]
    vapid:
        pub: ENC[AES256_GCM,data:3b19eSoOFNJdGebkn60kADlmDniY5+I1NLfVgzO8OUeLvxIVK1oe1YqVAa5EoeFToak4oBldIyOT9/Rt4lvtvPW4Z6jz8CWg3hlpPFfIotZH7zNCuDY2,iv:154BP5EmBqnKyf9BND2laKV3caVxa34MCRzrsg6/dik=,tag:gK88AQUdpuRQhyoJ8YY/Vw==,type:str]
        key: ENC[AES256_GCM,data:Z6yNLNoaLEowECo3fN6ZPf8T6GO6+0X0ZIFPwPr1FBeLwGLmbJ1rVtwU/g==,iv:yQLu5CFl73GCojMBa2II6OhLrNNinsiVG1aPOAx+HtM=,tag:FQbJy/kanYD0WPo6G5Cg4w==,type:str]
    postgres:
        hostname: ENC[AES256_GCM,data:uQCTiF2C+yXZ,iv:GM2SH4Gkvt8tLG8AYIKxfHTZvB1sT+hgIoqkiViH6Es=,tag:YWhIFAX4QcqQjuG20XTJLw==,type:str]
        username: ENC[AES256_GCM,data:SXEYmUNZ,iv:OQ6zNmDn0uqKqNKEqOHWY6VBuT/4/CHog7b0Pf0TAPM=,tag:C9XIIpHdXIV/bCBEcNW16g==,type:str]
        password: ENC[AES256_GCM,data:87+L3UAScZYjaYI4ASZ5z0WLmhRh3PbqIcX4nW8yndp2Uq6RB3KEp8LGBCxIaEpVXUB/kO/kbmeqrVlPTdk8DA==,iv:UFe/3H/AfTgSlJikHqE1IED3zINjDuOs5niXpGWXGYE=,tag:OOJcVbO6Zr4EpP5VqsJ5Hw==,type:str]
    smtp:
        username: ENC[AES256_GCM,data:f05knqDJRCR8XPBfv4nIdQ==,iv:wBXWtRYawOkjumsvTPcKfvL95CCB+RbsEyJv0YUG3WA=,tag:tOLQhRS1J+3Sps9a5jpgNA==,type:str]
        password: ENC[AES256_GCM,data:wy1NPBjCtjpL4mrlQJXjraEzx7csDurt5ZLStYH41HAWVOAQiXFqPYo1J+hOHAGp7fYEoyJs9N1rnliIemOgnA==,iv:ds8Bg9JSJdNHUXh0FvD5a4pquyRnIXowcsJcVV1TyB4=,tag:W1ZRJnhpxJML45sxX+MmDQ==,type:str]
        relay: ENC[AES256_GCM,data:Pyks8YtwzULSY7hJdYQ=,iv:omnyn+Xa/cjqK+9l5bI573aR2p7UsUvqGX5ZQGf3CD0=,tag:wIdabPMJdAtPYHYip0M2fg==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:3oWW4EG4pSfoshQrMe51Z9pjLjBzm+u756GGyH3ylqqIvKFFbgWNOefcE63epsGClpLH+ZI9Jgvk7kcEcp7tl3BaY//AWkPVAkACcnLHe/61mAWm+BLI8nMTAc02dCUkXQ+kJiua8/PnUD0/quBOmgruKqgPJw==,iv:BbBjgsHh1pl904COKCMAh41uI7UH9kHcyy79zKYcM8E=,tag:gUpSOibTJSB0rQkhIrmJOA==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:TwPkter8oixpxxPD7qg=,iv:Jb7OeSnZ/+t9GU22nrPVQZJiybKInDQ6ffcg7jdkLGo=,tag:tzfYBrdkraiVLpSxybHJ+A==,type:str]
        security: ENC[AES256_GCM,data:Z6PSLa75MA0=,iv:CTir/KO8cTDK0eDpa6dugYH694DLDcKG+ygRceaI7g0=,tag:66p7+NTMonCnn2F1Uffu8w==,type:str]
        port: ENC[AES256_GCM,data:aqfA,iv:g5aIKLKIB5++TI9se3a8DAm1TXBtFpraW7ZkuAUMT0Q=,tag:T/cY5TOVLtAlA1kT9jvulg==,type:str]
        username: ENC[AES256_GCM,data:wvD1KGwwzxCJsea593A/+wLU7ggRT2wq,iv:5J73NP2SZQtvt3Uh3SemkEVLiQoPp2TpWGcgDbvVA7s=,tag:u1ui879hGyMXSE2C0ge2eA==,type:str]
        password: ENC[AES256_GCM,data:U2FxtVo6CbFwEHGkogjfNKLLLoUJbC+JGv5Zf0iVhvvttVw1nY05XpKuGL0m00FYV6wpszeWBuV0P/lmuZKXUd+C8Qp/OW2BQqrPjWrmfd5FgBtJ1fLuGg==,iv:M47gM1ZU+TgldQqP/PfogBFChDhyK5xckqtVRbAWzxQ=,tag:4KUzKuqhbhMGZ/TND8Nm0w==,type:str]
    database:
        username: ENC[AES256_GCM,data:UacYwys7J1YgXL0=,iv:qPVLau+h4t1SiD5PqwoHjSuCwG/ftH1x+eLhpN5g+nM=,tag:JmSCSfy18EIiggv2q/Z+fw==,type:str]
        password: ENC[AES256_GCM,data:jOC1XCUMNB2qIYPfMsxs7bTodhp2JTrkTKqp4gKrmBtq2Qi0yAq+KG87CM8Uus1dnDgX9OizVUMcw5qaBM8QO4KniKOISLa5Xel3+0A2ASSXAQyFqUzPJ3IlUhrxFXKNktOrA7ZrrfXPgxsbG5rjqWyNS1hSclxeYuSNuqWu9sE=,iv:yekf7PRi/bwpJ/bLrfSz8nxubJxs1ckJNBxfslnfvl4=,tag:jh1+eC91e+vI2C8cWP3rPg==,type:str]
    yubico:
        id: ENC[AES256_GCM,data:fHvJ4n0=,iv:I6YWEq8+lpSvVicgnTnXyobK/dLi/hwyYOGUu52q1hU=,tag:Bu63ccpi/N2A1qRpI0AGiQ==,type:str]
        secret: ENC[AES256_GCM,data:v/xFkCYH34+ehidpSkxyrp9m6Ca51V5ATgd6+Q==,iv:ovEwbuFtdnnYnr0qpmWrXM3AqmoUsPwe8nIW/4Mkn34=,tag:94eVzOvHE6jUXsFoDLVfgA==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:zYzzH5q06NsCAZ4EZKGIXdi0V6FevbrvhAeWhI5isjZrdBSw,iv:kakIcF8ZUsdfeH65FfzsF0Vk5GotrDMmzWQF4IQRxhE=,tag:8BG5pWU0gVQhvNcl59XKcA==,type:str]
        installation_key: ENC[AES256_GCM,data:2fIIpF7OtBcDRORge/pgE7zm1Vw=,iv:1jk1+5V278evEl/gU/aocOMgXUzAfbFVECG/sQC0s4k=,tag:uzkJ+a/WH3CPmvQAMtV8/Q==,type:str]
forgejo:
    database:
        pass: ENC[AES256_GCM,data:c5uOH47etqRK8zHHzaPQleSg9vF5zP47sjda7hSNoaHGNjknxq1c17Ua/b09H+hOIzV2CejIs+PS0qirvP5mMXpeoeZCSRJZt1zLAT3gqgil0PPRZUIUtw==,iv:OTogoxwmalk4CiUlQstlER0JVN1YuVhWJgrhGJPYiuw=,tag:420o0iZQqLPJm3wmbo5TUw==,type:str]
    turnstile:
        secret: ENC[AES256_GCM,data:o2umdr0kmfhiYxpkrFUpThvGAUEZuR16BwQxpkpWzLjVFEA=,iv:yMnxn15p5HYZSMOCBT30i3gpClyW/2fx8Ytx9sQKLSc=,tag:g7rbvxkiQGIzQbZ4pVfWAA==,type:str]
        sitekey: ENC[AES256_GCM,data:9PXEt/srZRlMo/nzDAxd1rKv4qYRwxXl,iv:VaWMEu1QIh4LeauflFjJJgblLyOFkTpb4Db9wip6uY8=,tag:djB7Z6f0SgTgscMDJDfgtg==,type:str]
    mailing:
        host: ENC[AES256_GCM,data:8wLOPyHkbqnq9yYYiG0=,iv:7ksEKqX8nXS4A6M1JH3+FPWoxAP6naB2huwJ7Yc816k=,tag:tQhqaMuxvhFcFphz+dDxDQ==,type:str]
        protocol: ENC[AES256_GCM,data:hevnDq4=,iv:5ryKSzDHl1Vo375IqCnRr2TrcjJCvQgkdHHuIJ0Tk6w=,tag:yF8JvM364PfGBcr0vXeUJA==,type:str]
        from: ENC[AES256_GCM,data:I7/3SEjcGHUpXGA0LC+/KC4YylcZehJm7GewGoIQfpeY7oyB,iv:keQtnPpEdZpoHpWnIE/Dy67QTAWBhE1H1IGbtFOJMtY=,tag:khTGg02fqYyyzBN+/9JnOQ==,type:str]
        user: ENC[AES256_GCM,data:esyIsCCubMlyK2TDzkwLQhRUOOe3xiNk,iv://IECba3A/MlXv4q0eCI1DXZFF/YxF/U1AHhCrGNd2s=,tag:/QusQI1j57YBAXFpsRcEHQ==,type:str]
        pass: ENC[AES256_GCM,data:ODvRpmp6koDIWXVkWiM/hcVDqnviUul6e9NxXAsnq8HXRcD56tawzBFcoAR1KHdSQrElvYItwI7FwjXPjVJBGZl0XqAspML1wWRJmNE9bIIR3X7ILmfxwA==,iv:/4e5+aGW/HksRYXXrpbYZgCCWPYD0n2plb/+tNwu9hM=,tag:1NtMYvMhaYvO7nrtk6bSzw==,type:str]
lego:
    cf_token: ENC[AES256_GCM,data:cSL+9sY2uKgnn+s4IJfmhl/61B1tVDdS436rdTvG5hPbTNPp44ck3A==,iv:utJunj8wewHFdOaD+EOgpN5/RpXyCdsl5Lr6kBbXsvw=,tag:b7W/diIG8cOoRiJEFFaoqg==,type:str]
grafana:
    oauth2:
        github:
            cid: ENC[AES256_GCM,data:K7aEm404UE0oaXXtoYwzSpxP01w=,iv:K/WKrdiq9mXaFV33zYQYeYgia/54t6/qCseVGykW/yg=,tag:ro2WzD3U+agcVCh6Jhlv9Q==,type:str]
            cse: ENC[AES256_GCM,data:HIzvtsL8qXg/B9/PBlCdB09vBuf+AJSlyAyIxE6FDnrPoT6LAkebww==,iv:iNbKhyUIuKtBUVHXdR36KWCueMjQuKIErl8P7intFX8=,tag:kAbJhnV7x0qOr1g8asW2xQ==,type:str]
        gateway:
            cid: ENC[AES256_GCM,data:JXFhTds=,iv:F8A+gIGPUjziBTuBnhVS9kygzZYjnwFayL6Mx7LBwe4=,tag:kRNiJZGzCoVAkCznzWR57w==,type:str]
            cse: ENC[AES256_GCM,data:GN0hwXm1App5dIGV41M7iTnNSXkOZfr1kOI5ANSrnoE=,iv:1InLcW58sbz9wfp9VnONsqE+iDrhCWhlBBkr13KfN1s=,tag:yUj9+vSCLPGqVbKEnW1ncg==,type:str]
vmetrics:
    agent:
        akkoma: ENC[AES256_GCM,data:Lby6OX/4S5pBo154OUDy7wfyWlO4rjKjaYeqtq4l/+b/D2nMqgfB2JaHpg==,iv:M5NrIERoQJohFqCRgP3TcwW0OspHMIbZR9x8G7jvI8c=,tag:7efCgy2Xg0ag+8L4tCLf+Q==,type:str]
    auth:
        hosts:
            #ENC[AES256_GCM,data:VvxJN5pePviHlO35oeGs3ZbJMiNiXwfqLNmVRFNw1GflslI/uR0f21zC0Sp0G+k=,iv:IeAZya/9R5fF4iqmmMzZ28J8hj9yYBPXnljsCVhN73U=,tag:gYX7C4jXug6xfdmGNpa08A==,type:comment]
            mail: ENC[AES256_GCM,data:cKCrkF3jcVdZcNOjh9HW+aNGkA3NmOheilEoW/4gNy6j6psIsXLI/CquE3C44QVuTSQysksHwCy1Dd4V/9clHrSs/CB2/2T84daMAIb3xR3oy7E70XDnMoQMFZ99T8MGzWd88aEXfC2AJyaM0gth4Fl4lZFFH9i/SOAHn4plrxGHuGZBk1ynCKrSJGc2fZx1CHtK0mLW/Dv754GqUbGyYxdS8zlPbHhJuGR6Kg==,iv:Tm93jST/E4PkSlafzMWBfdOZj7g4J0dzBSeLrS8o4Ow=,tag:pwA55Lrg/Qmow1uwsxo+hw==,type:str]
            bocchi: ENC[AES256_GCM,data:dlwQQoo7SA64zePHtfDfK5KXEZvwhQv00fGlmuRiVnCAioUXEPjuvfYRJGjTg5ypoGefdGo1ErLayRHwfDLnjh151e3caNQzGqSm4mxbvrLBvC/KPoRpQsRcK+WRCH6AU2simy4Fwg5bCYUkr3nUS4b0QUjLxT/0zSn42f1P0TLZd6Yfnn/mzkXZ6H1RE9mZDvN3rCgxB18EC3v1Ue+55a6JxO4mQvXdOTuiGQ==,iv:vhfxElYtouDM44cRzZwuZvJMncRN0Wt5uSfcSEFAuoM=,tag:hUVyBTcxTn9NdJYUA917EA==,type:str]
            satori: ENC[AES256_GCM,data:hq1xNIkAndxAMR751RQxjK+GihwjDN3p96krIWcOet1uAfL8fEu7bVsnCq2pHfaX7kxvc9RDl38rcKe/zM+fzhHJ3W3l8EZvgHaJzQladWBOjVSSkjOwLEiWwg0A/XRGcVh0ryzMClXRiE1kmWo+qQPq8o1ji8UjfmNgMQtTgUWzn6SiyO53qd72r7Tt2nWayouiK8P5h5TjWXbKvechkdLpF4U50HT7YW2KaQ==,iv:6NhlTlShIUrtl5844NGWq5903liy7pbbsaa9z/OBxSQ=,tag:yCtn4HAU6qPOXZKQVlbwEQ==,type:str]
            renko: ENC[AES256_GCM,data:3OQWK6kKa6MGShQm3LwYMR81jNJrvx1EWVXv/o9MgVIck23cHsXOJwaPMrfChPxg/0tk31ser4eecxhmIBHMGRR+A9a9nHOyCvVbbrQmiKbPHE1NkxqfINCCwVD2GArYZnHfGhQQbtzXs2+lsicXh8ImJ9u0ZcD5fCu50A7CjT9KoSfC3HMi1EJEFwfOscJObmVdDYIdYDB+S2uCPDiHBQnDFrHrlKE0FtKIrA==,iv:WA8CsytshgRN0LXWyxm6pHQ0N8vwDfvh7VNlemrja8o=,tag:r45mvTjMnToigC1c9uWpKQ==,type:str]
            kita: ENC[AES256_GCM,data:yfiEct04cCBYcvJ2ZqB+lrZL8k8AN8j8ZUPV0/84C61qxNSm0VyE/vJFD3HVrRSK5AM1+zg37VKf/tCwwxpwgPRtcwhwddlZDwtmMaihN74xEdLCz7Fyewv7orcbEXhjz6Xfd5WjiAzIHWmq3GpVD9PP8VeTG5ajfElKzOJfEg/G4bHn9G9K+aiI9wcGOWocBDjCSr5Oq32imGZHPxY5VLcsxZtFf8KbWgfPUg==,iv:t1Rt7h6ExtMy5pltAJ4YBbbwoPqRyvr0gkWJXAnwvkQ=,tag:iBK4fuOoq2vnvveEc5/g0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSmgvQU1FeGRNZ3JPZ3dy
            Z2ZpK01EMUNhVEE2SWw1MHRIU2c2Z1VVZ1RBCm85eFFlamptVzFRRHdWbCtJOHdI
            MTJrVCtEdElkb3VVZFFKakZyTDdZSW8KLS0tIGtzS0ZDaFVvUXlEYUl3ZEhwWXov
            Qm9yck8zeVZUdnRDRmxLLzJoQVZhMGMKsCQrC0a6ktW0BVE1CJ4rN7s4uR7H0k8R
            6RVqrCGVEXweootYkZJqi8/8B4y4SQG6+qXwRBjupuU2WjSfm/LR/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBod0t6c2tYTnFJWU0ycnRE
            Z0NEbWt0c3pQdWh5Zmo0SEhGcUFjVGw4c25NCjN5MWFBREMwZjdCWTdTZU80WFJO
            MDdwcTROd3hCUWtPdTl5NnF1QlZOak0KLS0tIGg5aWdIUXRrVURtS1VQdWliZnFQ
            NkhEbVBJVzFBa0FHemxjVXgzU1FqcVEK6LWMa6sBckIczucLZdIciBy/CIUi+lAX
            D94f+ZFG4TUar/UFxKoHirE8F829ARBY0BYs0m0N55ZY6/96LCxoTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18h7hya5terghrwawgpny28swlat2nqkdrfd4clk0svujqlz9xfusd3zeqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweVkzcjZKVWJtRjFrcyta
            dERiRnpCd3hPb2duNkhKbUwvOTZxdUdlTlU0ClArQm94TXMzUkp5RUJmeHdSNFEw
            aDgxRmdOZ3FDVmlZVFpEOEtFNlVESFUKLS0tIDE4NDRiUGh3ajVHdHFhckd6ZGYw
            UEN2MmIxbWs0VlFOdmwwOTFtaFZtc00K6wHAu64TfN4ouSNa7Nv8ZPWIza5W9av+
            E9iU5e+d6g2wX6sVie9BEo/rdAAO5kKQyB5tKs323xRKAM05u9Treg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T08:08:01Z"
    mac: ENC[AES256_GCM,data:rGzwcdapQrP4m+ObhYYYBUnb0NHvY5YOJq90JT4rhtz1MRkUE8ipaJynbvaFBeSpHsn7o+8iRM6AHUMMdT/INPVzYbn78z9CFKetVHFZ3IRsUhk6h5YP+5CJyBGS2yh/8gIKLK7H6AUyEABAINXHxhckPsRdZSTdGM3iAbiWgiQ=,iv:Pj9Tylnw6yOH46+pF/Lu8XUIgqjnHExB6TPqy3HJqBU=,tag:4Mj37fu1EtQ2odFwQ5QDnA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
