synapse_comment_unencrypted: See https://github.com/Mic92/sops-nix/issues/120 for synapse.yaml quirks
synapse.yaml: ENC[AES256_GCM,data:fzgZwQM1F/H5U4buPWFJIV1ZOUoHAHjF700sO79/3LnRQ2rOGnWUoFhCA/pUPZrLgy4XTtzAgkrYg3mxf2YKVtE7601bwSxr8oaCtF7aYdd8Fs7+HWuFdv9OiWr8m2K4hskw8ViSRt/cKggjxUnaeU1vOtlhyZP6e+wT6UA/KGGxf4kq8gDhZKSmSyOAL7Z59bmweUcUf+QsFx/mDXiGJIhsNekSiJ9daFy56JHRKQxC/ueL6/zJW48GTTjubwTpnHPdUUDX1kGJqAwXcuIfLKb4lssgkOoX0buQGPiDn3JNaL1MOlwlILYGDpccdPApm4c6pdgEjzFaLW3/YA7DVxfytR/Y5n6PRpRw0HaxqWKMp9859pIwKS+wJLKVAhtvnksJ3Iv9qvDWwbrcJdqqqUqdLLC+RT0I+7aF0cyZLxzTjEC9c3tmuelx7MoNM/d6AehN48mAUXzKtkIXfGOXf/lXU4+L+tF+A/ZrcUGEEK1nlfe3/lAZ6i/AMVFeLcRlSQWG9qcz2qt4wyv8sPDgJJZ+bGAI5dvCRTZI0XVlWLtYz3DV2taXIVKcUmM21K6TjYjAc9Qdvenekfumv4El9Suujukl+kE7m3l1zmticIvkd2RPfHnwmkblSqjaReJdO7RV5/MpaZTTDALpXEVAdWPTNaBq2zygnuKjZsLSVgV9T0XkLWNTYQy26MJmfb25Wj+IPSJ4W3jP80cx2DncLbGO35+7RmvBkAeKKo2fHPkueCbjdJCdgeEBwjsO3gKiBuQzOuxZvwsaeufnImkT0VOPxmMm8twa5TprbL5L15x/eiMpaIa+C33rQX5qOYtaU1BKIrcjykmr86G6DkozJpRNEZzSXGUP4s7y+RypMHziV8P8/LIVfPaWSCxrmU6tksM9prUfo8mgeyhJ5ASivTi6iWSpXVagU1ZvumJLT8T9YyGispjxT3hg9jOkYN5DeJNEiSQ9j1hRd9jsY80k5Gz3Bb/Uj7dt,iv:fvaZQ66VKU+uzvn5AwTIFgzz+F2kJ8/QR2AfmynRfGU=,tag:LmGb0JOVim198yyhxd+qHw==,type:str]
matrix-signing-key: ENC[AES256_GCM,data:ebkluxNqbrYtHpZpfjRP4WAXfqYwiHRbgfV3EDpUgankxGhUj4sQKXN63inXCfThqOw7nyId8gfcDA==,iv:abvwkrNe324QCbWLwiPY0UwqezS0wbyk2Fvi0vs3SI0=,tag:4Z4UPVUu2oC6smVlS+BQtg==,type:str]
matrix-sliding-sync:
    secret: ENC[AES256_GCM,data:5OeQ4Fr4ZiHPbi67Vmjj2jWpwEPMov7DgQ8y397+wvBXuKa7VemN3HHNOALARs4Joty5C5x+OwsL6q+XBjtvKEuEf7v4pfK08JtkAp5TN4IeJv3Hhm5849UO3D2ecK3+F/2kUiP9WbYvt6Z0ZUr5sexw6XDi4s4SP+CAbudahEEzJZl1sfioCLvlPZA1B+FYMDx10cw7Q2kcw3voScSN5SRc4qsZmKm2I48JY3i7khmYnJubYtO1vGFZwCt3vdpYpqhLnyBJxdSsK2h6PQYOnSNXXQrhXF+cqzLdVSbigTTpoyzUBC99DQ1uUtPdkqA5VVLKAXGhoTlf5TQnnh9aPw==,iv:JR9Hz+rmfGeJ+JfDugkI7bzh3wb/o/5CdrzKPXfVTL8=,tag:NAON3B8hC439eFqbB7A94w==,type:str]
    db_pass: ENC[AES256_GCM,data:ooLmk1fQMbvK++SvBJK0vIhz4p/uvYa+On/3aMMlheW16sOXhK/cz+56KhgG8GQeckCSoSe3dnd7JJAkHJ+RJcMtAxuTTxfb5x+L/813MbrxpA2L+z43WQ==,iv:fKdDDkfGhzCeSB/wBcz9YJwJ7pF7hYP8chAJ04GZRDk=,tag:R7W7P8GY8KiWcIKtzZYcUg==,type:str]
akkoma:
    dist:
        cookie: ENC[AES256_GCM,data:kEbWW4Fng9COPSdRILTmSrltYEPPONYQiF9zzVXhCvyOnvfXz9qz//Qfh4KIy57LhwiFiG35Gm7S2mUnb51F8w==,iv:V8+MpX/IEc57zEfhNGX5f+eMyipraaXDKPDNDOy0Ieo=,tag:hUJZ1lbxnDBpSV4Fkf2UGw==,type:str]
    endpoint:
        secret_base: ENC[AES256_GCM,data:maOod+fs33+wZgZHxwFeuBBG5iQIpWu9CAJT/lIXeqUCpPIxPv8v/llonIRAnIw/1Pi8MyLYQo3UOASamHjz/Q==,iv:/x0ydo2gOPrhIZI7at877bzfFgMpraauozfLq95aHCk=,tag:y+vS5BjK0pN65T3FA/sKcw==,type:str]
        salt: ENC[AES256_GCM,data:6RNwGSvyq9s=,iv:aSun7ABJdbDQrFcrGQMM9H1/7d5lJqeMwO08gUYrD2A=,tag:Yo1ymCxAWBYT2eNq2g5FNA==,type:str]
        live_view:
            salt: ENC[AES256_GCM,data:CDfT+dReMLo=,iv:ZvWKutuMTOm2X8w8a0fOTq+ldrXemayIUY2PUcurY80=,tag:my1Ypw6/RdrGpdzraNYrZg==,type:str]
    joken_default_signer: ENC[AES256_GCM,data:4vxEDyx0qFSCDscA3pMtpd9dMm6TCrpvmHYXExGJ+f+/NjRbsOBoEs9YjqHfTvHzrYLMEbMcPtlsIQ57lxYuDw==,iv:Yk1f/fzzbruW64mvTTeiyTlbrOO/G47CKKfr9BLtQ5g=,tag:faBGvnSVphUq5vRAV9N8TQ==,type:str]
    search:
        meili:
            host_unencrypted: https://megumin.soopy.moe/
            key: ENC[AES256_GCM,data:csz3lmLhIe2t/EyTbqD7udSma9B5Jym1/xT2a0DtQiRL6VO2GjXEOlPzQ2Qj/cEUvYOepybRyUW/T6ZW6sctZw==,iv:t0kQUCmjhFw8Z2CTmYOPUNFvyiYfsXETU8GSxhRR5KE=,tag:AA6pAV1pljXlTJHesP4Bvg==,type:str]
    vapid:
        pub: ENC[AES256_GCM,data:1XgszvQ4KOSfR/JC4e4gHbDzPJrSBWzBISR/U2dVg1/EKuj2sxILg4qEFpJYaw3XrPZ6hQdkIKonJ4VF4AfQqJ2nEQ6ehx0LVXQ/5wv0xgPTzuAj1LzD,iv:154BP5EmBqnKyf9BND2laKV3caVxa34MCRzrsg6/dik=,tag:pCVQS99DR+FxkRGNuLW0aw==,type:str]
        key: ENC[AES256_GCM,data:ei4DYJlbQWkTIvw2ijzODWLgW2fjEqzBbvwkVDkImPp7daqxIS1mnwGFjQ==,iv:yQLu5CFl73GCojMBa2II6OhLrNNinsiVG1aPOAx+HtM=,tag:8wDjsRNUWIxLSWZ/M1fBSw==,type:str]
    postgres:
        hostname: ENC[AES256_GCM,data:q7FRhR/OZG5/,iv:GM2SH4Gkvt8tLG8AYIKxfHTZvB1sT+hgIoqkiViH6Es=,tag:VYd24JrtZtz98hLJlwGvcQ==,type:str]
        username: ENC[AES256_GCM,data:gO5VweHD,iv:OQ6zNmDn0uqKqNKEqOHWY6VBuT/4/CHog7b0Pf0TAPM=,tag:r78Y4H73S5PP24/5HMsiDw==,type:str]
        password: ENC[AES256_GCM,data:phQhGJI+xYac353+EAXBEdT2Z8YBXlxU+XHFzWln/q/dilGIWtJLeaV8aXCkKrf31cL05dhgunwUcIVHz2anCQ==,iv:UFe/3H/AfTgSlJikHqE1IED3zINjDuOs5niXpGWXGYE=,tag:ri5CFvVJYjs1Ao16dfbAxA==,type:str]
    smtp:
        username: ENC[AES256_GCM,data:X73+4io7mJP2AEFe96HIgg==,iv:wBXWtRYawOkjumsvTPcKfvL95CCB+RbsEyJv0YUG3WA=,tag:sWZHgGswtaNnu152FTQGzg==,type:str]
        password: ENC[AES256_GCM,data:PZs01FVpMAqABl5v/rrSOEnbQgsRJYNt0YOClAV9XE2rHOboQXw9OzeFDcnIxBEKKCsP/hoWQhtDX6J5L7vd8g==,iv:ds8Bg9JSJdNHUXh0FvD5a4pquyRnIXowcsJcVV1TyB4=,tag:1Vf/bQebDfFQLx62dSruXQ==,type:str]
        relay: ENC[AES256_GCM,data:qNgTSPiLx40XC50WVCs=,iv:omnyn+Xa/cjqK+9l5bI573aR2p7UsUvqGX5ZQGf3CD0=,tag:KuByyo0uN8lTKT7VYCpkZA==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:CL2zfZDfLRGgzx/7s0jq/YuPRAchlv1aZWHHfORpTmlUSRWV/kifrrUR2OQTwfQ35wmpTEzb110/qF9btOKR+W7GXi+hnnNuHX9EzSqB4RDIotc0CZi9kGJksQHNRSuKESmHp8zgu7R3F43C7ZkYhX7V0jg1Wg==,iv:BbBjgsHh1pl904COKCMAh41uI7UH9kHcyy79zKYcM8E=,tag:mXthTAWaZ4J5hWxole3tHQ==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:qJchIC/EX//Zuo8ECzI=,iv:Jb7OeSnZ/+t9GU22nrPVQZJiybKInDQ6ffcg7jdkLGo=,tag:lCya9kYoHPWWyf/UbltTBQ==,type:str]
        security: ENC[AES256_GCM,data:oIG8MdKLpGM=,iv:CTir/KO8cTDK0eDpa6dugYH694DLDcKG+ygRceaI7g0=,tag:fCw6Hsv2RkEUWbMAUJ8uYQ==,type:str]
        port: ENC[AES256_GCM,data:3mEf,iv:g5aIKLKIB5++TI9se3a8DAm1TXBtFpraW7ZkuAUMT0Q=,tag:V4xyCEKikoXgi0JVUQQTng==,type:str]
        username: ENC[AES256_GCM,data:SPq6sDnPjolTjDCMNp+qMXQpLW+QIw0N,iv:5J73NP2SZQtvt3Uh3SemkEVLiQoPp2TpWGcgDbvVA7s=,tag:eN7o2ryCrZ9m16vw6k+fLQ==,type:str]
        password: ENC[AES256_GCM,data:n2y7D//NWYllxdGx2k44Ocyfr2mpZ2rSlVajjB21yEDUQWlNhxTYo1rryL3uGTmybXUDxaeYRch1kSu+kojQQnfvvWUoAoL/ui6oQqvXzn02VcZpjjCMaA==,iv:M47gM1ZU+TgldQqP/PfogBFChDhyK5xckqtVRbAWzxQ=,tag:dzjvixTrVox4JuO6JcqNHA==,type:str]
    database:
        username: ENC[AES256_GCM,data:t8sy7poQkxf4e7Q=,iv:qPVLau+h4t1SiD5PqwoHjSuCwG/ftH1x+eLhpN5g+nM=,tag:nelibGCeCYLC92jA+FxGEg==,type:str]
        password: ENC[AES256_GCM,data:OcuaKmLZiPIsqsoznRLGiLDkJlAmEsWa/nFOwnlKGlX0XuFqI0B0mnsstnvlWCj8g9hKtl3Gg3YmzCMLdCtNYzGLaK+GhcPTV1sRYUK00VyN73EFn9J9GZPmX1oFLmBR+4LuB01k+t6e8vBOaRV6dx1QvqAWvZniQdfQlK9Hvd4=,iv:yekf7PRi/bwpJ/bLrfSz8nxubJxs1ckJNBxfslnfvl4=,tag:hDoOwDbF3qLInc2pZnGfog==,type:str]
    yubico:
        id: ENC[AES256_GCM,data:4NRxmHM=,iv:I6YWEq8+lpSvVicgnTnXyobK/dLi/hwyYOGUu52q1hU=,tag:XnatNLXWFTCQEXICBmub+g==,type:str]
        secret: ENC[AES256_GCM,data:MWvixTPHCjRd9T1z2OmWEtqaY7za29aoAOXvbA==,iv:ovEwbuFtdnnYnr0qpmWrXM3AqmoUsPwe8nIW/4Mkn34=,tag:Su5aRGjsySylunL74KoVkA==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:ZWHBs9+sR2YjvVLOTRg05xQt26P/6nx5xsBLtzpTk6WA5xM2,iv:kakIcF8ZUsdfeH65FfzsF0Vk5GotrDMmzWQF4IQRxhE=,tag:bGeFmX6E/zXWU+TuefRBKg==,type:str]
        installation_key: ENC[AES256_GCM,data:+vl8Zu5t+IIkklWnVR7Nh4YvB8I=,iv:1jk1+5V278evEl/gU/aocOMgXUzAfbFVECG/sQC0s4k=,tag:eaMlE7/1NMwWP1r5PRV42Q==,type:str]
forgejo:
    database:
        pass: ENC[AES256_GCM,data:k9LQRF+5ernoBQgH2omK4McVzi8BH8mg5fb+8FgOxwDrZJUY9XOI6z26r0uT88JlcWVjNfd/nJbYGSpEr0EkNc4Pndj7icR6W2AHnD5DydX9IfjWXCEyKw==,iv:OTogoxwmalk4CiUlQstlER0JVN1YuVhWJgrhGJPYiuw=,tag:Xt0NChSZBaFwwi5EtHdlqw==,type:str]
    turnstile:
        secret: ENC[AES256_GCM,data:CjOZLyKd5F/+ys3aRrXEyPKZFYb7hpgxq0BMJjSaxAnkokE=,iv:yMnxn15p5HYZSMOCBT30i3gpClyW/2fx8Ytx9sQKLSc=,tag:nIz2IlVm1HYbZD9c9z2LPQ==,type:str]
        sitekey: ENC[AES256_GCM,data:k5X+ICmGbJob/BX86T5Hbl5EauF7Nbrn,iv:VaWMEu1QIh4LeauflFjJJgblLyOFkTpb4Db9wip6uY8=,tag:MMQJq0TUTbZhvsqXZMTJHw==,type:str]
    mailing:
        host: ENC[AES256_GCM,data:RW/noDhX6BKlNYkI5vU=,iv:7ksEKqX8nXS4A6M1JH3+FPWoxAP6naB2huwJ7Yc816k=,tag:cNjnSY8I7MJHuvwEAEoi2w==,type:str]
        protocol: ENC[AES256_GCM,data:VhpsW4s=,iv:5ryKSzDHl1Vo375IqCnRr2TrcjJCvQgkdHHuIJ0Tk6w=,tag:6jpP0LLqZ6dJjHdHT1rCsQ==,type:str]
        from: ENC[AES256_GCM,data:5XtV517s/wjDtZ4/h2k5jz5D87U1glZPRvMYbDKmhPyYAwP3,iv:keQtnPpEdZpoHpWnIE/Dy67QTAWBhE1H1IGbtFOJMtY=,tag:8pYbHQCyx15EpKwFGx1UPw==,type:str]
        user: ENC[AES256_GCM,data:wuUW5yTRGvcKcdAUoFH3SjkSNLb7twzD,iv://IECba3A/MlXv4q0eCI1DXZFF/YxF/U1AHhCrGNd2s=,tag:4+0gmiKuiZ0pzGSP4n4pVg==,type:str]
        pass: ENC[AES256_GCM,data:Lsuu0W/bi2RcJ+43K9mO2Bm9NDsinAruZbh63rg9aA06Y+ImaIV37ga0oJxufsYWRUCy0AflSUNr/l91oVRPPEA2AiJmQwMSd92pZ0XD+Da8OgdGtA0eDA==,iv:/4e5+aGW/HksRYXXrpbYZgCCWPYD0n2plb/+tNwu9hM=,tag:eG/JEY/3FiTfDtjZhqf3+w==,type:str]
lego:
    cf_token: ENC[AES256_GCM,data:cdCkYOEJQu/WMf7dnA5yrKuGbCE0HgJ/tlDSPFuOyAxkP7XjzTDpeg==,iv:utJunj8wewHFdOaD+EOgpN5/RpXyCdsl5Lr6kBbXsvw=,tag:beIQ6S/AL4Z6GVhbdd4NTA==,type:str]
grafana:
    oauth2:
        github:
            cid: ENC[AES256_GCM,data:HsSsHNIvjP+pJujakvIg3fw9oY0=,iv:K/WKrdiq9mXaFV33zYQYeYgia/54t6/qCseVGykW/yg=,tag:jP155PpL3umXlhN6qZOORw==,type:str]
            cse: ENC[AES256_GCM,data:DLqRiuI0favGM0bMR3pGJwbLUcFrTXGCVsy3+VagWdbI7ZC5HsPWVA==,iv:iNbKhyUIuKtBUVHXdR36KWCueMjQuKIErl8P7intFX8=,tag:d3aSKTKS9/Lsg+kcvmk3tg==,type:str]
        gateway:
            cid: ENC[AES256_GCM,data:XfmyXhc=,iv:F8A+gIGPUjziBTuBnhVS9kygzZYjnwFayL6Mx7LBwe4=,tag:X7+o6DYkKtiLV4e3bn9h0Q==,type:str]
            cse: ENC[AES256_GCM,data:Dir5z5gU2ve/10ecliL9V0isLgf0gCrmPIknXHkx0NA=,iv:1InLcW58sbz9wfp9VnONsqE+iDrhCWhlBBkr13KfN1s=,tag:rMeCjuTo4hVi2I0NJHIssA==,type:str]
vmetrics:
    agent:
        akkoma: ENC[AES256_GCM,data:vT0OTjk6mLTbwTMj61dlAFKIEfTUo9XiRbfW2oLczX1OOILVYVLNTdUDYw==,iv:M5NrIERoQJohFqCRgP3TcwW0OspHMIbZR9x8G7jvI8c=,tag:fE+zfvQFLcYE0iZQk/XLQQ==,type:str]
    auth:
        hosts:
            #ENC[AES256_GCM,data:icz9NOEGbWZGM/hAKM0jrwl+mhY1fHH5l4clqB3EMgkFRUEwt8yKO3PFlBuVWZ0=,iv:IeAZya/9R5fF4iqmmMzZ28J8hj9yYBPXnljsCVhN73U=,tag:1cS1Zu4j6J0Wl2+2sdxeQQ==,type:comment]
            mail: ENC[AES256_GCM,data:rQ62Yq+jCAoMDizvy+s7g4n+lZBxSe7BxfQ0O4eoo4FgqL6IEqxWZ9f/8xjwRoP/4nHNLPYcbeh2HwC57zFH3Mo9zarBGecU7wM3hzByBj770PyXiO/lF+w7+6nj5z42sOvCuqCVKXz4PYl29lVQF4lbH5faDSmI12D6eKd5SpDwD0Ov7DQsqUifcdfUHQkq9Jl+E/mDsfNdJAlPcIpWyFdGL2Zr4f8W2wGHXw==,iv:Tm93jST/E4PkSlafzMWBfdOZj7g4J0dzBSeLrS8o4Ow=,tag:1yx2K+Mtec3bWs6iphXheQ==,type:str]
            bocchi: ENC[AES256_GCM,data:iIyNhuhp1idRxNDI1iQwDpGHjOp+NTlz/Y1cocU5Fk6ko5PUrvX1HVZVU/+dBGkZc9UAPYTTzVEaglcE/F6EBCe9uN/yeiQhkwSpJOSm6XZVZjGFazDXNpcPYGgf1cLHacO/u3F7zLLwAhpqZo4I04FBz4bFo7O7VBRQqRAwNGp7zHstiVjq7LUFssV64TkTDrmnHRk2StWRZjbgR/nvjiR/PIpxQlumKVIRug==,iv:vhfxElYtouDM44cRzZwuZvJMncRN0Wt5uSfcSEFAuoM=,tag:+o+3CJBRwDwEO29k+2c52Q==,type:str]
            satori: ENC[AES256_GCM,data:3E6ikBGqM62E/XzHjlq3VjfXNNb31wAd2U2SBsPfJAkNiSr8HpaHApTrX0eFT8jAhUrBsw4TJ0BYXFhhSIWLBhehetKvYkr12YUDvVhPZCf2sKXQrNf1sNe3zshoJFkP06jWA5neTMzUz/Ov+BDhCUb9jWASRRy/9MJVDY+mQ+JRTjYSW923+DKzEG4t4wQsbqavm1IY84MGhBxRFG1Bdhr93cg5oZ7YwilEww==,iv:6NhlTlShIUrtl5844NGWq5903liy7pbbsaa9z/OBxSQ=,tag:zitg5PnM0UiUNLR+fXqlNQ==,type:str]
            renko: ENC[AES256_GCM,data:Td8yr8ad8KYFSYhCtlMvY8t4zdiogvw0xs51PJQelypg0IM369reJPy98cV+oJ9jgbJK+tX/rrpj/wow47u51K2VvFZytCCbEtWjt+RtRjNHoPEOEYqKdMXf2S/Ptoig1xrB6yUKW47B+SlUKEBcZpEQ/VZcnxnK0xtOsvu93xV7ufjHDF+ClI+YqwQ9PD49iQ8/IZ1A4KDe5prNq89/gO6aqdwLquL1me6UnQ==,iv:WA8CsytshgRN0LXWyxm6pHQ0N8vwDfvh7VNlemrja8o=,tag:j8xcAHSK50liKxFFUdpivw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM2wrOVJSa2tFdlp4K2pQ
            Z1VLN2didENDdzR4WmExZ0lmKzd3OXlkam1jCnA0V1J6RE9qNFA0RndTeTRLK25I
            bE54VUxaaE4vT2puaXhtNGcxUExxdWcKLS0tIHlQYWhyZVl0QUtqZlhlaGQ2YVlP
            NVdacHBIL1BGN2NqUU5VaUdVNWpIcEUK46gJYdK3q7930TVJJE7/G9EgX+gii23S
            6Sph1xUXlMG8UVtm+VeFiiy5N2AeT2Eoq7vo+Q9NLfVTiyUtpAL7yw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b3M2NnlkOVhaMys5YkVV
            ZTJFa1laWWcxUXFib0szemZ3Y1BtTEl2R2c4CkJBa0NCa0dmb1BacytZNjJEdk43
            RDB1TTJoN1k4L29BQW1YR3MrZFFsSEEKLS0tIHhnaktSajZJbEdVV0dmb0w1TUNn
            MmZFRFZWa0x4MlJJNUJpbmhzTzc1ckUKkOfdhX0eDQNEEf5PnOK3wFxSUJvHVGSF
            5Sb3jkajz5yea+HDVkSJ2cYWYZm3vw1XTsT8hgHI7h6kMzQSKmTvAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18h7hya5terghrwawgpny28swlat2nqkdrfd4clk0svujqlz9xfusd3zeqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMXp0a1lXL2dKUTl6cHpO
            VkZ5RmJVaUM3N1hzY1ZlK1lVK3J1bmRoWHhzCkNiOU5lTkFLUG5lRWwzMy9OaXpO
            MklRMy9FSXdNZHlFOThocWpHQ0V3aUUKLS0tIFAzWkNMdUNHTmRaQWxFL0RZMXJz
            WVpMdGp6RzRpSFgybGZzS3Q4Nk5ZblkKNoim5HEK6NwezBjadVXZj6YH92OgVlHw
            dlXeiMPovQXwD9xnWuwwWWBigdx+EUPHAHD8BA05pbUYnKBjoTyJoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T07:23:23Z"
    mac: ENC[AES256_GCM,data:iLQmi5sH9zH+3a6UE6rY6+L7Sg6jhoT0cFmLeH1iCn24ovj42sfnsYf2nWb+oEqe5ArDUx82yahlr4iD7XQTSs2IV5VDcjI5L89GUigCEXAmattiF5QIP3U1Lmw+YJcBnxamYIdfQX1rEWaeJbLIrqeLWjQ4h4WIEujzYIsE5Mw=,iv:L4aoEd0ILCJJUqUd6kCnWbYbY6smeBg5caiFgfSVsFY=,tag:P6osbprd188EjSzugOb8/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
