synapse_comment_unencrypted: See https://github.com/Mic92/sops-nix/issues/120 for synapse.yaml quirks
synapse.yaml: ENC[AES256_GCM,data:D1WsvhvE/U6RgCfXcDaSTkmIfPAQZ9TwAx3T3/WAGX0FMFWgFd9ahkTtY06aomQ8MBcb6UP6TpKTv8Ptx0yZNZAnekPo/TmNOPwPdFPDl9XfA4R1od2794VJY95rOUrSScoHSorNwU8GV10dcmL6uYe4ZKYB7coBdwwCjh0veJ0eqIBaPcoDh9lJmQMy6iUUGNG72mFd/Gs9y+7rYouvLvfQEpLteWFyLNgS221mxBe09Kncna2KDcW/R94M4FXoaer5UPCC1QtjJ4GD9EurTs+C5vXxphPJ7J5Y29wj5t6Pz3sm5pqcRWx+t8yw4bV6FwAxY8EDh9YNqzAAN0493wc4oTgm0lGyH6PITtnUuzHyyv/QM3TJPcw+X65FG7LNwqIUkvEOtC4vpqGA5VVybyHcgni/LeBtF5W1Yvia8TESpA1VFNM24auRbLzGQy3L0h7CNPaanSFMjPY4LLl10H3qsu2Zc/XENZ0h1vxj77rrnyxCmgrbp4x8APZhiGPhXy4Bte8KPUBkgWxhH/EwkVnw4Bo6N/pT8cBGVrt5befNxmelpl3LcerMOdGJLEuX8g26FqhkvRXc7gssw4cROqEV7JyJQB05i1k1e+l+QzpQKNk3qFhdV2meoraoNUnCw8+mRktZAOhrHuB/pXxsCee+vQ6/IL85NKf5xL9UelI4y1yCHf16pGlo3EYmjOtyl3Sjj8tY8INWzJGPT9HajFB/LD8v+3JmuNTeyyTf8Xn7z9vcn+RURjGT21eO0foM4dJyHcK5rA4YJKBFqkgiZqjqcm8iBJvc6TtS5YBO3U6JF1biHis6peo27OW0DXKGhswmLGAszGDSjoy5/ebUK5dDOO5np86VJ8zNpTVDdbQFcHYR9INXZu/RTMbUzf9BKCQatyket/ZfN11AbrlRIMBv0z0VxHlTUsOBxZTR9yKIxQLEpXcTh7Sx1zkMA4mmS7WUsWsTg+svNq2Wb/7PSJObMAoT3Twd,iv:fvaZQ66VKU+uzvn5AwTIFgzz+F2kJ8/QR2AfmynRfGU=,tag:Spvb5e6dTm0WyPYuraYjiA==,type:str]
matrix-signing-key: ENC[AES256_GCM,data:aHFWkguW54R86mrMfjPNWdpp43pFfdN1Dvg+75hzJq0GvQw4jEJa27WZaTjsdvP6jl2oXrzWKUqZ0w==,iv:abvwkrNe324QCbWLwiPY0UwqezS0wbyk2Fvi0vs3SI0=,tag:+gsVsAmMW5qN3D3VZF9ozQ==,type:str]
matrix-sliding-sync:
    secret: ENC[AES256_GCM,data:vxECVHY/aIX9RpqLGaXLVbbt2mDDBRNOBPrp/AKwZy71usFSW5pupklFctuDwyeMnP7Nsn0wwFjE9fVdxQwjJ2VDqFM0zmHjjVS1hfjMY5qv/VVt9XwkNlc1cN1PD5RwWPR5Ib6TzmVI1HZVpaCadOrNpLwt4UcCipKN/l219RomO4uC491hyw+tK58Ul+AV1uut5XCxLJXxCCs9lQfMHr3lGfpC9FWbUyer/5fzyB0qCMG3vVxwLF/vWGPFwU+a4qoKK1wvvojJPf9R04eELiJONEoKOtOlxsTBWWRkboFOPiaI5Hpcb2R3cWjJIU1c8m8+E5s18HRwHEdvjOPK5g==,iv:JR9Hz+rmfGeJ+JfDugkI7bzh3wb/o/5CdrzKPXfVTL8=,tag:KuprXWzkyDdtHNB5Zw8MqA==,type:str]
    db_pass: ENC[AES256_GCM,data:IS+c//H6MJuoT9J7rgvbCO+aqqnIin7GW5dd0n2zkF6KdIQCaU+4L+YarLNBEMIlPSKBRQ+ac6WYv6k4gIGj8sAY1XvzUC9W/pKupXdwAdxigx6y1d0RUw==,iv:fKdDDkfGhzCeSB/wBcz9YJwJ7pF7hYP8chAJ04GZRDk=,tag:HE3HDv6TrZx1SN6w1hXVSg==,type:str]
akkoma:
    dist:
        cookie: ENC[AES256_GCM,data:0xe0nUGR8/8sYAA62QUlROUm2wRqCibW0ZQ2I5I2oYPQfPtGYWHjWYl46zI2XW7fk3A755wtASF+RVyxxwvXQw==,iv:V8+MpX/IEc57zEfhNGX5f+eMyipraaXDKPDNDOy0Ieo=,tag:1qK0SVE0XcR9rNEDiuRh+A==,type:str]
    endpoint:
        secret_base: ENC[AES256_GCM,data:svJIGwq8MF1e5+q48IWaWDwflXDt2Um27T4+0FL8txv9t0yU7yTeYwxWG6ATDl/i73NTyIATgyZrcnloAyuUxA==,iv:/x0ydo2gOPrhIZI7at877bzfFgMpraauozfLq95aHCk=,tag:tbpHafoWGxpBpAA0cx2FnQ==,type:str]
        salt: ENC[AES256_GCM,data:Fv9f70W8pXg=,iv:aSun7ABJdbDQrFcrGQMM9H1/7d5lJqeMwO08gUYrD2A=,tag:oI3NAPnFDpSf7EAL/jNqGg==,type:str]
        live_view:
            salt: ENC[AES256_GCM,data:luGhs4c8+Tc=,iv:ZvWKutuMTOm2X8w8a0fOTq+ldrXemayIUY2PUcurY80=,tag:LKnY/ig40XFJu0suATT3ZQ==,type:str]
    joken_default_signer: ENC[AES256_GCM,data:HoT0k9zV0MsDmxfBlN4P8DnH9Oxd8RiViRR1pfuMX444Rw1XhibGs45HksDmSIHk3e9eK45bddSQqOw3CkfmMw==,iv:Yk1f/fzzbruW64mvTTeiyTlbrOO/G47CKKfr9BLtQ5g=,tag:0sZlK1Waz13Vv8770dFStw==,type:str]
    search:
        meili:
            host_unencrypted: https://megumin.soopy.moe/
            key: ENC[AES256_GCM,data:lXy2jl1amtU1qre8df5TRwMAvlSexr2eZPk/ERjlm5v2Znvwk13zpmmtoN4QYSZksgnbGYZtBEbt5b05g7rk9Q==,iv:t0kQUCmjhFw8Z2CTmYOPUNFvyiYfsXETU8GSxhRR5KE=,tag:fHldLoeCXJ7SOMg87jRCyQ==,type:str]
    vapid:
        pub: ENC[AES256_GCM,data:30uI2EGzACtudbDYQlDA5mT0DsNK6z8QELBdo2Q2HZDFoyP4DPWwLTWVBA2mVxGW60rnFmY/AeKjLwjO9x2oPDcm3UA6daor2BGm+gR6i3zhPv1kxmG0,iv:154BP5EmBqnKyf9BND2laKV3caVxa34MCRzrsg6/dik=,tag:vXRajZbVKbw+RfEKuTBN+g==,type:str]
        key: ENC[AES256_GCM,data:bOpWXEhFFbwPmp3CTmjKFFswBAkeL8Zocw/KphQsw2p12BuirTjrXdtzaw==,iv:yQLu5CFl73GCojMBa2II6OhLrNNinsiVG1aPOAx+HtM=,tag:LCjaFMIMffWm87DFzUyf9Q==,type:str]
    postgres:
        hostname: ENC[AES256_GCM,data:Ufg2whp9ibQD,iv:GM2SH4Gkvt8tLG8AYIKxfHTZvB1sT+hgIoqkiViH6Es=,tag:ak/7+3lQ/f8g8a6fsoY7eQ==,type:str]
        username: ENC[AES256_GCM,data:fjs2ZUd0,iv:OQ6zNmDn0uqKqNKEqOHWY6VBuT/4/CHog7b0Pf0TAPM=,tag:KncE5ogjnUsoMicW0Yz/JQ==,type:str]
        password: ENC[AES256_GCM,data:1LwuBQGP27GJKO2J+dGhyn1ENoKfmLXmpQ7wXiGFpyJ+OF/8FZT9jT4k/N8kuXYTiow6re23pet/nnOArfsTjA==,iv:UFe/3H/AfTgSlJikHqE1IED3zINjDuOs5niXpGWXGYE=,tag:NpdXT6otONS+PK/5QZvl0w==,type:str]
    smtp:
        username: ENC[AES256_GCM,data:szD6Mde14MVdpWBzAUVXkQ==,iv:wBXWtRYawOkjumsvTPcKfvL95CCB+RbsEyJv0YUG3WA=,tag:xD9fBAg6m+1cimUZWW01xQ==,type:str]
        password: ENC[AES256_GCM,data:5F9vqwaPk5BLZYA1U0oaEKmZJmCqoSp+ZJTWoXcjymB+Yu3MPv93C8qEdcd12/IGKP4C/U5zVHQXL51j2K4yNg==,iv:ds8Bg9JSJdNHUXh0FvD5a4pquyRnIXowcsJcVV1TyB4=,tag:H4IS+WBPqq5cuH84UgMuIQ==,type:str]
        relay: ENC[AES256_GCM,data:ROypg+WZ4+kCYZ5Y7uk=,iv:omnyn+Xa/cjqK+9l5bI573aR2p7UsUvqGX5ZQGf3CD0=,tag:ZeGJtqy7Dq0G0R1vGu2dcA==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:Cn9CSW0XN21cV3Vo7Yxc+fVTMNS/1Eqbr4TZoQeeDOZIVYfMmxjMPH4CQRYjRN5/pJQ+yPlL3ZCng3iYwAtOZ75cxTJO7dnhwc7BJnMl+uh6Qxp4Kh00fRA8xuItX5wBzFruFwbSYRNDODx8eLrXYnkkjATQGw==,iv:BbBjgsHh1pl904COKCMAh41uI7UH9kHcyy79zKYcM8E=,tag:eh886STATvWgGkFyzDs1kQ==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:oNya5zt6S3H+9QjODXU=,iv:Jb7OeSnZ/+t9GU22nrPVQZJiybKInDQ6ffcg7jdkLGo=,tag:3KMEToWCLGGGlgMjxhLhUg==,type:str]
        security: ENC[AES256_GCM,data:5870scpE8+U=,iv:CTir/KO8cTDK0eDpa6dugYH694DLDcKG+ygRceaI7g0=,tag:jhwtcdxZrB9jfgpcaTblbg==,type:str]
        port: ENC[AES256_GCM,data:B7jb,iv:g5aIKLKIB5++TI9se3a8DAm1TXBtFpraW7ZkuAUMT0Q=,tag:zoWgZyi1zBnLK7h/XvB4UQ==,type:str]
        username: ENC[AES256_GCM,data:lv3UAq3rZDuNLb/uvjSCR09iLh4mnEF9,iv:5J73NP2SZQtvt3Uh3SemkEVLiQoPp2TpWGcgDbvVA7s=,tag:4BiO1UQabYG4mOiUl5SF8A==,type:str]
        password: ENC[AES256_GCM,data:vQ1CRXTE5eSCPB5C8Z0Oasy2TSNbSUkOYfT6RB7KfGV61BG1YaLcaMFJ9JBdQGFWVGCHCs02CC93AbNvCxH66KKUCQG7f6u1FyC8TYEgWjcoRFWVG2T/Gg==,iv:M47gM1ZU+TgldQqP/PfogBFChDhyK5xckqtVRbAWzxQ=,tag:wg2s9Tkz/m1IrO+FKTtslw==,type:str]
    database:
        username: ENC[AES256_GCM,data:aokrxSkwXSW2Jq8=,iv:qPVLau+h4t1SiD5PqwoHjSuCwG/ftH1x+eLhpN5g+nM=,tag:uGv/XTHFvutk8/zQ2E1Zpw==,type:str]
        password: ENC[AES256_GCM,data:5z/6LY9bSEPWyEfW92xjj9OAdQAEr6pKLp5IdCQSQfZUQaoTzeqCzZYgtLTv0q5RaJwJAUQMhmqqOKoNo4PmSB4X+/vhCSQQ9G/22KkC0qqCAQdCyE8JfNzi/E7LuBIrmPz6tH8rcdASHSFbSpn8CY2w3C6H5a+sJPc92Y9nhmc=,iv:yekf7PRi/bwpJ/bLrfSz8nxubJxs1ckJNBxfslnfvl4=,tag:Z/aB0Xequ0q8PAfswsUNDg==,type:str]
    yubico:
        id: ENC[AES256_GCM,data:zutKrVw=,iv:I6YWEq8+lpSvVicgnTnXyobK/dLi/hwyYOGUu52q1hU=,tag:bZSMsSUKseFpXAyT5kE0mA==,type:str]
        secret: ENC[AES256_GCM,data:tsBGkHRyz5uJ5rnJzK+tiFiz7jkqymVLywn59Q==,iv:ovEwbuFtdnnYnr0qpmWrXM3AqmoUsPwe8nIW/4Mkn34=,tag:ma4xG9eNU5s3RuJ703NzXw==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:sGqPKrxwtS+2+7YHSrdmyfk8eoHJUKxEK4kgY3vihtowlQ+5,iv:kakIcF8ZUsdfeH65FfzsF0Vk5GotrDMmzWQF4IQRxhE=,tag:20E4bsONDe3aQIvYZlGw7A==,type:str]
        installation_key: ENC[AES256_GCM,data:/S13BUG5vu5AdNCbwrfOW+tJX/4=,iv:1jk1+5V278evEl/gU/aocOMgXUzAfbFVECG/sQC0s4k=,tag:XR4WXGqBMu7/+XG0PIP10Q==,type:str]
forgejo:
    database:
        pass: ENC[AES256_GCM,data:64mdGSBmJfFYKwiCjHRIJpEAUQwVt9EttxfEflNd5QHZHx2xtSXSxXxuAiiWA/vUrr29/FTCoQxvD9iScKa/1O59sMfmrhqfZVaZm2JNmEC9OzTJVS8kzA==,iv:OTogoxwmalk4CiUlQstlER0JVN1YuVhWJgrhGJPYiuw=,tag:fspuokHcdl8L2NTIhb65Xw==,type:str]
    turnstile:
        secret: ENC[AES256_GCM,data:DqUoQLMoQj2yX081QL9NTOrFYOMAQhbTn0MKhr0mydyypHc=,iv:yMnxn15p5HYZSMOCBT30i3gpClyW/2fx8Ytx9sQKLSc=,tag:XBCcgnSePHKCtXxsSA2mwQ==,type:str]
        sitekey: ENC[AES256_GCM,data:4MpqjtJQJayqFB4QiQAkwjJR7BuXR9Wh,iv:VaWMEu1QIh4LeauflFjJJgblLyOFkTpb4Db9wip6uY8=,tag:ncMTDWg8C/2bBbd90voCfQ==,type:str]
    mailing:
        host: ENC[AES256_GCM,data:sLduW9fD3+Us5NJKqTE=,iv:7ksEKqX8nXS4A6M1JH3+FPWoxAP6naB2huwJ7Yc816k=,tag:xEGv7sXJkdKMEu7cZhy/qw==,type:str]
        protocol: ENC[AES256_GCM,data:gGQMEUs=,iv:5ryKSzDHl1Vo375IqCnRr2TrcjJCvQgkdHHuIJ0Tk6w=,tag:wkkzJNRNQTmUeuywG7zoQA==,type:str]
        from: ENC[AES256_GCM,data:36Nhidhh4SUmJ5yvwhS3RAHhUP7UpVlGjerM6FDi3s/9Eu2R,iv:keQtnPpEdZpoHpWnIE/Dy67QTAWBhE1H1IGbtFOJMtY=,tag:6V+BcVRTtzIr71gOecfiOA==,type:str]
        user: ENC[AES256_GCM,data:/SYatKgipb9/kmQo7fY20P+h9CHwW3Pq,iv://IECba3A/MlXv4q0eCI1DXZFF/YxF/U1AHhCrGNd2s=,tag:/tc4ZcwTgGA52Bge5sxCuQ==,type:str]
        pass: ENC[AES256_GCM,data:XdGkmEdftc/I4BMElxicLoP2zWBqt/VC9yA+8BPTB9V6/uk0LrsooMejj3JP+t4i1p3E2s8/ayP7nWsRy37vFHD9deHaP81BTApLDOGLOT0xT/x+ysYtIw==,iv:/4e5+aGW/HksRYXXrpbYZgCCWPYD0n2plb/+tNwu9hM=,tag:VwL+m81X43reKM+Hj6fAaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rkyshu0lswdqyvun4cs9cekm9zt4fw5c8ssa38tn3lukgcahcvsltnqx2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWEZkOTlGejlPOVBTSnpk
            MXBjVzAwTnd6Rmxla1Bya3VZVHdNMGZJMkE4CnRjNW1HZkpJOGZZL3V1dmV1ZHRF
            MHh0aXBrbDRLbkJteG1QWVplUVd5ckkKLS0tIFd4M2l1S2RYNXhna2pxRzNhcnNU
            ZjVQdkpHbVYvbHEzYURQTEpqN3cwTFUKb3A39jzQvsDp+CxQpvsuBLSFtugorfCC
            XVHHouD6h/3lzz1tvxUf0JxVZKsshOWR37WEQWtSPEDsBiWa/JYgng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18h7hya5terghrwawgpny28swlat2nqkdrfd4clk0svujqlz9xfusd3zeqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MXRmVGhIR3NxL3p6L0kz
            VkMxVkt6Z1Q3L0xNYzVycC82TlJkY2NFS1RvCmRqaGdVaVlwK05UNDVoQ3ZVcFJk
            c0s5TmQyU1hlQzlnSWlLL0F5QU9Va1kKLS0tIEx5SnJZQjNsenpKWm8zcUs2SG9w
            RDROWGZBMjlaZ3lFUzA0cllnU1U0R2sKFZCYpp/W0CdJatTBMY0VDFB8KkglkSMF
            jTVVrcOhihnztDXSGq4RDdeRVu98gGSUUZOnEMjgyYfHrxY9aY1RVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T10:46:36Z"
    mac: ENC[AES256_GCM,data:K7IGkiVL/s9RxOdleqwlYwMVTlgtH+iq1+gN/4zocVDtmoG8eDf/VgwCCRldpV0Uh/GVjmIAENX3vvg3UHbjryNU3bF+2vpqjitVKkwtFRNDGwjAqif4W4PBnPO0x/ZFMQOv401lqC2/aplZMqlxxWoS/RvJRygp0sdh4dWYc8w=,iv:/IUTuqyVb1hS5HiU5RiEsvUj2KpEmfmpIWrUHCvC5gY=,tag:ehn1DuJ3WBc1y7WlgcRN1g==,type:str]
    pgp:
        - created_at: "2023-09-08T14:11:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DAAAAAAAAAAASAQdAc9eTYMV21thYAun+oEVZw0Fq21Im/vlyCFsMEbLMaBww
            /KKfW7aFZZhv8saoLd/ntKCg6wVyhZHr/rKraH6c3HL6pwHhM3Ifvj6Lstkjd8UL
            0l4BG54A/fy7RTuw5eclMp0S6GSeedqSKR3Gw5mA6nX/l9KJ/k4gDK0XZXCm/8c6
            5WL5117xE2zKegKf3UZgj+P/HmV7w2Z+kmtTZLrxzFog/tqMwqm6iQJdyQ+xhbHe
            =k9wB
            -----END PGP MESSAGE-----
          fp: 8F3B277901484C6EA7E63F82D539637D518022C6
    unencrypted_suffix: _unencrypted
    version: 3.8.1
