synapse_comment_unencrypted: See https://github.com/Mic92/sops-nix/issues/120 for synapse.yaml quirks
synapse.yaml: ENC[AES256_GCM,data:F7MTc16PBofllp0Ij/nHjaMQIboXj0aj3SzbHiNpAKSrZVsrWCcH/Qv0PT+3Exhz7xaUdAiF3e8Fi5XP0J55rXY7B6JDj0+/GMW99UPcRk2vTfpg84VDsFK1v5k8k5yEgV8xEUvhkLjR4AO6Y0ufVu3XE92Ubzi4HFCsTChbZ8ZgvEuTHzHXUFCQWHLJEjVtGmcZzsXCvonq/0YvTDpzPrp79Xbfd89hhTyN8qymLnwgOv0LKycFDDPmd+tO3pgo1uu5qOsj6e6Zn5U3wYQvXyWJX20SLBOkN4DYHUoiXXLIPf537qUdvOyYrGYh4MBwwJpTuWmHrQ/f0NmAmY4fsBsVSciGLeXGYs9fUY54tK09ShxHXFVpvdfVVf/9QLH69XpKIP4Sa49Hp+LeodPfKpS5Yz1F3bHYrAFHZDWvPAsFhglhvY0f/+yn+rp2cROxIXRhAdrswtj8IpC8rNtlfO+AeQyWEgocqYbCrPxUSwtEM2QcFs1Pa0IJm89EbL7KU/k44JaU3wNTT3GY5iPqnVQJciBJ0CW3flC4RTt8QqgaqiTLxifLtn6T2rAjxbVW422nYuTlVRLXXwuRawb7uiv9i/Ax50ekRv/lOUT1ypAFFQS2i99TgwVygQC9frYPCPw/AHscGB0tUCZ67X0tcvcGmuSKIQAOKxMQvqfieA4MCDztDtBltW4iJxtDGIlk/p/78aVA3a0KIGxd7pJVtDUnZvdQSKmQmyvIJcDWpMuFwkhI/cfnwANn0YQFvfARjEKE0EP/XAgazakv1uUcP8PpZBTbEGr/uFQOOUJIjhkdop2B1sBzjE29HfFE/Q4pZslK4iGe8fnFCw/aqPHqVv/ukK/JyPs55spAdqOmlgEpTxWvUB1oAfn5MgrEksEOK10u72+Ub8hkzoevfnZTEgv8CqVtFfhwahBhePZx9YhUVtE/lVBsK1mEGiRLJLKSQUYb6kxR/BGUXperQyr13TqFaahCiLI3,iv:fvaZQ66VKU+uzvn5AwTIFgzz+F2kJ8/QR2AfmynRfGU=,tag:XV4bWmYZFKadeZ7k3dNv3g==,type:str]
matrix-signing-key: ENC[AES256_GCM,data:BeTwWMxbwC314CMn6BxPUKtnr48ipV2pbewRI0l8yNEuzbSFPNwU8a3i41viOoRS6Mg2jEHTSWDRMw==,iv:abvwkrNe324QCbWLwiPY0UwqezS0wbyk2Fvi0vs3SI0=,tag:1MkrL33pWhmdVUSJQviITg==,type:str]
matrix-sliding-sync:
    secret: ENC[AES256_GCM,data:9WoG0trBuANRdON5wvN6UXW11lwwp62KCg3m2hubjilCRDvKevAjV6cE3ketDf5jcsmPuePtfpRfddsvC9MAkGYAKmcRNM2BrqA5a5Yvor8Fc2TzGUrgEF9HXCCPASM3sQTup7NCJRVvkQsVRQqC6TFju5PMGsScZjvLtsVTIwifh1r6w2Pwr4fBl92x2g4CLAFQ6gk2QQm3YUj31BG0UcLtopaAH1+jRQIMDhgp+dk3umM2HSJHpm4gMG9uhEZI7daMsw7dc9pXK4jevRyShaT87JiFqCEKM57OJadKuV88DE0wvybN4g4FM4lUYm8ZjGkpVfIWKIcm9yayCEv0SQ==,iv:JR9Hz+rmfGeJ+JfDugkI7bzh3wb/o/5CdrzKPXfVTL8=,tag:09bnhNkYi8FRFN08AjcKuQ==,type:str]
    db_pass: ENC[AES256_GCM,data:iAFXDwyX1ujsj6lFBX9YL2iR/vh6JOzhr3Wvx4zv4+aF1CcgYtar9m7ZvCdO+ZWF5bIvK34SwBHkmtq665lp3iQgETc8jUN+45/tP4nHH2rg9nMipuGs9A==,iv:fKdDDkfGhzCeSB/wBcz9YJwJ7pF7hYP8chAJ04GZRDk=,tag:b9bXib9UNkTM9cLCH/M7ZQ==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:SLO0d6zZhC3t8vSx99mUlhUSkWcx5P+fKrNZvzy0SBGT+Ga4puHtteCXk3xALlTQJ2LmQTNg+uj9vI5XC0+4eNT+kjl4gmZvberT+6/ANQwylKWkL+IXMjfjMzRuX8yRJGH1R1j11fZDgtSWpGvNqMicDkasuA==,iv:BbBjgsHh1pl904COKCMAh41uI7UH9kHcyy79zKYcM8E=,tag:8goYKIdtE9QX92VgZpA9tQ==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:92P5COMWfAf09s4slCw=,iv:Jb7OeSnZ/+t9GU22nrPVQZJiybKInDQ6ffcg7jdkLGo=,tag:wrsCY9qC7/TI/p1bxDt/ag==,type:str]
        security: ENC[AES256_GCM,data:4X5CLH4KoVQ=,iv:CTir/KO8cTDK0eDpa6dugYH694DLDcKG+ygRceaI7g0=,tag:J/WuWuNYKxrXZ08n9rG7+g==,type:str]
        port: ENC[AES256_GCM,data:XKc8,iv:g5aIKLKIB5++TI9se3a8DAm1TXBtFpraW7ZkuAUMT0Q=,tag:qumWtCf4qsyNh6dOkDPmiA==,type:str]
        username: ENC[AES256_GCM,data:RjGJbKkEmaMhKKsjdEvpb9YrvYBeAJJV,iv:5J73NP2SZQtvt3Uh3SemkEVLiQoPp2TpWGcgDbvVA7s=,tag:CkucUUmuRESTCSzdJ2EF8w==,type:str]
        password: ENC[AES256_GCM,data:DdBBZbN62iNlTNzxknygeZeaiTVQ5behsJzlswsRzDa+7L8wSqaHp5UsnkuomTfJdgGSqQo9ObnCqm3zBj3vEbUupj6Ur2o5OWJDYXK8hep+WRUMrYqd2w==,iv:M47gM1ZU+TgldQqP/PfogBFChDhyK5xckqtVRbAWzxQ=,tag:kNw+TslEPPena5jtdRLqNg==,type:str]
    database:
        username: ENC[AES256_GCM,data:UjcrR4QQxBtjoto=,iv:qPVLau+h4t1SiD5PqwoHjSuCwG/ftH1x+eLhpN5g+nM=,tag:msp2oCjlM7TzrFyit4Qi6Q==,type:str]
        password: ENC[AES256_GCM,data:5fZan5fT1mEKQp3j1BoLNKM8TZBj4D3GJEuHJC4iOjot/fCs+8CToU9K5ZbBlJmBLU0NQNmuw7ic1fajw3J0HkSLeKMR1IXYymQy9nGs7/Dtw7QmpanLRatZpSYfPCgQg3BM6lol2aW1rhwIgZGtuj03zp/+GhklRxZyj91k76M=,iv:yekf7PRi/bwpJ/bLrfSz8nxubJxs1ckJNBxfslnfvl4=,tag:adD+ZG/VNn9Q4shCU+6lrw==,type:str]
    yubico:
        id: ENC[AES256_GCM,data:P+Rg6xo=,iv:I6YWEq8+lpSvVicgnTnXyobK/dLi/hwyYOGUu52q1hU=,tag:QfF6mJJfklGlf3eqiISjeA==,type:str]
        secret: ENC[AES256_GCM,data:lUHh8w6FUR8HqDvLEVa9f27wrtpqsZOYDG8DhA==,iv:ovEwbuFtdnnYnr0qpmWrXM3AqmoUsPwe8nIW/4Mkn34=,tag:ikECSoxkqmFehjMJS2ju2w==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:u3uthapB5tvhLsyawp17H05zF9rgwpo/nulRc53zPQ6eKg9T,iv:kakIcF8ZUsdfeH65FfzsF0Vk5GotrDMmzWQF4IQRxhE=,tag:ytTT+k7EH+aYdkP0BpvI7Q==,type:str]
        installation_key: ENC[AES256_GCM,data:qYDdS5gV+1RWwjhZZVdQFvTqdNI=,iv:1jk1+5V278evEl/gU/aocOMgXUzAfbFVECG/sQC0s4k=,tag:yAEzpPbY8+7DCXq0gvUcDQ==,type:str]
forgejo:
    database:
        pass: ENC[AES256_GCM,data:KJZATszG5hOCV6tlZiNNK9n0Psn+l14hys1ZzMy9Hwsy6gjanFQzedNn3fnwZgZ9ani9CO1ncdAj/xNk7EweO40FIBT12Ih6m9JvTugQDveYU38v9TKitQ==,iv:OTogoxwmalk4CiUlQstlER0JVN1YuVhWJgrhGJPYiuw=,tag:ZNavKCvqjkxzvOb3hSpd5g==,type:str]
    turnstile:
        secret: ENC[AES256_GCM,data:zmnN7OmRjf02BVTiEic3LzbxCOD/Q0GaBx6wTha0k1jB728=,iv:yMnxn15p5HYZSMOCBT30i3gpClyW/2fx8Ytx9sQKLSc=,tag:Hw/HZrO7QEYExCPWFkwYDw==,type:str]
        sitekey: ENC[AES256_GCM,data:9hOoGMaEPGUT0XgWc+tSeHqxNBKwavoc,iv:VaWMEu1QIh4LeauflFjJJgblLyOFkTpb4Db9wip6uY8=,tag:cPbcxVL3Ov+xlGqbx45NQw==,type:str]
    mailing:
        host: ENC[AES256_GCM,data:wIG697u0AjEo0Hu71g==,iv:00ahgX0qqr7905RgA1QoLW5xFC6EhMlfPvZpcjgWmkE=,tag:StOQOrXHVghW1WHkLdbZig==,type:str]
        protocol: ENC[AES256_GCM,data:N9xCOt4=,iv:5ryKSzDHl1Vo375IqCnRr2TrcjJCvQgkdHHuIJ0Tk6w=,tag:lIxU1dWDKfKtzSl7F/Q2KA==,type:str]
        from: ENC[AES256_GCM,data:mwcO1TA9w2A5hbkrKIwbpA8vApqaoGUeK+QVry87WmH52K6KXg1RztgFAi7E25w3cg==,iv:p1Xp/Szhh60QzBPN/7w+QgRe/s+VOzv4JlEEVhiysQI=,tag:WQSIoGEJ8gAbPO1ZArkU6w==,type:str]
        user: ENC[AES256_GCM,data:71ZJuyuFeT+YHCdYZ96ogP6NfErYnXLr+g==,iv:242pszmIpJzoaX4Rx+7nYSD8xoDt1aqViQeBCUH0SlQ=,tag:EOsPhFvozIFkqdA8/B03FQ==,type:str]
        pass: ENC[AES256_GCM,data:K7AwpFI5KNJC7lyTipnus2ynkAmbYikDeX17qUutun/EAprDgr2dufB7mlhvvsejj+m7b7toh8BcHYfjN8oqSjYpB74=,iv:qBqTOLuzS0E0uBQyUK8vsF9uAhKyCf0Q/Iuy22twGEk=,tag:43Ug+zcCDEPyWcOPDkpAdw==,type:str]
lego:
    cf_token: ENC[AES256_GCM,data:08Ysg8RNHjDNWKs+/oFoJIm3skJ4Yd9kouq6fzw0z9FHzstpI7r+BA==,iv:utJunj8wewHFdOaD+EOgpN5/RpXyCdsl5Lr6kBbXsvw=,tag:2f6KRuQUJeRjYt6CPAEalQ==,type:str]
grafana:
    oauth2:
        github:
            cid: ENC[AES256_GCM,data:YZ6c5PHqdMwM30hCYxycpk2xapU=,iv:K/WKrdiq9mXaFV33zYQYeYgia/54t6/qCseVGykW/yg=,tag:e0UQEcMJg88JD/5s+pkK+Q==,type:str]
            cse: ENC[AES256_GCM,data:o9yW6DRgdV+eX1OQ6XyJUQsZ0SMtUY2MrWrfhhqf9LgDRdsHFZNxUQ==,iv:iNbKhyUIuKtBUVHXdR36KWCueMjQuKIErl8P7intFX8=,tag:OpzLX7zbOfxVxZmL6crLWA==,type:str]
        gateway:
            cid: ENC[AES256_GCM,data:M9LrS2w=,iv:F8A+gIGPUjziBTuBnhVS9kygzZYjnwFayL6Mx7LBwe4=,tag:ioQXCTFxqZo5yOnucSLz/Q==,type:str]
            cse: ENC[AES256_GCM,data:YYTOpfaOlwo08qnPCkydj92N3TxDtQxwXAA0xVVB1hQ=,iv:1InLcW58sbz9wfp9VnONsqE+iDrhCWhlBBkr13KfN1s=,tag:4/OIhs4kqgBeCHCNkIwAGg==,type:str]
vmetrics:
    agent:
        akkoma: ENC[AES256_GCM,data:r/WgDnHN1GQnWPRbRE+nx6vC+FX6Kc+8Jr9DSGP07ar+QwIey3YUeFUJDA==,iv:M5NrIERoQJohFqCRgP3TcwW0OspHMIbZR9x8G7jvI8c=,tag:sUJG5Gb6VVOIU3VbXhNrXQ==,type:str]
    auth:
        hosts:
            #ENC[AES256_GCM,data:gh8JtuOIKKQuttfi8QiE+N1IzmIHvV/pnBuHmAZBJOYG6CJmOfCxoTVcN4/wyc4=,iv:IeAZya/9R5fF4iqmmMzZ28J8hj9yYBPXnljsCVhN73U=,tag:a2NofH9HbEL6+tJUSufFig==,type:comment]
            mail: ENC[AES256_GCM,data:WbGo+dyVo4b7GDk2/SVJLW+K1kcSd3EWzVIcz6IsAQfG0gQ+EWe+5e+i2sHevXUOOIT/cp70zmPkEd+HlPZb0LXjhSr9cFA5wyDj7Nvy7c0TDztbPdtYGou479uyq3Koqg/nJlfRymFEdKEElQUprtHIjcgHibOpdhg7oS1qrVIrKvhdgewHvPg8eD8Fq/GtkGbfRx4ymdvWpiFlBNMLp5tRygA/IBrO0a+YEQ==,iv:Tm93jST/E4PkSlafzMWBfdOZj7g4J0dzBSeLrS8o4Ow=,tag:9mQHxr3vRJtOuzYRWV3gdQ==,type:str]
            bocchi: ENC[AES256_GCM,data:7XvaYjaZJ4OzEWsrqmURN8mDPl9DzPlpukbb4ougHtW8Z2EmORF1EEeNztuCC/hX/za1yB1LtejMqeTqx/UIIbDIFgtCSbXm+XnMMpg6OyQYoqk3z7E31ZtBmq5pER8eMxdxC/5Jug/SNfX3RV7KCCW7jVQkbBAJQ304oy5evfQ1+d6dMgsm0bBmIAA6TGCgoI4WREX/MefFs1gOLozPCXOg3rqIjUzVMc3+Dg==,iv:vhfxElYtouDM44cRzZwuZvJMncRN0Wt5uSfcSEFAuoM=,tag:V1CM8mDkH0j1YPY07KAXfQ==,type:str]
            satori: ENC[AES256_GCM,data:LoTJoCWMtWtpJhcbS73kffix7QMhM0rPHtJQbM77oG4aT/D4sX8vWsWgKPmYsxzkAMeI9lUQ1rgX2u2yOd7asUSjuW/U4pUsaMSi8EEq5dxbxPoAZQVHRRCImBWtcHeOa8AMH17lohYDy01AiCmH1da8c7iMeg68IQ8DoHGLQMqY0GJVLIwoh9dnyvpf4ALFMPMnt39vGi3hXjHQlcwYSdTS0BIgcrW1oHMrhg==,iv:6NhlTlShIUrtl5844NGWq5903liy7pbbsaa9z/OBxSQ=,tag:7i48gmPmEKCzv1cq8P8jUw==,type:str]
            renko: ENC[AES256_GCM,data:PBo4AZ2ELq7+D142B2TdrAEPfcOAee7Go+dpN1crBvJy0DBLMvOCDnhRevRyf2hhqfJ57r++ILTMr+R3VmEVvTNG8ABhEDSria5F5IgAbuRTnk/ZJgi84xqlEyGVIkG84GsTF+QFNWBgS5OUOjuelBosYoi1OhhnQU+zxUIt4a/T+JNASq+ge/AQoyUJUOZcHv91mOG9AJEVqQCXA8nV8WQxPNBJII7qFimdIw==,iv:WA8CsytshgRN0LXWyxm6pHQ0N8vwDfvh7VNlemrja8o=,tag:h89e8WCDuzbkd+vLAA7EYg==,type:str]
            kita: ENC[AES256_GCM,data:Niwnk6+48nXbUOqGr66czfLffwNf22Uewr2NWI5WzLzxxQXmc4z5/PBzjDKScwoHwOCW8g1b310h4xOcEfzcco54xpGhRhdGuHYjZp+voVC7ugTsQ1qA72a1cjIfJekPtUeeWzX7tiav+6AcP9xdmVWGtPG8DWbCQRn58B4kR43G6fyIMD5XNW4VSJdcssZTR5EvT9DFSPVhdGBYPjEOsohnMB89W/+e4gVKFg==,iv:Wvx+ItZIrdHO4W4M6QWIZgyGDINWoNKKPWVbarnGYj4=,tag:PARM4+q0H+w4v9ZJUnTvQA==,type:str]
            ryo: ENC[AES256_GCM,data:vFOGhKs29DKvUUp/+N2YyOEf1eRz5Jr+F06zfAYSIcR8E7NHHlPeZO2xwok9V+4TRvCmFsJZs9X8OQ7DI929nKZ5xqE6ej7aXOhgd+3KPY4cLcSS+3QShW7I/EKNnt3P/TI479AZeXWToZ+QrcUQ4erH9FG3iiz7AD1c+oDc7BP1LjoNQcVJKrWch5P60tJoJE0tq8wwhOsvMCsSPW2lAJvLmuvXF98hTL8EZQ==,iv:eIIFeKHC6DygdX0JIqZgban10d/24UF8K49DiFLpqb8=,tag:qtGKAssQygryT+/aog8sfw==,type:str]
miniflux:
    admin_pw: ENC[AES256_GCM,data:yad28v4L9v1U349tOqlSJLs+wxU2isFi,iv:zJMay0BMstifEbpzQ+fAEr6+exkVpdGvRLve5Ni8EiQ=,tag:eEChDTcEFytzkWA6/qEimQ==,type:str]
pds:
    email:
        address: ENC[AES256_GCM,data:4GAp7aW4JtTlfKc7bohYRyY+6KeJjAXJW/R6lpF22qMEbOTNZA==,iv:GG9N8u6Tlse+rVTQ4Na3KhA85stsFSF874/5/TKlw38=,tag:NfW/5VqIX5raz411Jji6rQ==,type:str]
        url: ENC[AES256_GCM,data:wXRXEjrLeCVyrsTWfAHw0D95byOWHABU6SvIHguiOUW7r1fljAt8f0QkaSaaIg1AUN0jeSYESkoQG9yk8cxL7/vqLwK421j+Q/LZsWATbpLtkSHHdzX6YQUDw77MXqGON88YkTpk3Ur6P/ereQz2iBP9Ph8=,iv:nwED4OY1R3VWSjgNy79FbiuNQ5qKgOX3YPHhZJKTf9A=,tag:fVJtQwAr9rEtDcREXVqgwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbm9IUFZKWW1obG03VmZM
            amR3N2NPMDhDUTNkTENPZStLV3luUEsrVkVJClVUL3JtYzNGYk90b3NubU5VVG1u
            Q0JVQXlhWjFBeHZVQUl4SGtBZHhJUWMKLS0tIDZ5RUpNdkFVaW1uRHIrQ09EczZa
            U1FQbVRKMGw0eURlY0I5S1BPTmFvK0kKF/NluxRwkAkS11AujkOzdMlUXfkAolvl
            2Mt62hDtFwxh1gCQDq1j1RC2LtcG7FnQpm1CI10POIDE+HfuYNj7uA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYzJWZjNQOGNaZTB3NGpG
            ZzlBY3lPeDVXNmhjR21CTUVBRWZYZ3pPRldRCjJjN1E1YVFrMkorYVZRSFRhTzRM
            clJkL3RyalllUldVbmkvWjdsV2JJNjgKLS0tICs5WVFvQzBITGtJT1FnSU9lSUpQ
            cElpckVHZG5WTXV5b2dML041UW9Md1kKtqsN/agZiQSEmsRcuWoe0FZwYk+CTjld
            xhVsLW4STRZ7Xxd//RTrKf77uPfyZglQ1TdstXi1WbFnruJbOq+piw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18h7hya5terghrwawgpny28swlat2nqkdrfd4clk0svujqlz9xfusd3zeqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRlVoZERKTWpESXlFRkEv
            Ukx5b240RDllT0xsYnZJQ2MrSGZHeXBuMDNRCjA1VTRpRzJaMHpicmJWSXpFa0Yv
            b3lxSnFGMysvbFIvaTBPVFg0dldwR1kKLS0tIFgySVNQT1QxOE5SVGNvWUY0ejNC
            QUlVNExmVGd2QXJwVmRGa0JvMmtocEUK7Zo0Mtj3oZm5Etp61cGbLs+2XP97pjR6
            rtfHnuxceJj0+yBugfwgFD1TGJ+6M7z5YCwTx+GAvbPDrmSm2TGrwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T16:34:35Z"
    mac: ENC[AES256_GCM,data:Mq6Y3HJjLVeE+WrpU1Tl2FJF+bETCrMHqYq2oRJloMlTQDwUI3PNdsaQ7nspQMhI7Yp+ECCmXOWa+kuHu5guUikWYOHVjN2Kb4i6P8LldPpyh1/NOEYsu/nBSGpl9657f5iIBqqiW5bFVFviEdBIUzlzOAZD5NRxnaZ3uEdtao0=,iv:T6l4ffisrB/Qj4jbWndf3x3ZMxmcXW4MsZvYB83Vgms=,tag:ruTqOWmnQLtql4q9vpyo6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
