synapse_comment_unencrypted: See https://github.com/Mic92/sops-nix/issues/120 for synapse.yaml quirks
synapse.yaml: ENC[AES256_GCM,data:VclLrPzim2rUCi/ti1iNQ6KKlyrGpyK/KPFLMMBbm70D2ZIHpHui1TOWnlwRk2ldwqYOV3RQCrRpFIySSJUmA8EOUPDw2i0Z476Bl9Hq+QBympYzOmkScVhDZg3GNTpSSY9MLZ8unBmMnr3QiE6gNB/cStz+0rMhTzb83vG3z50ixDGlqBVRndfOfGIsYp3umoIbRbHDNEITfyiSPNBXYx+rK0nXw/FDVqRUk14yNzhmlkRsjgzx01DrC+KDZVx7BzcQOBEhoZ0PddiFZll0Btx2UatthET83BSVEEZFy/ZiDg9jp9eiSxpFZElm4WRyW9lyVVuxJdOLR47Ei+gxgn/l26++5VflU8AsOgRFLUrf4ivTQJAiNyzXA0UcjsAT/0k+GRi1r8oeWO/7P7Ki4lb5B4fOslPxv4rs5ybqiYp/OFidt/yTY7GGa/1glOvkD/ZATBDd7ADo/Z+Ts6XVJQWreQbHvGzp6HOZ5sDRJMFJ7JyaDxwkSeUvbFZhSwqc4XsrtFjWbKjr9OsL0L/35gkhLKF4RsJWDEr15XoTCnayCUPqOKI4Tkk/Q3bcasgDgWUOBrNxGqb2ubvSfP0em21zeOdez7qF8Kf8cfeUgrDNleggYHDMHfuM6RIq6w3pmye/bwKJfLnAKbOvkyd36/7FuRppcdonNF55eqHQTebLP5P0m+FIOMlQBQL+3CDYPiJ6oGA5fEwyyC7OxM2Pp4506nSMTXlp9+yIgY9TVfseopqHLfr4UHboQf1MFOwuq8She0+5cLeuzwnfD04jxSW9dOhMjPDEc6BjRfGPzocX4rIpCgHRuCnttL5gqKUPX4pwQHbIWXcLEC43Y7Z1Pf3xKVryqxi6yIBRM7cmcDsZosovue+3o1595sYUjL/i6F46oqRhlNsSPFAJo8NW+sYtKylXQCDWezkCKiMUgJGz137ymZlL/yZcil6DeaGFcdiSZmsRN5YafZg0v+LqsNnUHBO2zXh4,iv:fvaZQ66VKU+uzvn5AwTIFgzz+F2kJ8/QR2AfmynRfGU=,tag:ShzFrRu40KxOwBk34Su/SQ==,type:str]
matrix-signing-key: ENC[AES256_GCM,data:C4u3NzFB10TnMTosVR4bQIDmSrAhFM4o5/03aDexKkK0vuWwsPZw/og0626GPDAxlpKTtVyW8BKcWw==,iv:abvwkrNe324QCbWLwiPY0UwqezS0wbyk2Fvi0vs3SI0=,tag:JcxDAypyOW8FkyY60N/Fkg==,type:str]
matrix-sliding-sync:
    secret: ENC[AES256_GCM,data:6T+6QVW3HdcrTIuI+QM+oOT5SmiRST3YiVux+lSEdeCjk0EKlvWu+az2eTBv3eHTmTk1etwZlPIV6A6VTlNhObryvVfLNJdIDMYaqwkJ2RtvSIly+VIXiOaewZIPgHEKOajW+y3d50cqBjH8ml1Tbe/5hvBfaI27LK1fLptKmw7kLO3v7ej8/HWmR5B6qKKlsLfGxNA4SgymRZj1v6E7sk8ijCw9fCYVoVXhog980isIBnbYnnlXdeO+H4nKZ+nbVXR968QyiNl3XpL9prUCBc5xoMlk5CCZ2jgSuXgxs2DPySwJgvi0tQYA9oVdn2wcOvAg24rMN3Txk2pLVLFR7g==,iv:JR9Hz+rmfGeJ+JfDugkI7bzh3wb/o/5CdrzKPXfVTL8=,tag:eJQZoWQghnL1yAYQuUuLWw==,type:str]
    db_pass: ENC[AES256_GCM,data:A6oTvvLPn2vCwHSoWbZlPvh5dZG/obk2US097YSDLH1oxZdtduOVclyL1AcFjxFN7+ZspJCgOvhnix8C4RSNwVcPGGq0zQcB4r9U/ZoKvYueus/n8R4WEQ==,iv:fKdDDkfGhzCeSB/wBcz9YJwJ7pF7hYP8chAJ04GZRDk=,tag:FJZU4b2k5QI0NVKUMuxxzQ==,type:str]
akkoma:
    dist:
        cookie: ENC[AES256_GCM,data:5r8LXTygQHFzU+egmdEQCWs0EeZ8eP7yPssy88UDTJg+SBoLOJBozRb/RULBPthc/UVb3g28XpHbHas0H36atA==,iv:V8+MpX/IEc57zEfhNGX5f+eMyipraaXDKPDNDOy0Ieo=,tag:bNbRD5yWOxT6sPcyO2BrhQ==,type:str]
    endpoint:
        secret_base: ENC[AES256_GCM,data:KEqeyGA5IOJc1q3KoORmjY4Io+HhMRAAqUGManuw5xo1EIO2xhgNc1yLRoHNZ6xT7hJ9tOiRmV7vOnFBXrOeMQ==,iv:/x0ydo2gOPrhIZI7at877bzfFgMpraauozfLq95aHCk=,tag:E9FOCrujPPt96iDK78tC5w==,type:str]
        salt: ENC[AES256_GCM,data:Icvlgq1CfFg=,iv:aSun7ABJdbDQrFcrGQMM9H1/7d5lJqeMwO08gUYrD2A=,tag:bZEwHBG74eQBqwku4cJcUQ==,type:str]
        live_view:
            salt: ENC[AES256_GCM,data:oF89/jTl2oI=,iv:ZvWKutuMTOm2X8w8a0fOTq+ldrXemayIUY2PUcurY80=,tag:VeBaE0cGo+nzy6ee/Cj3Ww==,type:str]
    joken_default_signer: ENC[AES256_GCM,data:mgPk3o6uZFbAjpi6i4M6VHb8qF4NrkBdLuEA6RYWg1c0xHVUU2kG20ZPjAY4IJt0jTXUYTtG8yoMk2VP7eTUyw==,iv:Yk1f/fzzbruW64mvTTeiyTlbrOO/G47CKKfr9BLtQ5g=,tag:csLKS/vLrI3x+JC9zdfyOA==,type:str]
    search:
        meili:
            host_unencrypted: https://megumin.soopy.moe/
            key: ENC[AES256_GCM,data:1bwg34aMk+kh6nyFGSGE8EYDrBEvsZ/eIoJeH3ZEw0NK8ZucwCSdjvK3NnKwiXse8rs/dE7a1Mj3hz+k2aD/KQ==,iv:t0kQUCmjhFw8Z2CTmYOPUNFvyiYfsXETU8GSxhRR5KE=,tag:OHKLmYM/p77x1+X5aPk32A==,type:str]
    vapid:
        pub: ENC[AES256_GCM,data:W2aor4OVhBupKt7qP5BWoKJLonYTcqn+kWkcDe+agan109bQ6R19HEjmq22uF+IbYahugofHiVC0BOshWh41WpKuDT1JCjpmhnBxI0QfFlq06dZdpPjF,iv:154BP5EmBqnKyf9BND2laKV3caVxa34MCRzrsg6/dik=,tag:Wf6y4AOdIExfTfsivRIsIw==,type:str]
        key: ENC[AES256_GCM,data:v4wwWoMzOAfha/3HptRM8kgzGThEocBl2K99FOL57rt2qd65BUlmMtSEpw==,iv:yQLu5CFl73GCojMBa2II6OhLrNNinsiVG1aPOAx+HtM=,tag:yH1wWzXuo0C39oEdl/XB/w==,type:str]
    postgres:
        hostname: ENC[AES256_GCM,data:8foAQ9bd2bLm,iv:GM2SH4Gkvt8tLG8AYIKxfHTZvB1sT+hgIoqkiViH6Es=,tag:v4hCyDGm/dCKQAJEHt93Cg==,type:str]
        username: ENC[AES256_GCM,data:clyyk/OF,iv:OQ6zNmDn0uqKqNKEqOHWY6VBuT/4/CHog7b0Pf0TAPM=,tag:Tvz7pzwsAtcOormi9rXPMg==,type:str]
        password: ENC[AES256_GCM,data:l/YMKF8YfhQERh5fTymbQHAdo5nwLuqQ9uMlk8aIgMXzlgRJoRRB9O5qjlPLy8moq9WAQga5CYcBOXlLkj034w==,iv:UFe/3H/AfTgSlJikHqE1IED3zINjDuOs5niXpGWXGYE=,tag:LSFCf2/w6sUy4v/TaQSJhw==,type:str]
    smtp:
        username: ENC[AES256_GCM,data:svJ9zytGrnm0juoBYg2+4w==,iv:wBXWtRYawOkjumsvTPcKfvL95CCB+RbsEyJv0YUG3WA=,tag:HTDlyGPaPRsrmIZpDi52xA==,type:str]
        password: ENC[AES256_GCM,data:t0djYYq9h2nowSsyVcgKjHNiaR6iD5pYYgLwsf250L/ZeghiqzDt9YMHEOhUM61xYtehINRjuNdhI0Qd2FSZ8A==,iv:ds8Bg9JSJdNHUXh0FvD5a4pquyRnIXowcsJcVV1TyB4=,tag:bdbnme26Sq496GfO2jdmdA==,type:str]
        relay: ENC[AES256_GCM,data:9/k8ONcFVVyrZW5yvNk=,iv:omnyn+Xa/cjqK+9l5bI573aR2p7UsUvqGX5ZQGf3CD0=,tag:mxI6Mte43e/Cbgeh0+MaPA==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:XIBNDAD4mIAc2xuzH9h8rRGqheGQrd/rYpUYGIL2tpPDwZ1vJdBcpT1HrYgETzdtxB8GXKXnQDiXf3iNRnGwFbSnBD3uQv+0zK9ZMCGYYzY0XwpL374JLJpt/Ck27gUXRwyH7RX5G6OzOCD+HJba2661VrFwVw==,iv:BbBjgsHh1pl904COKCMAh41uI7UH9kHcyy79zKYcM8E=,tag:Xpk3Hn3yLdbapb1m2Igpjg==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:1VVOhuECjOtKrcqsyHU=,iv:Jb7OeSnZ/+t9GU22nrPVQZJiybKInDQ6ffcg7jdkLGo=,tag:r7Qy/E5jv6ktrtNBg9EhfA==,type:str]
        security: ENC[AES256_GCM,data:/2baKnIOGl8=,iv:CTir/KO8cTDK0eDpa6dugYH694DLDcKG+ygRceaI7g0=,tag:JagkkBFP1Fs8yDh59c/KiQ==,type:str]
        port: ENC[AES256_GCM,data:R/zq,iv:g5aIKLKIB5++TI9se3a8DAm1TXBtFpraW7ZkuAUMT0Q=,tag:zaJaAqosQR5wZ4AMNefhnA==,type:str]
        username: ENC[AES256_GCM,data:p4HFD+rcg/9XRoIVN/6mwSSOrDYk8Hio,iv:5J73NP2SZQtvt3Uh3SemkEVLiQoPp2TpWGcgDbvVA7s=,tag:myCy6BOMePUWWtvaalnKvQ==,type:str]
        password: ENC[AES256_GCM,data:rFzyYh1T8aVELDfS/tMk74Yjmr/gogbnAd5cYy7Q2om3nOu1E4GVuH0FhCROxbSlRDvjWG0XqQHokHpSeQ2KlYcgSMN5EkfA7FOMHTjNnfU5xOilPFrEUg==,iv:M47gM1ZU+TgldQqP/PfogBFChDhyK5xckqtVRbAWzxQ=,tag:wtaOLWSv+gad9YUWg/K5RA==,type:str]
    database:
        username: ENC[AES256_GCM,data:dgL81N4CWkiFi0Y=,iv:qPVLau+h4t1SiD5PqwoHjSuCwG/ftH1x+eLhpN5g+nM=,tag:GGKdZLKrgo8LRMG53uEqZQ==,type:str]
        password: ENC[AES256_GCM,data:m/cN9iPqCbxK1AXOFYD96wyGmXk6d4QD2kvK10aJHkvDq8WSqXR7i9UpMdIEvxmSMPlqbaZXvoBccdxGNwoqE9whf00HPz65xnP89ShMgD60PMNYnDPVX/ItUYLlNpq3nGDDtYReoacTxR9zMoefGToMvpzynRroBUrhW88WIlY=,iv:yekf7PRi/bwpJ/bLrfSz8nxubJxs1ckJNBxfslnfvl4=,tag:lIDjQEY8MkO4ugk8QzvlTQ==,type:str]
    yubico:
        id: ENC[AES256_GCM,data:NzNSzso=,iv:I6YWEq8+lpSvVicgnTnXyobK/dLi/hwyYOGUu52q1hU=,tag:04Mhy+8biNJhqwWqZ8ntyA==,type:str]
        secret: ENC[AES256_GCM,data:cVSJ0NpzBtiCU15WxBRcYM3IMcCmqpYSX9xhmg==,iv:ovEwbuFtdnnYnr0qpmWrXM3AqmoUsPwe8nIW/4Mkn34=,tag:fbUk2bUA2iK4Zo7onri7lQ==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:S+r+IuCQrkTZ6fnUyAYD/w6JGRWV6Wvb/AokfHiWe1Z6qH+l,iv:kakIcF8ZUsdfeH65FfzsF0Vk5GotrDMmzWQF4IQRxhE=,tag:32J1Z0Dao4TKWLuEmkpFGA==,type:str]
        installation_key: ENC[AES256_GCM,data:P1X0ywcRSfZY9TVd0uQThmx7D2s=,iv:1jk1+5V278evEl/gU/aocOMgXUzAfbFVECG/sQC0s4k=,tag:0xcQ9rXOjDu+ss8YOQfmlA==,type:str]
forgejo:
    database:
        pass: ENC[AES256_GCM,data:PUgE3sdeqnn2cwSog9KfREL8xUeFEHC3yQk8gmpbEwkuLOoA5AGJoXskTSvYZLtTEOtVHMuOSDn5wmNpWxMRkHskBwwYSYp8OyKHcpvUpZsv4vdBTXYKtg==,iv:OTogoxwmalk4CiUlQstlER0JVN1YuVhWJgrhGJPYiuw=,tag:K/pIRn8I0Rihha+gTcZGJg==,type:str]
    turnstile:
        secret: ENC[AES256_GCM,data:0Q93ukPKRULpLIlJaplgM4M3UTTQjBsYjYFE9n7UssCwBVI=,iv:yMnxn15p5HYZSMOCBT30i3gpClyW/2fx8Ytx9sQKLSc=,tag:qI5FreB5hxaaDLFSXwCwsA==,type:str]
        sitekey: ENC[AES256_GCM,data:yvAHG5S08A64ihZekgJ/okSwSuhscLDK,iv:VaWMEu1QIh4LeauflFjJJgblLyOFkTpb4Db9wip6uY8=,tag:RLLo2lRNnssh4DWy6nNrZw==,type:str]
    mailing:
        host: ENC[AES256_GCM,data:1A9zkCHgs7Cq+LaXlYE=,iv:7ksEKqX8nXS4A6M1JH3+FPWoxAP6naB2huwJ7Yc816k=,tag:WTvDNf5YB95dPYq+oELytQ==,type:str]
        protocol: ENC[AES256_GCM,data:WAO5oAE=,iv:5ryKSzDHl1Vo375IqCnRr2TrcjJCvQgkdHHuIJ0Tk6w=,tag:ZK9v4p0xXR5rkouDXkLzUw==,type:str]
        from: ENC[AES256_GCM,data:aZL/E3N6/RIbNZFVkEuJhAzdCxxflghjK0L/H4QKb2asHtdn,iv:keQtnPpEdZpoHpWnIE/Dy67QTAWBhE1H1IGbtFOJMtY=,tag:/ji2tjboQuYUdpU99BAfGg==,type:str]
        user: ENC[AES256_GCM,data:MsUZ2YdryHggR5D+gT8x4T4EOvamdwKp,iv://IECba3A/MlXv4q0eCI1DXZFF/YxF/U1AHhCrGNd2s=,tag:ln6kFPIE7G/xT/EMc3vIbg==,type:str]
        pass: ENC[AES256_GCM,data:Y2d5YtHxQLIB6PRis1Butnkd0FowwNDbOhzqrV7jXZ6sfq6uMewsSk2bEiCsurJADkp/DKQfl1ohJjilTVfCBz11CWIvXX1+t2lFG70TRIGhMEt0dlIPAg==,iv:/4e5+aGW/HksRYXXrpbYZgCCWPYD0n2plb/+tNwu9hM=,tag:nuBYMevJhA/vZ/se1R3K3A==,type:str]
lego:
    cf_token: ENC[AES256_GCM,data:G0Br9/A0TZetWyym/M+JcimzXqLNVPzmc1hGXeJcGcqW/6cc3OSlRg==,iv:utJunj8wewHFdOaD+EOgpN5/RpXyCdsl5Lr6kBbXsvw=,tag:hrvRhBd3E9BuKSY+QPOCDw==,type:str]
grafana:
    oauth2:
        github:
            cid: ENC[AES256_GCM,data:HbHuXHvDAFwFzJT9TkcvScNADIE=,iv:K/WKrdiq9mXaFV33zYQYeYgia/54t6/qCseVGykW/yg=,tag:+oCuI9/1WCoPK6tR3noXRA==,type:str]
            cse: ENC[AES256_GCM,data:3AboBOas4KzJiF9pAbgCjl5Mm8utLCXR59K+kcFnnGPbpp/9stuicQ==,iv:iNbKhyUIuKtBUVHXdR36KWCueMjQuKIErl8P7intFX8=,tag:AHQfU+yKipJe7HhwI6/NVw==,type:str]
        gateway:
            cid: ENC[AES256_GCM,data:N0mo4Lg=,iv:F8A+gIGPUjziBTuBnhVS9kygzZYjnwFayL6Mx7LBwe4=,tag:ZtsQLsgkOC/qY0r1WoOh8g==,type:str]
            cse: ENC[AES256_GCM,data:4fwTPf2lxWyLmGviShJgHggGI3FIjdxJbQgvofnSTN0=,iv:1InLcW58sbz9wfp9VnONsqE+iDrhCWhlBBkr13KfN1s=,tag:3UeKs2RFiGyzSl/gYMUO0g==,type:str]
vmetrics:
    agent:
        akkoma: ENC[AES256_GCM,data:RAmDoGsAKqBCRXDT13HIJe1T8u8DnJ9Sh7Y1w/xYuvLuyoFFWz2gSFMuSQ==,iv:M5NrIERoQJohFqCRgP3TcwW0OspHMIbZR9x8G7jvI8c=,tag:uYqvHBbL9y186Y2vCevKwA==,type:str]
    auth:
        hosts:
            #ENC[AES256_GCM,data:Z+RgxBBPDMHMYzwW66vO3wZFEU0HP/cc6B0CJx3O6D6ANLZrNRwGIdeFno8LxK0=,iv:IeAZya/9R5fF4iqmmMzZ28J8hj9yYBPXnljsCVhN73U=,tag:U8jWVsbDqWsgszguPwXO4A==,type:comment]
            mail: ENC[AES256_GCM,data:39ViCc9DvpZp02AVso+89to78hD4p+VPh/OMFV1pB2Wgv+VHGdWdxo02y3Py9G3vtJkMf1tSHtV8W5w+QG5dyAYEpPvthIoCnfPgLkpBP0tMOUWSMp+CTgaVrzn7vqDVJazpDUv4lFj8nt9qdL6e+odrR+F2LuIyPQI3x4fKi+MRdRoE6mblYUa+9rgoThaSf/m2d86Opq5NaTQV1F1LEVeJHM00w2rlt6OWyA==,iv:Tm93jST/E4PkSlafzMWBfdOZj7g4J0dzBSeLrS8o4Ow=,tag:OLUbhqr8TV/pvOVAOuf1vw==,type:str]
            bocchi: ENC[AES256_GCM,data:MjGOyURWES8NwGWY32iypS1EDVOzfzBa7bq5Vs76Xann81eqf3fXYyNE3R+sD/rkJrwdpIImerT0/UvYjF/kWuZevRLwFor9/vR+Q1VXon9VlnW+VjgfdtT7G91KTUKSg1Iz4/nxCkGCqpTFUMJ7nUvLqGjujgBJijQ53rTwppNXzgA8EvrvCN7GiO0k/KHZ5YKgL/eTYaGCELkfREUsnwxYT7LB2uq5LhE/3Q==,iv:vhfxElYtouDM44cRzZwuZvJMncRN0Wt5uSfcSEFAuoM=,tag:sTbrQjRSd1hvHeL5YMxHEg==,type:str]
            satori: ENC[AES256_GCM,data:gqlXoxWV0uhZcSs6WXXTh2Lnf5R3eVAzubtmzZuXMAc93Ta8c3cl1UTTkqkduwIPLgkIaczRVoTIxv/osM/Brk2vXoleXK/rKdeKdpQ/BZGtdUYJWDCcfaPa0W5frurreBAbaOEEYSda6mX7f+AAOQ2xyzWyY3RpdYxCSUmn4NOuST8YNIOhYTgLH4ze1MVzTrdooRZGLy9xjOquvcjSZJm4JiukVPD5T0GRPA==,iv:6NhlTlShIUrtl5844NGWq5903liy7pbbsaa9z/OBxSQ=,tag:vanLDuZLt8VrxMBADHJwcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WUNGOUtqSWdkZGhxcUhB
            WDdId1dILzlGQURZdmdpOWhMZmtEODMzczBRCm9UWk1VdXJ0eWVqbzRXV0xCTXpM
            SjBXYWhEMmsxT0lyN0tXS0R3ajJPU3MKLS0tIE40SlhaVllndTg2N0s3ZlpaL0U0
            aHNMSWh4NFViaXVMaHcwTzh0UG9neG8KscyTPMFiFubFbDgP02ML33AT/BPy6Y9Q
            SdCOyTLonhr2YbZLhNEt3b6ty2DQ4b0XwRD6iQeI+PBEScGwNgHVCg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQksycFBnblpNejhuTFg5
            Y0llZ2xyWmloYVdaQk5qNzJmWlBYNFBSbTAwCk8rZzY4WnFGM1loQUg3SjBwbGYr
            QTA4Q0Y3Q0p4WmpKUUEwYmh1a3R2cHcKLS0tIE4rVWJzSCthSmNOTitKWGNwNnZi
            QWRlYVBONUxnS1NwbzRxRnVFTVBRMVkKCbdZl/qEG75IpcMDKe9z1zQ4y85Dsek3
            gkplnMO4KjD0QlL5aOLbfzo8bCmbP8WvKds3hK0amYu5zpyPwWfo7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18h7hya5terghrwawgpny28swlat2nqkdrfd4clk0svujqlz9xfusd3zeqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzendyQjVScGFXRHQvZVkz
            OVpraHFseUp1QnBvWnQzTzExN2NJMVBBNm5zClZoa3AwN2cxOXMxQzhLaFdCbUMy
            SmxvdmpMak5XY3lmWVJseHhXaGl0L1EKLS0tIHFtMHNKdGVxaGdyR1NGN0lhRlVN
            aTVmSnZXbWxOUzdKQTBvWTV5Q3FYNTAKyzzywFJ3z3V1japTvxvutsZd4+e4dfxE
            HbBelv4P6RJKauRmmLB/wGrUdr8Y8qHX+dsB5UBXLZNydKWOUQHHTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-08T07:28:43Z"
    mac: ENC[AES256_GCM,data:gVSVqlFxT1yIUGlRVfCJaYlIEfkdydvzkncnYmGoXun3ZHKMUxNrC+EaVZL+xmiY0RUUNfoAWEnmJhXmB5pnHye5ojvOTGzms6QMmLkaOaF82NI1giR8IWpSMamyycPI1Xh3XjsL9QovedfO3NbtGxL5/+U3hDV5QAiD84EsvzA=,iv:af5FrJwn3fLAvUwBkJPkR0BXo/xuTHxH0EaZTqCSNiI=,tag:8vgQGDfQxUw+yqblU3ptfg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
