synapse_comment_unencrypted: See https://github.com/Mic92/sops-nix/issues/120 for synapse.yaml quirks
synapse.yaml: ENC[AES256_GCM,data:e6J45oVlOiU2x6o4ZhbkA82yQsuTJ+SL92zQ6VbHrW0EmY+dfSgDrC93+wfpuqEpdbyXCbhjys1bf9HFXxig9Etn63T89OWlzaax7GQTF4SQ+EiEn3FDR/5hf7BDZY91u2sbMgVEnTzBD9QH/mpZIv2/cilUaCrN5hNffGWtfUf1t8kzakjCnjJfyAZeAiL979oOvBaghgRKt+psFCOKG7Ok2bx+QwrM3/v6JAOAre5WlBuiT755m8Zo96MgmkIelIkJOYvUgsZiQubxfGaUfspiLV4Dv2UF7SqjaqCINeA9vOotjKwKw+umfax/3oNTOryZZZ17M1GfTZjTdzz4zY/p2WP18rUsjxoAVIH318X007g8EM+oEPdNh/jH5BE9MvQyy2cZR2MItbmOdZ+OjD1/lfXcHmjUweFSXaWBCcMJAJqFPPwDQ0ftWEUVrKSQ0vEdXM0XrJoGY0zUnfagfcYEkpK3sZIE5H+oQC1IDOkZqOH1xf6qXCemuUrseUtBm0+VABgxUAtsnj7oK8ZWzt5xdgS3/wy6RA/Os0E0cGt/hbCjRrSN0OTCIf1Kpq9dYkJXoTncvdSvwE7DWSg3QmxI8/A67FSLWQgqU8jkpqFFR0CCohuWoPDeakTa/gwiMNlyxKjVXe5fxXZGKNXSKpMF6OfQANxW9ho7zKY6RzVy8xVLZ3gx0wcYQzbuu/OB8YTfQbqYJztfFBuc1e7vR/52X9JBBci+RAY6K7Rqd9qLqfklyEtsOQHfv+yxgbh+s6Hic8xR1ymXm512YAKNp0axEOr9FW3F2TclN/gix/DVP1PHWTREbvzAzS324jsLxCqshgD+8MRDheRtZmDlM38K2Zcc6HfhKj4i+dOE+VZ7QSIrQV/P6sUAjtorH29o2JgBgo/N8EMA33CdDCVeUjf8bYcl2v/O53+zdSoM4Z8S7tH9+iLisOQrxgDMADfIcrpmRM5lvlFMlsLVfBSHARXMhnOVOwjY,iv:fvaZQ66VKU+uzvn5AwTIFgzz+F2kJ8/QR2AfmynRfGU=,tag:Td7V7eT2olTCNFxTxvk5Eg==,type:str]
matrix-signing-key: ENC[AES256_GCM,data:svGjCGGkDJICDHEPmPPW9i3v6IiTSuiiaNABBnNE/bZmnxAyCateReZMYtg+7p21Y/kqdqbE9Yzh9g==,iv:abvwkrNe324QCbWLwiPY0UwqezS0wbyk2Fvi0vs3SI0=,tag:IYt41O6uPCkV/NnvnIP0/Q==,type:str]
matrix-sliding-sync:
    db_pass: ENC[AES256_GCM,data:EwpWM413g5Wo3gtoW83IttuyjjbGdffIEejoI5zKT3hZ1K3svsKRj6Ma83CoLgHvgYc1Ulm+Nkq21hSRcFWwHni2VSXoDIarvGUTEoMq/+96yEAl1hsdtw==,iv:fKdDDkfGhzCeSB/wBcz9YJwJ7pF7hYP8chAJ04GZRDk=,tag:0HJAyvf25klK8LW7m5VNog==,type:str]
akkoma:
    dist:
        cookie: ENC[AES256_GCM,data:/yBwOQXn7rHcO8odpI/NuRN/qL3hDVfNSS2DPK0cq00O6FbHMz8mg1/bioqhDB2bbo+Y9ZnUOosU5rjq4GAfIA==,iv:V8+MpX/IEc57zEfhNGX5f+eMyipraaXDKPDNDOy0Ieo=,tag:Shw430HSj3s5cHhR4ncMzQ==,type:str]
    endpoint:
        secret_base: ENC[AES256_GCM,data:Iim7OL+ieCE18/rYGiID/ZMV5VBvHrW+aoaebApPvyouJXPrha+31+WaCKQZh4gi1PvvNzKUEPm96t0S5ZLuXg==,iv:/x0ydo2gOPrhIZI7at877bzfFgMpraauozfLq95aHCk=,tag:JuHNKByiEdab+XiEp4kQeA==,type:str]
        salt: ENC[AES256_GCM,data:uiPKxK0wDEk=,iv:aSun7ABJdbDQrFcrGQMM9H1/7d5lJqeMwO08gUYrD2A=,tag:HnJfwxhu/Lx7g4EGWYu1rg==,type:str]
        live_view:
            salt: ENC[AES256_GCM,data:4584MDB3jDM=,iv:ZvWKutuMTOm2X8w8a0fOTq+ldrXemayIUY2PUcurY80=,tag:fD5j4xvmB76g8QFBEd2KMw==,type:str]
    joken_default_signer: ENC[AES256_GCM,data:55EskWyk4GTFa+H4iRdG9SZI9/KzaXfeWrsOQseeUBHjDz4xGF1A1uUz+hjTa4TiPEPoJ1VJNSer1EgPX3FCxQ==,iv:Yk1f/fzzbruW64mvTTeiyTlbrOO/G47CKKfr9BLtQ5g=,tag:YBbAezyx9OdDWi24n5pRbA==,type:str]
    search:
        meili:
            host_unencrypted: https://megumin.soopy.moe/
            key: ENC[AES256_GCM,data:Nu2cuyW7sAeobIxab7eIh2pHeDewoOxvPSwZuNvPr46QnWlmNTJoLkEfW9+ABC1fNVL0aaSQl8/bOKjMxcuyiw==,iv:t0kQUCmjhFw8Z2CTmYOPUNFvyiYfsXETU8GSxhRR5KE=,tag:VXk9OeuMckjcNMjNpB9FTQ==,type:str]
    vapid:
        pub: ENC[AES256_GCM,data:sYMzfmZrBvYil2GjkyjPd1g8LEJz4B1Ws+/3xwNJq271xMQaTv4FUrsMvwVlTYJXOQvDxOHS73A3NwkzEe3gtOrEZ9MCAm9FTbPo3hnKk7DnSL/gbJ9n,iv:154BP5EmBqnKyf9BND2laKV3caVxa34MCRzrsg6/dik=,tag:fqK55Dzhng5/hyhlHXA//g==,type:str]
        key: ENC[AES256_GCM,data:5NLECsTsGx8u7riLjQNk0YRJY6+zO0d57H/BbXZdVQMHnBb335ZoFCkjUA==,iv:yQLu5CFl73GCojMBa2II6OhLrNNinsiVG1aPOAx+HtM=,tag:C93OV7dXgg+Q/6LkC4VLjw==,type:str]
    postgres:
        hostname: ENC[AES256_GCM,data:HCrwv03Iqhxa,iv:GM2SH4Gkvt8tLG8AYIKxfHTZvB1sT+hgIoqkiViH6Es=,tag:8HuayLqy2GJRkQQLsfH5gw==,type:str]
        username: ENC[AES256_GCM,data:d89tc/fb,iv:OQ6zNmDn0uqKqNKEqOHWY6VBuT/4/CHog7b0Pf0TAPM=,tag:AOvB8mA/uT//W9fhFcWHKg==,type:str]
        password: ENC[AES256_GCM,data:nPHWL+a3t86Ept/ww/kJdCmh2Zt5SW8SfNtiSXZoXloXt92oyLLfWi29kyiGArqjtbvn3VxBeHd3qGBUPkGw9g==,iv:UFe/3H/AfTgSlJikHqE1IED3zINjDuOs5niXpGWXGYE=,tag:CIE76gtbfcs7ZgjAWoAF1A==,type:str]
    smtp:
        username: ENC[AES256_GCM,data:zlhIPPUlgYpfc7RyyxUTAA==,iv:wBXWtRYawOkjumsvTPcKfvL95CCB+RbsEyJv0YUG3WA=,tag:/7Ge+waert8tH+0J8j3ZIw==,type:str]
        password: ENC[AES256_GCM,data:Ct7liQEzp9bjKM5ZI6sRzid9p0w2LJmUs8VDmAmvQe6GclpO+JHJyUgcgq7UBGcbKAU6U7rO5naeG2iPV+tPjg==,iv:ds8Bg9JSJdNHUXh0FvD5a4pquyRnIXowcsJcVV1TyB4=,tag:1eem6EV2WpJVlZY0EjDchg==,type:str]
        relay: ENC[AES256_GCM,data:g9pMlO8JwCor/wXySTY=,iv:omnyn+Xa/cjqK+9l5bI573aR2p7UsUvqGX5ZQGf3CD0=,tag:HvFcGMXgBSc/cySsckxg2A==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:ZDd3P4VhFHU9e3aSgFjkH2adVbCBBoypEVJMQ7I4Rut0b4haV9VRzwdR89iMteRbqqhh6iMK0G2pR1yXQZg1hpW0Tn8lLRh6SUehMeKtledfPy0OlhtU80B9YUCbSldrvndahXfUmGpspjqZd6N7aeY04d2RQQ==,iv:BbBjgsHh1pl904COKCMAh41uI7UH9kHcyy79zKYcM8E=,tag:B7Fl7QZflSI7cAN/SvjTFA==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:qHEuAkDmUtBkALo4uR8=,iv:Jb7OeSnZ/+t9GU22nrPVQZJiybKInDQ6ffcg7jdkLGo=,tag:H9jVhnk9DqZ2fFskJA0tbQ==,type:str]
        security: ENC[AES256_GCM,data:2OHMfxFtA5c=,iv:CTir/KO8cTDK0eDpa6dugYH694DLDcKG+ygRceaI7g0=,tag:iEV2HYyNjTXnva/yTIygMg==,type:str]
        port: ENC[AES256_GCM,data:pxwu,iv:g5aIKLKIB5++TI9se3a8DAm1TXBtFpraW7ZkuAUMT0Q=,tag:qbmwYC4QNzRmD6PGWQmxjw==,type:str]
        username: ENC[AES256_GCM,data:0aOyd6mO2tx0rBHdcMKdO81qpXIisp6g,iv:5J73NP2SZQtvt3Uh3SemkEVLiQoPp2TpWGcgDbvVA7s=,tag:rPgq3qRtRe455OF31gza5g==,type:str]
        password: ENC[AES256_GCM,data:cP62SZAfh02mtMbK2u2YRLPSWgf/jA70lB8/a792VU2/N2lGEYUHZIK1S2iU2H9O4yETt8lR3NSuaFsFf9hU7kdKvSzelg/SOK6NMiLMADHvPoKNaSPS/A==,iv:M47gM1ZU+TgldQqP/PfogBFChDhyK5xckqtVRbAWzxQ=,tag:HGACLtrxvkflXVw5G5vlrg==,type:str]
    database:
        username: ENC[AES256_GCM,data:HJp4WD77aF93RpU=,iv:qPVLau+h4t1SiD5PqwoHjSuCwG/ftH1x+eLhpN5g+nM=,tag:bcJ+GPi1e+29o6HG+whnaA==,type:str]
        password: ENC[AES256_GCM,data:ngyieTmdZp0FdXZE1EPRRcVJSUs/27Fggoydx/zTS1cTbKGC9eBN5SWeIacE1Pov8fEIlUQnmfZkRJh7VUz1jer39dytKuu5AmvqszfBJonb5PIpKiUK78zUuOFR6WiyhFuIhBb7iupKhZEI+aOIY98UjLvvEbto6CAZ7b+67GU=,iv:yekf7PRi/bwpJ/bLrfSz8nxubJxs1ckJNBxfslnfvl4=,tag:eoalwN8P46munrhE5dkspg==,type:str]
    yubico:
        id: ENC[AES256_GCM,data:QjhCXIY=,iv:I6YWEq8+lpSvVicgnTnXyobK/dLi/hwyYOGUu52q1hU=,tag:HoZnR15UQQ/BhxFBup/5oA==,type:str]
        secret: ENC[AES256_GCM,data:BGrLNC1NQvFj/5gk6/S+tH/1fMTEbakp/ZIbCQ==,iv:ovEwbuFtdnnYnr0qpmWrXM3AqmoUsPwe8nIW/4Mkn34=,tag:zhMTNCpU+raOk73AojV5bQ==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:U1eNWyaK3O3bO3LxFotOPcIcAhTbP6fAlo+nkrEypFaGwBuv,iv:kakIcF8ZUsdfeH65FfzsF0Vk5GotrDMmzWQF4IQRxhE=,tag:RchSGlct0Y9523UFx0eZFw==,type:str]
        installation_key: ENC[AES256_GCM,data:eaYulEMBgCM7020RFufkYUXAhSI=,iv:1jk1+5V278evEl/gU/aocOMgXUzAfbFVECG/sQC0s4k=,tag:8sE1NGTqPemag/PNvF43/Q==,type:str]
forgejo:
    database:
        pass: ENC[AES256_GCM,data:/+/sJQpl/hv5qt/MwGYQGkVyM7Jk2HOkSEwRx0FS5grfIU1ry8b4EaOLz4k+tMZiP2EKAn3HrkpNrwtbvqh6V/NQ6c6fayhi0uAuCmT9NicaZfboB6beBg==,iv:OTogoxwmalk4CiUlQstlER0JVN1YuVhWJgrhGJPYiuw=,tag:A9RYYxYvK7kUbNpeiTto9A==,type:str]
    turnstile:
        secret: ENC[AES256_GCM,data:6fMyn/JdulsLF5QHvQVPABHUMsmdgKagzjdAaLwY83f+6io=,iv:yMnxn15p5HYZSMOCBT30i3gpClyW/2fx8Ytx9sQKLSc=,tag:HGXlW/vhC1n9yRisp2eP5Q==,type:str]
        sitekey: ENC[AES256_GCM,data:xtt6u9pQ/ohSAJzPrMshZIaEI9CyoEU2,iv:VaWMEu1QIh4LeauflFjJJgblLyOFkTpb4Db9wip6uY8=,tag:Eai1mDxtPMTLCcGoM0uAnQ==,type:str]
    mailing:
        host: ENC[AES256_GCM,data:BAJZVDwuopnQunok0/Q=,iv:7ksEKqX8nXS4A6M1JH3+FPWoxAP6naB2huwJ7Yc816k=,tag:4NHq9W6uPM2lOj/9nLO2eQ==,type:str]
        protocol: ENC[AES256_GCM,data:gnZbEWk=,iv:5ryKSzDHl1Vo375IqCnRr2TrcjJCvQgkdHHuIJ0Tk6w=,tag:NOJZt05IsnqjEAOTaSea9A==,type:str]
        from: ENC[AES256_GCM,data:b+vH/r6rLPAKwBUyy87EEOB+j5wI899j9ySlKsNoJFuY+07/,iv:keQtnPpEdZpoHpWnIE/Dy67QTAWBhE1H1IGbtFOJMtY=,tag:uT42o9r5oPdRZnWcT7w+Gw==,type:str]
        user: ENC[AES256_GCM,data:AkQbGyjYdXIyYrl7apCcWJIZ7On2Hxko,iv://IECba3A/MlXv4q0eCI1DXZFF/YxF/U1AHhCrGNd2s=,tag:Q7vJfDCg1tysdJ6K3mlvqg==,type:str]
        pass: ENC[AES256_GCM,data:f3ZOH5Q1YVJPUONSdfnfrsX4ubo5xqE68FVGc5ml2IBnul4Qwmr/OtBB+i4jxIif9DkOk5prdaOJ7Xr4ettSy67Rv9o7erLDXXhRbVc83LqeyTMXnh+Y4g==,iv:/4e5+aGW/HksRYXXrpbYZgCCWPYD0n2plb/+tNwu9hM=,tag:mnVQ3xq0n9So8Y3XL559xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rkyshu0lswdqyvun4cs9cekm9zt4fw5c8ssa38tn3lukgcahcvsltnqx2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc3g1MEFsRktWQ1dEblVw
            MnlxMWNQUGcwVE9aRDFjY1FYcVJxTkZrSFJRCkdVamdNSG5OSGNXT0c3RTI2R2lL
            Ulo1ait3cmJJUUlEUWNIdU05bHpEejQKLS0tIHAvWWFTNlFyZVRRREV3bzF4YnNJ
            aldZU0pmY0hYNU9SelBHQk4vZGFYWkkKi52h02P7VlHCMWtCXlBq4J5lNc/TOimu
            h3u41ReooVc+idyzaDe9q08mTwFsRirVuBeEaEvDUPpJywHKVDOEng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18h7hya5terghrwawgpny28swlat2nqkdrfd4clk0svujqlz9xfusd3zeqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUUk1VDM1cVc2WFM4em95
            RmJHQXF1eVZLRXI4OU16UVplVE50akFUbVdZCnNyS1d5S2NNNDZXdW94RytJZFhN
            SnlRNzdhQVhmVUVLUWhBaUcvUWE3RGMKLS0tIGJsRVhNRU10WlEzMmVZektZcUdU
            ZXlPN0E4emFjZlhBck1UUnBSUnlGeE0KwY5zdaIAXYs/3Q4elSbnP9yY5Y0yVQEl
            xcd+WYTLCpKAwQ2zUpAbmnMVqZKfkCTlcGnEPuU3pdX7cFGWeZeHBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T05:32:41Z"
    mac: ENC[AES256_GCM,data:DXVjj+8RaitRNro7XQrmdo07kHrP1PQrbN2l7LKOONw4FmaHBmJ/gp1JvG2FULZ8BjbjR3gB2u5OjR+LEDayXVpRnXpJZcB14NA1KYIUp3B0QnVqYskv1TprN3NxGDUO8LWai/+bWF+Ji7e8RINE9jMAad/KuTOwHyQbXSceylg=,iv:b5wMyB/6ZN6H3J5/5O4vTRJnkMOLcUrbrdoCvPPWSDk=,tag:sVsSZmKAg0jq7M8YpPkMkQ==,type:str]
    pgp:
        - created_at: "2023-09-08T14:11:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DAAAAAAAAAAASAQdA6EGBehNCunpCu78zaFedRtTHT5G02mAXEbVUnzR4ryEw
            za5MfYupg+OYTCfoOd5jLKIza6tFNPj87mSXenwhBu5L2GWF5/YGywcS/DnBZ5JT
            0l4BseUtbldS2fw7j2u430aQqIYTkXXugIA8ZH9WRdw/QYhnL+BeFcnGsl1O+jby
            W9togm/4d/M0FGv8VRj517hRg3vpobh/fWAeoIVW/4KX5sBg/fp+C53GbNFXm1y8
            =K+iu
            -----END PGP MESSAGE-----
          fp: 8F3B277901484C6EA7E63F82D539637D518022C6
    unencrypted_suffix: _unencrypted
    version: 3.8.1
