synapse_comment_unencrypted: See https://github.com/Mic92/sops-nix/issues/120 for synapse.yaml quirks
synapse.yaml: ENC[AES256_GCM,data:12wcTRG8Fft/VWcZT8avtHVLK/uTkD5QWmkYwgydG8yrq7/S1eHpPYdktdQ2rmd2ZXT+PKRnYJCsfo4q2KnewVKqd8MX5o62h7OqQXEhabCzLOU8tUFolRK1v0Bs1+zm6Igc+8IpvRkQHGFbuG3t9qp6XXZAslkCa6sceorJJQwxHP1ojCHaTmFybemFioEyvrpx9pGcgqO0+Hx94AJ4mGfskA0UZsQHfVVzGo73FNoMHfFr5GrlQjkOQkEzD+gEADxN3kv/F47HquUxrvcdmVL6PnKm7pE5twTZe2wnI1zO2XUA8QkUCHVUJ0zTKcdjspJpMN72A6tcSegK6lukajU7C5q9DLps7qbmHFXNBNErz0HZUTbhHAkLQeyBgBA9jHpomPZV1D2WxsjXL6yRdP9aWl9jKK8MSfCApB5oglsmm3kTFH0J3YUZObNwt5NygCGMpohbsyg4IjkNoCrfbhVRcnX1o6nqGgHFKZfEQdX1S+u7I+Aj3qoDSpUHsA99FYdaQvCo6Z6B9c6MXpgK1aI63pNOKbN77vS3B/k8nmYwxdZ+qT26aCXy2hCUraCvOuTsUKITTaTHqcAxP4lhTxTqPmjJqckJjgHDn81eyqqdM4ahcWKd7INQFDjIZqzpdwup57TuhELk070QmQSyXMv4m82w0uQJW/vTdKweUIOE01BuerwgteIvx25UCWqqN1duhlZDqnDpXZwOAh2K9Ltj+2fNVymwMv+I6FuZ/YiEcOLRgL6DXF6KBGn69bvsUOklr5XJArkLWEkPrVzqCmoe0FxBYMil5hLBxgTldNRMcs/fZLV4VKQXfL3P0RxAJn09JspQ9vQhWJQ7LVmgVV+ij6jGmbDt+G6jKQOhm/XLaxyH4q/KR24e+saf3k7Ts7mAYjbEZ6ljFO7CNDXKgQCp2ukASM+3IAhaYKSww9IuUOA63hcXl67A+0RhhOkik7EVkvThWmSQgmlVxa4z2d7fOs7U5GnZ,iv:fvaZQ66VKU+uzvn5AwTIFgzz+F2kJ8/QR2AfmynRfGU=,tag:JcnAf6GwSzhqNcFB6wpD8A==,type:str]
matrix-signing-key: ENC[AES256_GCM,data:ubV3SClvUlRob94xyMozP21Avyo3zUHeLdeIvqE7xX4uUUfKOqizBfB+mY04mMI0N/fAbD0IU+NVgA==,iv:abvwkrNe324QCbWLwiPY0UwqezS0wbyk2Fvi0vs3SI0=,tag:V+VStxZGh/ivA64lLKityg==,type:str]
akkoma:
    dist:
        cookie: ENC[AES256_GCM,data:BcJ/F4Y+TVEl2LjXeU1WbUBTMfGnNuD9d83PPzCYjLPkzVBuDFQQvFqiq0WCjpIfBnvh6jgFSjyCKHXYEVDICg==,iv:V8+MpX/IEc57zEfhNGX5f+eMyipraaXDKPDNDOy0Ieo=,tag:Oj0kKNlgmDbVxj4ezeC89w==,type:str]
    endpoint:
        secret_base: ENC[AES256_GCM,data:qGogO5Bhhy4MCJTnSNt9vheyf+OWWgblcc/ZHRRZ22wcfkJDyKJmmN4ps3709yJedSBHh1hizfxXaSzLsExDFA==,iv:/x0ydo2gOPrhIZI7at877bzfFgMpraauozfLq95aHCk=,tag:7naVAH2nSmcwjspDnW0kxQ==,type:str]
        salt: ENC[AES256_GCM,data:l5VDHa9j2IA=,iv:aSun7ABJdbDQrFcrGQMM9H1/7d5lJqeMwO08gUYrD2A=,tag:sysUR4YYa1Ss8yyzN4iHmQ==,type:str]
        live_view:
            salt: ENC[AES256_GCM,data:F/Lqr/GRGIc=,iv:ZvWKutuMTOm2X8w8a0fOTq+ldrXemayIUY2PUcurY80=,tag:kYkbO8GwXNGclRmaWNdITw==,type:str]
    joken_default_signer: ENC[AES256_GCM,data:8futevSLc495EUzR+j294wpF2ISHWY/dIhvesmeUANsPAqJvPNJAtkBZWceeLhoW3W7M04eBAD19oW2be/+pdA==,iv:Yk1f/fzzbruW64mvTTeiyTlbrOO/G47CKKfr9BLtQ5g=,tag:pVnJe328ed87TdldcuFZ7w==,type:str]
    search:
        meili:
            host_unencrypted: https://megumin.soopy.moe/
            key: ENC[AES256_GCM,data:HItwNfcvWBo/hAFigAoMQQKnnxn81j3k6xQQ210MTEiQefSX7d5GnYHJUUM9Vt8WnEOk/z61zu0VUvYbgbir6g==,iv:t0kQUCmjhFw8Z2CTmYOPUNFvyiYfsXETU8GSxhRR5KE=,tag:6L0Duoc2orT6lzLdamfy8Q==,type:str]
    vapid:
        pub: ENC[AES256_GCM,data:bs2Cf4LwaA+8ZgDN1G7VYPApDTWN+KZHF++8evqzloWOfbsNXNg3n7oypXRZClNHnuXMNqGbCJdLqe90BR2MF0vvwYmiaMWwjVHBnypPRHpVK4PnCI/5,iv:154BP5EmBqnKyf9BND2laKV3caVxa34MCRzrsg6/dik=,tag:OBCRTv3iebXyrEu9twCB3A==,type:str]
        key: ENC[AES256_GCM,data:D++oBrVThaWvW6M6lciHpl23R+Ilj9BcK57tgReLYvORASQ9xz9OY6jnnQ==,iv:yQLu5CFl73GCojMBa2II6OhLrNNinsiVG1aPOAx+HtM=,tag:e3cHqtcr2xCS7isZ16mT5A==,type:str]
    postgres:
        hostname: ENC[AES256_GCM,data:61ZZBxID6zEE,iv:GM2SH4Gkvt8tLG8AYIKxfHTZvB1sT+hgIoqkiViH6Es=,tag:0qffLxUYKiwS/+fQrb7/yw==,type:str]
        username: ENC[AES256_GCM,data:e8+lOdkh,iv:OQ6zNmDn0uqKqNKEqOHWY6VBuT/4/CHog7b0Pf0TAPM=,tag:saQ1jPknlhH1LCps72M98g==,type:str]
        password: ENC[AES256_GCM,data:8O+++UVW7gn3VFauIbkQAtmdcem4wDsEMxVheyKC8MPHS4kR3WV9qBv2UnS4ocGz7gLnsFob5QLGeO0olyrLwg==,iv:UFe/3H/AfTgSlJikHqE1IED3zINjDuOs5niXpGWXGYE=,tag:Bfi7VHCqacs0iH98HNSfIA==,type:str]
    smtp:
        username: ENC[AES256_GCM,data:Chxw2t7bmrAaCfPx0V7Gyw==,iv:wBXWtRYawOkjumsvTPcKfvL95CCB+RbsEyJv0YUG3WA=,tag:htsCy5qG4Mv9zBDopdcrVg==,type:str]
        password: ENC[AES256_GCM,data:HTUMTtdB1ElD3iKlaTA7J/NBxqgG/2eVAWzLbviI9Zbjj8RguWU7CjDems6SdFn2nGS8ZdQFwkS1paNlUzdASA==,iv:ds8Bg9JSJdNHUXh0FvD5a4pquyRnIXowcsJcVV1TyB4=,tag:uPWzqlutQbKA1De+BSzrVQ==,type:str]
        relay: ENC[AES256_GCM,data:CLRj1Yp2z4ftiHpnDdc=,iv:omnyn+Xa/cjqK+9l5bI573aR2p7UsUvqGX5ZQGf3CD0=,tag:fH9Bo2pUJIlZ2JVL6hmYSw==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:ynsW0nBwdxpskMzhOSS14o0i0twmFr6Amc2D9FBMI+HPQ3emlYHDnDtA4WCCNiTKd4sWaRZXo4zbtWsfKWuPVZfIBQpGF8N2c4ggQ/lJbB8Ei/DhQE6qmgejULDSVr/hibvV5wtEClHfbuFMTCo7Hx1HYERjtQ==,iv:BbBjgsHh1pl904COKCMAh41uI7UH9kHcyy79zKYcM8E=,tag:v2hEBNJjLu8vNbQWKza8Ug==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:oRH8P35j+d2eP7CQzyU=,iv:Jb7OeSnZ/+t9GU22nrPVQZJiybKInDQ6ffcg7jdkLGo=,tag:llt1/4LRpKcM8rpElH6nWg==,type:str]
        security: ENC[AES256_GCM,data:lvhzJSNay2I=,iv:CTir/KO8cTDK0eDpa6dugYH694DLDcKG+ygRceaI7g0=,tag:T4/oTAV2vuD6QZbgmxAOfQ==,type:str]
        port: ENC[AES256_GCM,data:3dtB,iv:g5aIKLKIB5++TI9se3a8DAm1TXBtFpraW7ZkuAUMT0Q=,tag:jzvp7HwniDDYNFv5YgCVJA==,type:str]
        username: ENC[AES256_GCM,data:P42PyU20I1uN9uJUTnR/BNyQMU2CSO6b,iv:5J73NP2SZQtvt3Uh3SemkEVLiQoPp2TpWGcgDbvVA7s=,tag:K+kwuumWxeQOQFZdVrCvSw==,type:str]
        password: ENC[AES256_GCM,data:9KSivlRfLq90srkwZp+4eXagzv0YrLGLspmrveBtoP7c+R+oB6mJATVzqMfR4B3gi3gRr2ax/lntfUWZvw6YyEVQV8HMpGk2+CyLaKcMJP9UE3qKA1N8QQ==,iv:M47gM1ZU+TgldQqP/PfogBFChDhyK5xckqtVRbAWzxQ=,tag:LbYUiPVRRT+EHwLRWdo2Lw==,type:str]
    database:
        username: ENC[AES256_GCM,data:3dXxpFBWzRUzXmU=,iv:qPVLau+h4t1SiD5PqwoHjSuCwG/ftH1x+eLhpN5g+nM=,tag:eOZhLZOAbWYwKA4KtJoLFw==,type:str]
        password: ENC[AES256_GCM,data:IjeXR+XNg1aHzmOCDOyGi3f7B7CiCu625dyC3hgE3crWo/tfUEmPuMvLVt+0T4wiTI1wyJJ+lzXeIewyGJOg3jNtzCxRYLY5eSgBilcZjcBfMIYo6+w92jyzSpKufcABXHnU0vSLSCcfs99KVMNOLAuKLum2Pj2AOGq7LhjNwt8=,iv:yekf7PRi/bwpJ/bLrfSz8nxubJxs1ckJNBxfslnfvl4=,tag:IbMyDN+dvQmJKUDkFmPQTQ==,type:str]
    yubico:
        id: ENC[AES256_GCM,data:xrUeld4=,iv:I6YWEq8+lpSvVicgnTnXyobK/dLi/hwyYOGUu52q1hU=,tag:4StnnxfY+3xr0UNwzkM2kA==,type:str]
        secret: ENC[AES256_GCM,data:OEWSX1XXKxe1RI5JD9rybwQfsU4Pvmj7bHqgfw==,iv:ovEwbuFtdnnYnr0qpmWrXM3AqmoUsPwe8nIW/4Mkn34=,tag:ydwF7Dpc70WLSif3d+O83g==,type:str]
forgejo:
    database:
        pass: ENC[AES256_GCM,data:mxBBC+crHEgtJsqeaobTzOqX6fZxjAMbLR8v5WbL5wdPpZ/3Ji1axN0eej5QA+x6eIh3CrD48MQV2FKX2b3oivzANZTqhreXQCywN9qlHq78CSPHv1rL+g==,iv:OTogoxwmalk4CiUlQstlER0JVN1YuVhWJgrhGJPYiuw=,tag:74jMLEQVJ7wUWR+7giNU/w==,type:str]
    turnstile:
        secret: ENC[AES256_GCM,data:2lxhEWoUqO90PDN2hQkl1B6ennRaT6XkqOS7BqQXUE1Qmxw=,iv:yMnxn15p5HYZSMOCBT30i3gpClyW/2fx8Ytx9sQKLSc=,tag:3PUZ8o3bPcG7/qtTV72NAg==,type:str]
        sitekey: ENC[AES256_GCM,data:ZNEojJgK2HNMHpIpfO2tO5NQlmnlnHNy,iv:VaWMEu1QIh4LeauflFjJJgblLyOFkTpb4Db9wip6uY8=,tag:buKU4/BWdDyOmVBR/I54+Q==,type:str]
    mailing:
        host: ENC[AES256_GCM,data:7gAxUaPdL0Dg5S8LKdTyPsVd,iv:7IhNOfWIKGOjDPBesOYRu5md3almqiU8B3f16ldoIdY=,tag:+GL3s+wkqstNOCPefRG4BQ==,type:str]
        from: ENC[AES256_GCM,data:OcBv7yPXL5rPNE6YMbZeGakaLofaFfxayRah6RUmVPYksD3F,iv:keQtnPpEdZpoHpWnIE/Dy67QTAWBhE1H1IGbtFOJMtY=,tag:J8ryCU3oTvw5ICLR4nKytg==,type:str]
        user: ENC[AES256_GCM,data:oUsb5aMOEwN9N7WrgG5UNmvnF6yfbGrz,iv://IECba3A/MlXv4q0eCI1DXZFF/YxF/U1AHhCrGNd2s=,tag:wkiCW7mNKuf/X0UAmCikgA==,type:str]
        pass: ENC[AES256_GCM,data:ItzmYDtkeCcokwN4al+NyghslM3kGCMpn9z0/B4B1/6bNI6ZOCkWp3XTuYf5tORpefrbnbaEI6FXawILp6q4xzTkjy/G25m//hU9VpTdDse/gwBcTtzuDQ==,iv:/4e5+aGW/HksRYXXrpbYZgCCWPYD0n2plb/+tNwu9hM=,tag:FxukvuuDgl9Gh4wgqyrgIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rkyshu0lswdqyvun4cs9cekm9zt4fw5c8ssa38tn3lukgcahcvsltnqx2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dXExUlBsait2NVNGVzFY
            RXd3b2FueDJQaDhGcVE0K0MyaVZXdFpkZDJRCkNiYjdxUSsvZ1NjVEJiQzE5TnR1
            ckZSY1FhWlBQaU95bVJVakxxc25zdGcKLS0tIHRBN3o2QnExUGhvdkRZakwyUjN2
            NUNPZ1hoMDgvcFRaSG9xR2xXbVdadEkKnq/5UzE++LWwwHrQKWR7X4RNFSsfUMzg
            EoIrWCR2itzsN6rf+yVknihwv1ZRw9ir58uQs8ZHzxW803IaCv0oIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18h7hya5terghrwawgpny28swlat2nqkdrfd4clk0svujqlz9xfusd3zeqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc1l2OHJFajRtb1VPVER2
            QUJxYUk0eTlyUHVPRkxlU20zaVNzbG9Uamx3CndRZU01amhWZDltTHdXODAwT3Zr
            WXIwUFU0VVRCMWFrZ1o3am44aXd3Mk0KLS0tIFV5QVVmNlVVMktwM3hSZGlLQ1RR
            ZmVQUDRueUgyNU1SWTQwekFHeGlpRmsKA0Mi9P92C9AO1R+5xAr1s+w8d9A4UYwn
            UlOYfS6NT+PYiYfFTvSXlzM6uKMqv4NpR+3eUNYlcc/DDGvgpajgrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T08:47:33Z"
    mac: ENC[AES256_GCM,data:Aa+v4jGt2gQBnnIu/Iz37mNT+JXZOCMfo/MDy009OOojSLviNton/nrtRCYCWpJwmtKZ78JiBuBteIb1mWsZgpnsr2MRDiXtE0bFwDZ0bX1IusM+wY+poUK0D+aGPCA+RdGzQ1mr6LUgiSnpnHq2DYJARMjc1qhCSCtv8zWMPxM=,iv:gwnCTrbDESnjNPv5sdzCitk+bcHPdL0TZ7R/doFK6b4=,tag:/e9PQC1UN3J1HXKzVubX9w==,type:str]
    pgp:
        - created_at: "2023-09-08T14:11:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DAxCcDC4ukRQSAQdAgOr/Tix+mwVfr43bBOWUUUGUtymX8SYqHHgNw/n1Fl0w
            0pqDtMKi5cJHhrm/Ec6Qn0Q2WQTQFoTTNi6qMY7M9oJ23Im2uNyZycnM9siaTEMy
            0lEB5PCeLfHjbKERapoGcl7xJNxtcPl4laPKO4A3m0GIsi5BAlrB7xz+3fHbOWEU
            0O4/GwDcgXAuCNrwbqTi4Y7oMGpcjvnlBF4B2JLG2h7/QDA=
            =Gw1/
            -----END PGP MESSAGE-----
          fp: 8F3B277901484C6EA7E63F82D539637D518022C6
    unencrypted_suffix: _unencrypted
    version: 3.7.3
