synapse_comment_unencrypted: See https://github.com/Mic92/sops-nix/issues/120 for synapse.yaml quirks
synapse.yaml: ENC[AES256_GCM,data:/QRcVcX5DGbxIIgRB2MLOrkGkbJgLoyj9tmA8Gc3MIoH/Spb2KCfrOo6uzRqnFV2vFrW9Q00FTMT/9XFabqNbeacghkh6jib/1Nqd1a6+4Y+pSO6SryZxnvdZJzTnbtF0AlW+dClTH8qpe0j3snUdNq1RNsK+slwmZR2ru20mRNqQoZRHZepbmM4Pyyw+/462q1qurXpY931qz+kicRwQj/1BR8d32doFvV29zorX9k0AEtq7VnlJeEEKPhdc4GM9q2Hr13JOxxSGEPPFAZiAMa0XpeMb8dFzG8plL8LFYnF+BXzMs6GHRg/oTeXPuDnGU6PAkPtq0de567iRZ6OOlUJK3ZqK3jFOIr8ss3/WBSbOgsYbp9BxcwZRg8RgtuO5ZzfFliwwLTN5QT2sUsWKscsyL4mHKtxy6+bUf8lVY8w70cPIZdSQNnb7ZP0GGm04Iyei6uY3RbhEv2Epu006V20nZoDVMVoiGI/76qrTn/VoVXOxWsdYc8C+vFDS9MfmJxanKXt9x90KK0kKcExwdqj+yOWqF1AhzCPWXCndmcT4MjlF1c1FaZvpO3BJ/sGcSuh41/dVUOH0Dz41fzq4lcVSVTgJL+T5Jy/pDqrClOvQRMNa1FjDXFrRG84g1SdCUB6ob7ljqFIDen72yaBn5XKMPXDwO+gYpl+LdVh+h3b1QmMJNIXo0tsqvvD5JvFjwPBjd5nJpMwaFrkVIMCxr5Km9gC/ooImKzpyFQGH59fTI0SpMXmCs3PFkzz7TVIiRp9lfU+Dur73qMKBegURm+Ud0fpFjJWoswRVje0ZTKZqtm2pNt8NpBPF4yc21+Sd3O2wPh8KUqZrwHGcB8ABBNSbkaXe5jKIsZ/gi0eN8d3749nWExaAzxMq3eap8o35crw9gf0ZeuUm035X7MaLm3Rr8e1Qc1Pa6y0LME0HmUcYxsvvaOr57SLwiQFmmYbMuMu1qmkGFZQbHrMybmxy/SLoa/UoD7c,iv:fvaZQ66VKU+uzvn5AwTIFgzz+F2kJ8/QR2AfmynRfGU=,tag:hx69XAEtDSLg7g/ASeVF1w==,type:str]
matrix-signing-key: ENC[AES256_GCM,data:oYE7ooK/kKKVirYcUYRXc3lpyEOkC6Gk5xLqvbiaMTgLFemzdZFFp3oFhmqIV/wDOfhL2c/ChmuHug==,iv:abvwkrNe324QCbWLwiPY0UwqezS0wbyk2Fvi0vs3SI0=,tag:MiDcl5gbrZrXJVYnxtL5bw==,type:str]
matrix-sliding-sync:
    secret: ENC[AES256_GCM,data:cmCFoFBnFSlXDkXr6oceshB/UTmbfmf2r3j/v3ewe6dboC56FMGMLVRYOTh+nu/syKbC75NlpoALZR1DY30xK7DUSrhO1/r+Wc/z/CgyG9Rz+5gYx4BPgS0p3AsSNvlY6J4j+661CmdelKL4bVr+ZSep6pypfkH9VAy0LjXJ1hDPPMml1Pp2Gw23dh/eazjb/ECZ9Ne9xUWca+0u+/Y3TCI1zKkqfKVzYibhbpzYOy0ot7nceJoujopcLaoobX5CafPH5EHxLYTP3h6mnRjJq2TIQswDeBjkpHkVhFrVHPTN4eZFk/R1AqWUSfB/6PbS+f8nuGq1SWiP7m9JRhW+Qw==,iv:JR9Hz+rmfGeJ+JfDugkI7bzh3wb/o/5CdrzKPXfVTL8=,tag:SZSFWZLxTplud9L0sustFA==,type:str]
    db_pass: ENC[AES256_GCM,data:AHjo6G+03gbrZvYFtYaU6uhhajtfnWmuGKzj5ZrBMjpaVKbEqjWKcuIU3Cs8zXGlr3QfClByPKCRg/uZcA+/LdrEx1gENj2y3FEDBl3ekf5vPPE4Qd1a/A==,iv:fKdDDkfGhzCeSB/wBcz9YJwJ7pF7hYP8chAJ04GZRDk=,tag:NRVm+oTnLyZF8qYGVZJ1jg==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:vazhQuvGoKh3uy8yvwfAehfbycEGlgWiPXVHlV2k1UUmGLYlH2SHrbZufitnGIagls0nr30YyEMGJ66Xgdz3HW8FkLezZQ/wBHu/frpGjqJOfrxCgFUDdygHQJov5TdEdZ27u+UW8v0rux9aX8j6mfUM3mZxhA==,iv:BbBjgsHh1pl904COKCMAh41uI7UH9kHcyy79zKYcM8E=,tag:mXSv0kRTdHsvppIQd5vQqg==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:BgGBpd3HyMT/Po/gTIQ=,iv:Jb7OeSnZ/+t9GU22nrPVQZJiybKInDQ6ffcg7jdkLGo=,tag:M/NdRhVPMCxrQy8c8ycg3A==,type:str]
        security: ENC[AES256_GCM,data:4H6HNFWBpLE=,iv:CTir/KO8cTDK0eDpa6dugYH694DLDcKG+ygRceaI7g0=,tag:3693/sT2XbRyzY4LztI0xg==,type:str]
        port: ENC[AES256_GCM,data:UTHq,iv:g5aIKLKIB5++TI9se3a8DAm1TXBtFpraW7ZkuAUMT0Q=,tag:MR2IrxmXGb0oVrQsmQFzvA==,type:str]
        username: ENC[AES256_GCM,data:0L8/CCsh5IKj9vss7FXSUcwx12TPA55N,iv:5J73NP2SZQtvt3Uh3SemkEVLiQoPp2TpWGcgDbvVA7s=,tag:VJycnuwFaVOsRHrwMF14Cg==,type:str]
        password: ENC[AES256_GCM,data:lPHpR9Z912MEGfwN+1dm0vJRIvgF4N7N+qsieyDuscj2qY0bjtEoRbAnSvpNkoTpi3drZxuAR3ZxJ9UFvck9/hGOtSOn6wEUCfFJWEsZQ8/k0F7EaMor4w==,iv:M47gM1ZU+TgldQqP/PfogBFChDhyK5xckqtVRbAWzxQ=,tag:NLDMayhrXy9nT6CtkhQEjQ==,type:str]
    database:
        username: ENC[AES256_GCM,data:2D1kgSPa+7bQtXg=,iv:qPVLau+h4t1SiD5PqwoHjSuCwG/ftH1x+eLhpN5g+nM=,tag:CsnCynMeeWaQE6OORa0/WA==,type:str]
        password: ENC[AES256_GCM,data:PfM6wTM2KZpb442wTBbKefNmIf8YfYKeLJcMbyBVczbqiTT2uDcGlFQ21JYXpdpS0ZlyCbkR115R8zDenMCE2eRE+oMtO7WISt10eSTmWfuqWq2pf9PZm6R50b80lYe5rJUmy4mtZGu4PramLvI8qIFYXTi9EcKZlNh4Zio4OfY=,iv:yekf7PRi/bwpJ/bLrfSz8nxubJxs1ckJNBxfslnfvl4=,tag:+21eR5yhtVg3Vy08qHWD2A==,type:str]
    yubico:
        id: ENC[AES256_GCM,data:S+F/C5o=,iv:I6YWEq8+lpSvVicgnTnXyobK/dLi/hwyYOGUu52q1hU=,tag:QGNNvy+ublzyilCgCScaDw==,type:str]
        secret: ENC[AES256_GCM,data:ACM/YCW/rnNjCBR+dQjvN7n5zl+t8wc7SF4/EQ==,iv:ovEwbuFtdnnYnr0qpmWrXM3AqmoUsPwe8nIW/4Mkn34=,tag:vB1DUUvIErM1cdqqwItFVw==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:buoJTb0xMPwLU3od6EAtyBPuaXTXz3RgoS9wzHuLmTeIPLtA,iv:kakIcF8ZUsdfeH65FfzsF0Vk5GotrDMmzWQF4IQRxhE=,tag:sklnt6ldn/mO0wBDjyokHw==,type:str]
        installation_key: ENC[AES256_GCM,data:a008z235vzyB8T/sH9f0ukhX9AE=,iv:1jk1+5V278evEl/gU/aocOMgXUzAfbFVECG/sQC0s4k=,tag:9jOlC2t2WtLAoEbpZXfneQ==,type:str]
forgejo:
    database:
        pass: ENC[AES256_GCM,data:L7WfrPAFQ2b2lJ0ym38XqahoVt9wW+NEM5i0Hi1lFdc9n4pq1TxmPWzgfW6TApO2RZv4ufmKlrVk47hnW62RESw3ite1Psq2EE/LSa8KsD662MmaxYrb/Q==,iv:OTogoxwmalk4CiUlQstlER0JVN1YuVhWJgrhGJPYiuw=,tag:qj7B4Zc//uGVjlbkw4LrYg==,type:str]
    turnstile:
        secret: ENC[AES256_GCM,data:uBbtjN2eqDn7WN2y3swF+5Z1yLW4Oo1tTrDqZB6/tSCP0d0=,iv:yMnxn15p5HYZSMOCBT30i3gpClyW/2fx8Ytx9sQKLSc=,tag:zynI2iK6iYU9Ykzp6QYuEA==,type:str]
        sitekey: ENC[AES256_GCM,data:SOl5FYVMvq2XCZFP/KvS1YjgZjOnPfGt,iv:VaWMEu1QIh4LeauflFjJJgblLyOFkTpb4Db9wip6uY8=,tag:DQXhToC3Ys9JTdRQ8agdvA==,type:str]
    mailing:
        host: ENC[AES256_GCM,data:iVf5HnKPyvPx7WSExoM=,iv:7ksEKqX8nXS4A6M1JH3+FPWoxAP6naB2huwJ7Yc816k=,tag:JU9n3wQMFzwNMRK0PFJuJQ==,type:str]
        protocol: ENC[AES256_GCM,data:HTf/kKY=,iv:5ryKSzDHl1Vo375IqCnRr2TrcjJCvQgkdHHuIJ0Tk6w=,tag:rWNZdUXGJAB1zv/xSs80hw==,type:str]
        from: ENC[AES256_GCM,data:W7+g+1O8Oh4/SGOVHq7bq4P+a+MMJxglj0UAC+bT6rdSGWt7,iv:keQtnPpEdZpoHpWnIE/Dy67QTAWBhE1H1IGbtFOJMtY=,tag:5NzCHr8Ka0ypMX9DYBg0Tg==,type:str]
        user: ENC[AES256_GCM,data:Z/U9R+jUB+nd0+pSpdv72wjzWLaLicc8,iv://IECba3A/MlXv4q0eCI1DXZFF/YxF/U1AHhCrGNd2s=,tag:UweTefv0Czg41Sb64F9hTA==,type:str]
        pass: ENC[AES256_GCM,data:wHOJyzUEW0n+k3KUrAn3g/CwAw0vHZjVCl6fp7Fvr/u0FE8MrP5iuBjBlr5WxUJS+sVoLh/y6KEcPuPEV11wEEIiVv/TXRRnFjNGLM8p+Mv5w620i4P6Ug==,iv:/4e5+aGW/HksRYXXrpbYZgCCWPYD0n2plb/+tNwu9hM=,tag:C6VyNQs8plolsXjj6ucrfA==,type:str]
lego:
    cf_token: ENC[AES256_GCM,data:O3iHQ6oAXS+n/X0KRNbvrzmLYjkAXbe/gWtNjw0PVmkuyaUmspYPdA==,iv:utJunj8wewHFdOaD+EOgpN5/RpXyCdsl5Lr6kBbXsvw=,tag:7g4fwd0xJS6cf22AsfSXbQ==,type:str]
grafana:
    oauth2:
        github:
            cid: ENC[AES256_GCM,data:VYPxY9VXcpQMFqyoeBN+zjkKp+w=,iv:K/WKrdiq9mXaFV33zYQYeYgia/54t6/qCseVGykW/yg=,tag:4cq/YNSS25blFE3WkazquA==,type:str]
            cse: ENC[AES256_GCM,data:WRrHW4mFQUUBiMz9UPR3/1U2qu6yZyU+ukDJHwl682D7Rn55vQHbIg==,iv:iNbKhyUIuKtBUVHXdR36KWCueMjQuKIErl8P7intFX8=,tag:I1PcDnKuDDY/tVlh42sFhg==,type:str]
        gateway:
            cid: ENC[AES256_GCM,data:kB62ZnA=,iv:F8A+gIGPUjziBTuBnhVS9kygzZYjnwFayL6Mx7LBwe4=,tag:VbyUr2rCiZG2RRWIHZu+6g==,type:str]
            cse: ENC[AES256_GCM,data:XInTHmH8OCvYm4N9aPt60jzm3hXfsjF3cc7gb0FU5FM=,iv:1InLcW58sbz9wfp9VnONsqE+iDrhCWhlBBkr13KfN1s=,tag:vq/xcGA6ptORfep/uWanNQ==,type:str]
vmetrics:
    agent:
        akkoma: ENC[AES256_GCM,data:+nSb5214dJ/bw2Fa4j+ZVfRpuJuBw145y1huawNTK27xl60CebA7qJYWeg==,iv:M5NrIERoQJohFqCRgP3TcwW0OspHMIbZR9x8G7jvI8c=,tag:Yvwn3QaSXhoZNQopOVxTyw==,type:str]
    auth:
        hosts:
            #ENC[AES256_GCM,data:8X5vVwOqltB7qatu4FJhQe1Hcy9wni5/YDy2NomRXz/4SzugpzJA9EM0XjqH7gk=,iv:IeAZya/9R5fF4iqmmMzZ28J8hj9yYBPXnljsCVhN73U=,tag:KOmnNwMp6sUm/rciJuS7mw==,type:comment]
            mail: ENC[AES256_GCM,data:bqUzANslpvRG4qMNCUJCw98jeP81FigymehTQmrpcU9qGcsaMe6gSmFjCxS54u8DFYQ3chma6o6GWx+jyzBP9j11OtM6yRexYbdQtSVqqvFyaoOknAYhuAl5qmIBGLcdfKAScR7QTkwS3e0YGu6t3ahWbKwcboVDjJY8nMtXWitET6+gzB93/LS9CYsd7q1fDtmJojt1LiIWMWwnaCGIpuaTUivB3zcNAdxTSw==,iv:Tm93jST/E4PkSlafzMWBfdOZj7g4J0dzBSeLrS8o4Ow=,tag:jWrVxdlNP2Q9eF3dhWFdZw==,type:str]
            bocchi: ENC[AES256_GCM,data:4zm4+MEbtuZZxqFrFNzidJUjzS0rb891CTg6kJpEYG+qx9eOGTmWKoKfxMnOjteiy9G0VMjdX0FggunIYmLTqJYNOIJgB5B0/y5lLQurnr6WRmnm/JS2UBFPbpWdF4W8RF+Xi8xWpRS6AjBzQJuobhyduwGONAKwAflhtVFtOCaTXD+pgcEv+CkA7zscyuCxIAn9C1TIiUm0xTk2WvIPrNnT4FzVRhKZvFm6Fw==,iv:vhfxElYtouDM44cRzZwuZvJMncRN0Wt5uSfcSEFAuoM=,tag:aMrLDKphbMqJkFSINBpRRA==,type:str]
            satori: ENC[AES256_GCM,data:rp7QI9LMtL5b1X/L4qLyBaxxmblXQRW+Ge7btIeT7QdeiGA4/mf+xeMJvmBpirERWJunZqDdJ9i9ksP632cGRMhLmG5E11LtIV30xNWL8ZeuqOQsd6IBIa9fxlYWCHTVY76SJzdniJWP2gwz9S1E+/2rpmjnTXbgVWzOU9857To1XIfUFLIgG/ZC4J3vwsyXTlmGnW84ccIN25aKW+I8lU1vL7nmCIFGkbf4BA==,iv:6NhlTlShIUrtl5844NGWq5903liy7pbbsaa9z/OBxSQ=,tag:HBOEApT1xXPLaFQ3Kyz3gg==,type:str]
            renko: ENC[AES256_GCM,data:yv9qI2Odygec0O2RlUF3NmktcSIPydTkitEwzIHCEEDP0JmiXO0aGbMYdlQPNrW4P4aRjW6kSaRisAyjw13sIcBjqmPcncWLQDGqQZlBlZbNkZ6+73hsZVI2H3jB/Hz43eufKP/fYnBY7Er8jUpuo2C9T/7iNiL0e/Go7F2upJauvjVpfcDF3QgU2Y6YUfcOAgKPXqfZCG4+PUd0LZw1fnPD1b45OsEA8h5nDQ==,iv:WA8CsytshgRN0LXWyxm6pHQ0N8vwDfvh7VNlemrja8o=,tag:Kf0ENhN+DQEmuAJWvF+9cA==,type:str]
            kita: ENC[AES256_GCM,data:KnIHs4Crhm9zl298ee8enBhanhZTaPEL6nzNZfKRYmozEi0KfTBi5rZR5hCHt8VMS4zso7Bx35TNZcUQqYqKEmkeSEoIWSPz/jsnuqgIJHVdsWhG8nodRWlVicLnI2CDZrYhtyOlmMDOZIrVdZf48cbjSqezrsLT9NH0CioSvPilbjBk3Mm+sJxxLEnszILZwqzI9xTlj4HMYZcJyQAN0xJKRxrkokcsKFpPcQ==,iv:Wvx+ItZIrdHO4W4M6QWIZgyGDINWoNKKPWVbarnGYj4=,tag:Rglt6KsUdf4BxDURpYpDaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQXF0enRRbUVVTlRwY3cr
            SVRiMnFmMndaejIwaFplT1BKci9JaFROT1NnCnRGSXBsbTg2SDlmTW53RzhxNXNO
            U1pMU3BPRHpmS0RFcGZoV200N0FzeFkKLS0tIGxRZVoyMEZvMWxHZkhXajlyeU5a
            eU4xRWlHZWZ3TFlrdGRPNmpWcDZuSHMKwOBmnWDU164Hpo30NdJUF29u2ehcrFdr
            wLE5qwmRCXR1I83i8Vrw4xlffa6YKioE1dVZKjkE3f7ucg7xsO8gXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkafenrdkkmatjh034yykpzjzzs5fx6kft23jlmsung3dwyufcksds59l2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVFplcFRNTzJueDN2U0VR
            d0NnT00waEJhSkptcGIrQ0pHanJJSDFwV0JVCnZDN0ZEdzZwS09zUjVRZ0liOXlZ
            WHhxK3o0OXhsRVBCcUhlOVhpVDZoN3cKLS0tIFlsNFJqWlJQTHBFcjEvUHYxYmNj
            L1c5UlNnajFFQXZhSlljb0FYbEhDZjgKz5brBCtm0Moi4ry1zTRpyULVl8oW20th
            joeamRXDKnW95K+PH/LJsUv0oKGD7udoR3MaoCiE5W4CaaDoOzYJSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18h7hya5terghrwawgpny28swlat2nqkdrfd4clk0svujqlz9xfusd3zeqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUzdZSEVDZzRicnpaQTN3
            M1MwU2VEZ3RkTHptVUEwaW5GdFZhakk2QmdjCnpEU2N3bElCOHg2SUJpZ2Q1U0NM
            UHloWHptOFNkR0U2ZGZBTEtnTmEvOE0KLS0tIFRWc3RnazR2TXVWMGJzd2F0blA1
            VFZOOVY4ODl2RzBXNGYwNjFRUkNDR28KGVQrkAMBSXKFOJ6/axVzxMp/84DODH7o
            EEged9XfSJRKENKh6NjFSZEZeDukePEzRiIbEGaFAC+8vQ0ggbUF3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T10:27:47Z"
    mac: ENC[AES256_GCM,data:AnSbgtNO532pTiZB7b5B9Stm1yyIgt7C7KOuWzjCQO4/cVweETPBurqcI2MaEpPL8206iLJFCdDS3YKgt1GfW6OrZc0RPciJ6Oz7R3HUDQ8NUiIGZcxruvWUeHkDuTOaGrQs9pxqHHlCqXLCdk7YDev+QeQ5XVIus0Bylpgv6OU=,iv:qWeV+QPTH4YYyUypOkwOGVH1XjxmuFdd6PKHByZgScc=,tag:AnpQnZBVnRXST3LL2kxJ2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
