synapse_comment_unencrypted: See https://github.com/Mic92/sops-nix/issues/120 for synapse.yaml quirks
synapse.yaml: ENC[AES256_GCM,data:awToENS3607hznfHUcUDZ2DL5BGyrHR/NMs3UPCuei3Bfx2EWtCcovgAArNxPonvsxych2OsJxcJZFOUS5mXzGmPc7axPVye1qJUa9Ih5/r4oWxLXC7oaNBGVyQHbm787A/YsjdsfffGBj3YSfcCO6JZebTZ4YiwvFl4BCwsfx8Vpuai/jWXCzWOoEHoSkTDZu4lDoTrNLyquwhVqMXNPDY4GVGDPbFMZ5TAHLVdwPlq7DSTQAcktdBOmGBrfYbDi191wKMDEOOPefcZJqbkMrDhSl+x8lw67XbvkNJcNCbRAB5VmVs/0baDDBzoZ5Dan73paDOQPbvfGDgbqU6qpkRYmPvjC+p75v2yjsA66E4yjdUSysy1VQJPtr5Nb6gwn05wjitEz8W9TIIgzha0Hvumo7UIUnyZouYQWAsQjNj6mP5eBAlHo814XUsPpkSI2xSxMtxDjFYccqio4M68cJxfS/MdjT76GBeBO6FejV1PQ2TjSnMk6ezKt0PV0Jpw72fauAcAFzgorqsarf/kbq2iI2aBrLCGctInuMiwHn81QWDRAGo03WheOBg6O8vjNur+0rgUEv5xfThXfgcUYV2CUb3ivWyR0HyuHof5dX9V6qC5/7l9a4YZr5MAB5baJUhR85Jv7mMzgSvSbD5QUJqP43ftLciRCwRYZtmuKqvnKUt1RO6mLZQysd1tZF3czcd48AWQ/+8UwlD0qoZzQTTZrIMyhFwQjKJmZ7gRLz5ytsj7YEmGyBHUvBuwoIqNwd6s8O6+hD3/HgKn40wyGclSTs5vkQBDbMhCeUH5QLHIVS0GQClmuHQB6ZJHuxW2Ahu0RYGnVU90zUYOqu0JS5GZemfSag1/evVO5fkY/078Q+loSNj99cRc01yulPVhEKcpdO1iDaDErq98xkRdfDCKZU6mt9exbV0Tthf3dK+Yj5RIwHGORjUUYd62FFRuOtVuU4OVVWk/bVMAuYpex0/5Q+uTxZuT,iv:fvaZQ66VKU+uzvn5AwTIFgzz+F2kJ8/QR2AfmynRfGU=,tag:fSmA+PnxFnjHgm1WyDHAPA==,type:str]
matrix-signing-key: ENC[AES256_GCM,data:xKpBlfEAaDhCupY5CSgaR+1tj6WS+N7o5OqRfBnam2n8jPjJrIlzDRpZgI9l1OXbus/eHQAitN65SQ==,iv:abvwkrNe324QCbWLwiPY0UwqezS0wbyk2Fvi0vs3SI0=,tag:zMTzXJogQv0bjd/YIj8BnQ==,type:str]
matrix-sliding-sync:
    secret: ENC[AES256_GCM,data:TliF5Xeri9I8/rI70YfaS6RCAQLlL6ZWk1v267/Tz1IK8D75CPhsjXx2XD7QUMNPT3x3Naxz9qNUxvPvkpCwCmC8Of8Qr4L7L6T2QcRKHilVaA0RvFmGyI4qtKUHhoY7WJFnZRDBRxHIPs5shxWVLyupObGhjk8iiLxykKVfdo6244tH8pIe8ooVRU/42t1acQxvFprcN50dpAarKbLbgQgU8dBcUP5qiiP/4E2mrBAR0jppCTkYO1T2bkxqE+Owqr/Q0UJZ5p1UPOX3ocZOhnYyVz3iWdCum09Mq1qE8dK8ErEwtTSM97rNDYE84qeEKBxsT07A+zC7p080iLHpcQ==,iv:JR9Hz+rmfGeJ+JfDugkI7bzh3wb/o/5CdrzKPXfVTL8=,tag:YwA9He+El/pV3nIiao0qRw==,type:str]
    db_pass: ENC[AES256_GCM,data:aOrwZcDT1hDfiA5k5F23f/0TQWVUOKIjkwMaLD+pzSejS8pVuBdTTBmeViP2B+VV3ErnXST2rNNqYVbz7QPwz7r3qf7cnsv9XxNjBfeUxg6mzhQzom5uLA==,iv:fKdDDkfGhzCeSB/wBcz9YJwJ7pF7hYP8chAJ04GZRDk=,tag:ize6wAQLwjpU8MrkE5sSzA==,type:str]
akkoma:
    dist:
        cookie: ENC[AES256_GCM,data:yPyixzZwnoIe0qH1gTzJhfQgXeK600iw8GCs2fUBFY4xiift/fyxM568LgnTcVsK21LV+9iehDDCKWsTMCLVSQ==,iv:V8+MpX/IEc57zEfhNGX5f+eMyipraaXDKPDNDOy0Ieo=,tag:3SrlkBW/ufySAAOPWUOuCw==,type:str]
    endpoint:
        secret_base: ENC[AES256_GCM,data:TSXy1HX8cu8JSEVft6ZAKUnAqvsML8zje5NwVKLCr+UP59ITXN4J9hEGpM5JJzDxNN5rPdAFqN7EvA10n5NEDA==,iv:/x0ydo2gOPrhIZI7at877bzfFgMpraauozfLq95aHCk=,tag:i/XnjBZrhTqW5PL5K4ltrA==,type:str]
        salt: ENC[AES256_GCM,data:3moHjMsNJ6I=,iv:aSun7ABJdbDQrFcrGQMM9H1/7d5lJqeMwO08gUYrD2A=,tag:b3bTFfEVr1ulvbKPNmpWNg==,type:str]
        live_view:
            salt: ENC[AES256_GCM,data:5Ly5m5AEk4c=,iv:ZvWKutuMTOm2X8w8a0fOTq+ldrXemayIUY2PUcurY80=,tag:sSXJidu89NK1TnxjvYJfXQ==,type:str]
    joken_default_signer: ENC[AES256_GCM,data:Mn+Gxs6lziKpokliqCqPoPX++XY8/VWZmkgeyYYFgeSzimfoJqq3pU1FPp9P5YGXDaWU0L2Hkftqh+gU1bEg2w==,iv:Yk1f/fzzbruW64mvTTeiyTlbrOO/G47CKKfr9BLtQ5g=,tag:ZoIBx3CvHqIUQCw8B4rs9Q==,type:str]
    search:
        meili:
            host_unencrypted: https://megumin.soopy.moe/
            key: ENC[AES256_GCM,data:KAGxm07jlkL27rnBbZSVgxlhiOgRyfOl5pwMS2bUXpT+UStVj8z8fpPZHBdqbmU+UQkOlYu047lqkHKBQA1ypw==,iv:t0kQUCmjhFw8Z2CTmYOPUNFvyiYfsXETU8GSxhRR5KE=,tag:LYWAPyGo6wEpcvPPdBKJvQ==,type:str]
    vapid:
        pub: ENC[AES256_GCM,data:pffszcUMFeGsJ26Xqei00CbnXWSQ3x0LGVGbJhhsoBxRDCzxc/nqk8a2cM24pmj4FG8hybRGH5KPfe+lKhn0KD6TKsmlwO2k55ItBWM2yoOmR86292Xp,iv:154BP5EmBqnKyf9BND2laKV3caVxa34MCRzrsg6/dik=,tag:X+8h/aZtBy6Qy9jxVXhvmw==,type:str]
        key: ENC[AES256_GCM,data:2X66IIohXsYpbkmtpTGgJ/u8x0HZl2W/bMdTetRmZRNX6SZ0VMZxmJiKmg==,iv:yQLu5CFl73GCojMBa2II6OhLrNNinsiVG1aPOAx+HtM=,tag:/q4qkUOsBtkFrEWdCemhew==,type:str]
    postgres:
        hostname: ENC[AES256_GCM,data:KA12ZIUmk+ZX,iv:GM2SH4Gkvt8tLG8AYIKxfHTZvB1sT+hgIoqkiViH6Es=,tag:wTZjiqTmSaE3d1fkTs2GYQ==,type:str]
        username: ENC[AES256_GCM,data:zmII7rsI,iv:OQ6zNmDn0uqKqNKEqOHWY6VBuT/4/CHog7b0Pf0TAPM=,tag:m9Vg5wxwdM3QPyR68jvPzw==,type:str]
        password: ENC[AES256_GCM,data:HoZEoLV5rP8WPpllb/PIYzN+FQ6g3AhQK0zwTWak3cJvDKLow8caezXrAdvFH9SBB1SzGJXGCXIDLxfvVqT6Bw==,iv:UFe/3H/AfTgSlJikHqE1IED3zINjDuOs5niXpGWXGYE=,tag:uHHiQfx2vWcghr3zFHh8kA==,type:str]
    smtp:
        username: ENC[AES256_GCM,data:gxMc36T3W+213kSGM7Carg==,iv:wBXWtRYawOkjumsvTPcKfvL95CCB+RbsEyJv0YUG3WA=,tag:fasG98JFROa2zKm0WP8c9g==,type:str]
        password: ENC[AES256_GCM,data:EXAd8kBk50w7swPSt20HHcwy3U0YIYNlmRUOnind/3fLiviZautegtj9QQ0vMj2N/3Xz145UUr9SN1kHbFOL0A==,iv:ds8Bg9JSJdNHUXh0FvD5a4pquyRnIXowcsJcVV1TyB4=,tag:7qVpb34SAGwKynsniGptVQ==,type:str]
        relay: ENC[AES256_GCM,data:ZOnGkVRtliyuFkeY3Ro=,iv:omnyn+Xa/cjqK+9l5bI573aR2p7UsUvqGX5ZQGf3CD0=,tag:+RH+v9pk5Kt1hN7yHKbP2A==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:yff56PhxzikGqG83xI8gNQC4ELOIN61Rz5x8UQ39xWFP9HwEyXRPJF76s09zVloKLBTUeoZMPbcbXjgysuuxK/u3b/stuoSgcWsGqtXNLTbpyDZoa68Fc3wdcZaT9xG9XAJ6cbRd095qciGv4POAj6U6ict7sg==,iv:BbBjgsHh1pl904COKCMAh41uI7UH9kHcyy79zKYcM8E=,tag:QzWiTShi7F2e1WoA4G+HbA==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:qw5WY96GPur6yubGovo=,iv:Jb7OeSnZ/+t9GU22nrPVQZJiybKInDQ6ffcg7jdkLGo=,tag:JZeQtxCcdkR+OpC6qPuK/A==,type:str]
        security: ENC[AES256_GCM,data:WcGTC1yhFKw=,iv:CTir/KO8cTDK0eDpa6dugYH694DLDcKG+ygRceaI7g0=,tag:f2PZp+hxa9v1KFqNqiB0oQ==,type:str]
        port: ENC[AES256_GCM,data:Mdo1,iv:g5aIKLKIB5++TI9se3a8DAm1TXBtFpraW7ZkuAUMT0Q=,tag:EM1LH+ra+3P3x2t0qZYadA==,type:str]
        username: ENC[AES256_GCM,data:VTP4Wu1dwj4PWMBiSprcrAYp/ylZ8BOA,iv:5J73NP2SZQtvt3Uh3SemkEVLiQoPp2TpWGcgDbvVA7s=,tag:cFoWorRrjGAOm25s3Qcy5A==,type:str]
        password: ENC[AES256_GCM,data:5FzgcK6/jFpI3vS7o3EC8hQDb2U804k/IkNFRMMbmicDpfULffZvZ3y6XgZG1UkeR+gWfigL+MIA4zQkedkd/+0cUf8Kr9XcdEi+PHbWj0ERxryn80AMzg==,iv:M47gM1ZU+TgldQqP/PfogBFChDhyK5xckqtVRbAWzxQ=,tag:6P2AbGKkVHdMQcnCJ/oRFA==,type:str]
    database:
        username: ENC[AES256_GCM,data:7/5DD4xSTpQ9IhA=,iv:qPVLau+h4t1SiD5PqwoHjSuCwG/ftH1x+eLhpN5g+nM=,tag:KO/aNoKGKwMug1Ej5KXeOQ==,type:str]
        password: ENC[AES256_GCM,data:jRFqwayiHiDMKypIJC6CDo5nNpr0HGjzd0ai61DKfRfpRoyjRJfO2eiakcxGy3w1q7Gur/TsIlQe/5Kj5S9VkdfFV+dw2kGdwjWCM0L2pwBQz4SARJvbGTI1qZOTjwksoCGfKu9biWIhALRwaLdL0Pd9pKf1oYDuclWoDm9AQvc=,iv:yekf7PRi/bwpJ/bLrfSz8nxubJxs1ckJNBxfslnfvl4=,tag:/w2F1agDSD3sNTV2SZ9bnQ==,type:str]
    yubico:
        id: ENC[AES256_GCM,data:sUfPG88=,iv:I6YWEq8+lpSvVicgnTnXyobK/dLi/hwyYOGUu52q1hU=,tag:xMjhZzhG064YYyxNsUQaVQ==,type:str]
        secret: ENC[AES256_GCM,data:T/wLR7Mm9eMT0SNftc7Ozc2l2pWE1HNz/q6MgA==,iv:ovEwbuFtdnnYnr0qpmWrXM3AqmoUsPwe8nIW/4Mkn34=,tag:8H5n4GC7rJwDOSdXz2NQwA==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:Rlfb/QkBwHTnq8ALd2FdpRnuPeIkpln/UlRdzOCLnvYLbjcX,iv:kakIcF8ZUsdfeH65FfzsF0Vk5GotrDMmzWQF4IQRxhE=,tag:2WIA5nS4fP2AASUCxI6DmA==,type:str]
        installation_key: ENC[AES256_GCM,data:HQyIqfLXl9/qAVGYCC1YYfdDvfY=,iv:1jk1+5V278evEl/gU/aocOMgXUzAfbFVECG/sQC0s4k=,tag:A3z0DGEGGerQJ6HqqfjB8A==,type:str]
forgejo:
    database:
        pass: ENC[AES256_GCM,data:E54aUcgZ53histSP8HAZBFMg6bslshqDw+/M8NtOGi90n8EGqahtOji85Om6b8ksz/+FhRVedAVfnPDwUiax/YFdxQBD2K2acbJ7tvlZlsJy6QHtQxyxhA==,iv:OTogoxwmalk4CiUlQstlER0JVN1YuVhWJgrhGJPYiuw=,tag:h2q3iHyA9gJe2Yeq1pouDg==,type:str]
    turnstile:
        secret: ENC[AES256_GCM,data:+dOaOWYatHTDU0TQe5a4AfUMCmSsiA0ioK0OM7L+SWVCM1c=,iv:yMnxn15p5HYZSMOCBT30i3gpClyW/2fx8Ytx9sQKLSc=,tag:xpRae/8lJhf0cCGEymhtdA==,type:str]
        sitekey: ENC[AES256_GCM,data:nTMHbL4+fjDWnMk+1gNfRhOrNihslKeQ,iv:VaWMEu1QIh4LeauflFjJJgblLyOFkTpb4Db9wip6uY8=,tag:FJkXywkNfVRoYORjtU+zOw==,type:str]
    mailing:
        host: ENC[AES256_GCM,data:b+uDHaVJi/4h+WpYqlY=,iv:7ksEKqX8nXS4A6M1JH3+FPWoxAP6naB2huwJ7Yc816k=,tag:wjzX1W9wcNwMQ8eWttYJEw==,type:str]
        protocol: ENC[AES256_GCM,data:5cSSasM=,iv:5ryKSzDHl1Vo375IqCnRr2TrcjJCvQgkdHHuIJ0Tk6w=,tag:e400gS21av764okBtWAgEQ==,type:str]
        from: ENC[AES256_GCM,data:8C6L5Psn8RiRdYGbj5PkT35DC/uTHk9MV5Xf5dJ2MKBGdtar,iv:keQtnPpEdZpoHpWnIE/Dy67QTAWBhE1H1IGbtFOJMtY=,tag:Iov4VkWx5320yEw04hKUlw==,type:str]
        user: ENC[AES256_GCM,data:8GePg+iU96c8Zx10kCNWb2rXZaHBfXjG,iv://IECba3A/MlXv4q0eCI1DXZFF/YxF/U1AHhCrGNd2s=,tag:CubtpGbA0Z9IMHC+uy05aw==,type:str]
        pass: ENC[AES256_GCM,data:p1ISjT5K/pkLN7Wpo2VJXfTjjuRnKwLA9y5VmSSedMZyZ0XKP1IWX1aLurieBObYT5SKGg2irXdtz2mt4lp7o09fELH1wX2sVMgutbQfYLDBT8TrVvTX0g==,iv:/4e5+aGW/HksRYXXrpbYZgCCWPYD0n2plb/+tNwu9hM=,tag:eu7WRjrDbQZWqmtDBbmS5w==,type:str]
nitter:
    guest_accounts_service:
        endpoint: ENC[AES256_GCM,data:MOd4hoF28E8K8dx21iUMrZO62zDWw2f3xllWb9HCotuPmSrVyOfNMpcEnguVTLFCQYQzbN9ZH5gpcvZ6,iv:pN8NwtYpK3okIkFyngLqAZ9V7Hd59yrS0SXMuLbudBc=,tag:9RWakAZylvS1Aw9vWLw/HQ==,type:str]
        token: ENC[AES256_GCM,data:tMEyYKG7bh+pT7tyFSQB3zvuPeRG8t4JNdSyheuAeqe+tZzo,iv:CTPidsuToOl1CqAhiN9dCZXRNmsyylsbpP94pVGmcfM=,tag:n87iX1sF9Bmbn3dZdj0SIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rkyshu0lswdqyvun4cs9cekm9zt4fw5c8ssa38tn3lukgcahcvsltnqx2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeG83RU5FbjRvQ1RHaXA3
            emZ0SXU1WHh2OVNWby93MldteUsrZFZnRjBBClRBTGw5WHR5SkFCb2JsODJJdXdy
            cDUvbnY5SWhQOFpOVUlSWHNvajVyV2cKLS0tIEg5R2VrRVlHT2w5SWpYUWJyUWdj
            WmZPS1FseHJQbjRpeHZzZlBUS1RTbWsK9TN6qOOSXN1J6mcoFnSod+lm+kS2fHfj
            cuds8ZfxsCbc20hArw57EqQMA4HX7yGF48wUhccu9wACBusvRWC4yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18h7hya5terghrwawgpny28swlat2nqkdrfd4clk0svujqlz9xfusd3zeqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS00vSURlclRDd2szaDdx
            TTFCNjNXQzR3dzJvUWlVUEl6YUtieUxpQkd3CmNaR2E3czNXWWZLUENlZWN4aThh
            M2NmdFh1MUZQblNvNm9vLzM1MU5MS3MKLS0tIEZJZlRIcVRNSFowM0JjM1YweVpT
            enlNWTQwSkRTWTNIcncrRkdFN2d0ZW8KJn9h+b4NX2ElKc8WklfJQ2v/B6BbKnr/
            oX+p1daghqbIw8E/45JqkgqmsMXugEnygexpttEZQyP5Mmlia7blwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T13:04:48Z"
    mac: ENC[AES256_GCM,data:B5QM1jBMvrMPmlAVIoRSaVwyfaaLMLH3mB/mdMDY5ZVTcwA6THEFsxGd3cE1w4p3MA1l4DlOWFSd3vcOf4nJbhdXMUYsQ19cBI81aV98THnFkh6ifbaX6ZHiIkj977BlCDHKIuTNP1i29W1iMcYHeNU6i9iXRniE2k5RK9E2Ln8=,iv:CwYPWfSkhLtpg8FdLA5ZEKvxsi6Pyirc8BNhqrJNsPA=,tag:W4uuQg6WWMzy/Q/of3RPIA==,type:str]
    pgp:
        - created_at: "2023-09-08T14:11:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DAAAAAAAAAAASAQdAoEDKg5cJP1Pnlhb7U2rczLwM/Kxu1VDkp8q619g5Tkkw
            ohNk6CgCQFQenH/1Fi5/gNNkRvqkK8a7jZxtbtNDSORH/dKtxOHdXMRmzrMNR3+F
            0l4B0uw2eWsFUG6f0FBBr2fAPZDoJGWBJsHhBjsvuo/ad92mWqtm4tVq8eea0DCk
            IQoMh5TmM9fjj0VHbmLq7wqiOd4nd+HvvUVVZ2RPPyadWcLvBa5CcmoBEaJ/Deuv
            =Prb6
            -----END PGP MESSAGE-----
          fp: 8F3B277901484C6EA7E63F82D539637D518022C6
    unencrypted_suffix: _unencrypted
    version: 3.8.1
