synapse_comment_unencrypted: See https://github.com/Mic92/sops-nix/issues/120 for synapse.yaml quirks
synapse.yaml: ENC[AES256_GCM,data:6M44u7PheL0wiAOiaeUIJdBnttd79hEKkwZMXynDYqr+YKn7uJZS6AeRdMW/4fIdtUPvzXQGIQTH88S7OOunVFDlPJTKRp+ekazbnwMgqTyw5M8iLKf4vY0vHjRdIRd4bROLi1HA9vAoVRBK4McbzFg7YxS7YEqXFcl84ArrNvxh4bOUL37jaJgIZHprn3BNjYbCQYmBNW0AfAMVsAVPnufL9XodvuLx3Ec4PzAmKDf0A+SuKIHbamguYkjCNe7RcPQcdUmRcXhK2eoXimLIyfkk09ektmPLprvOYXtnuk7U7xlymH3duy+E6y+0+pC81pzks3wYnWzoKJ18iXGPwQGFI2aG8Mon6gJ7xAibvBurmUkMKit+eBs2F/5zTl36nfvd26YtdEMaU+XzDTPnsCtUS8i91yBK1jX8AJXATTKndM5NU9ILKFntGts6WhbnPRTLO/2k/IZgeH9nHs68cfXERI4uHIDr+NLxsTGxLnurVd/b1PEHEE1e+kU+s+tR9HTw7/zXHrBOlxGaivUFmbz7ktnJAIkRvBo49qsBFkMHMVLDlmbE0oQApqV7vcTQenaUlJuRl1h6kHim3W2c8d9DAb7SmhKHXgu27tHEEVm3B56j4LVrgAog568mh2hpG8SLbSTznV6kCkQ1sIL/1nbwl6DYz0USTpyBczDEHMF9Ex/euPkmNIH7yAhQXch6XhArSR6AjLZoYELHlzsVwZrJQ9M4AGOfOjztMI07z4as1N0JIwI4LhYvbeXUy9H/qaGqvZsk0Bh5J2LG4IPWsVqsig8HRDIuJPGoqmSWlX5VLMKNTOGiOK7aMpU+lYrHP1b8tBGTCMnSJ0m+ivfUzP6iQZUBR3WeiVSXU5+3lbyVUj6YfBqzQ1ai+vTq1bMDXXS+oMZEjgv3y3dMoqlwV2Akgst3IWS2hkowNIkG0CfEpf7WBnGkxf2LphkNKksH5/ccASlcK9VyUGkqhNbuI9FTofKEbcDF,iv:fvaZQ66VKU+uzvn5AwTIFgzz+F2kJ8/QR2AfmynRfGU=,tag:KRKvMdiP2tUrlyLyiOdecQ==,type:str]
matrix-signing-key: ENC[AES256_GCM,data:0aiWlYoCmmaLElFdXObSkyrbjZEOE67kl2svljwBVF8ghouDVrPeZD3uy0MQlBS+DlSbo76T53UXsQ==,iv:abvwkrNe324QCbWLwiPY0UwqezS0wbyk2Fvi0vs3SI0=,tag:IPHCqNMy+6v46ucbJmBKnQ==,type:str]
matrix-sliding-sync:
    secret: ENC[AES256_GCM,data:dbM/BqH0zJBzGKPHMwhOx/Qo2r8ZNZ0UKNK2cEH3Q95KvRMfexIxqjl7JqF+PKGHO2OgzOSOenQXnuwjTAhkz+7Qrr+X8GZD2/CcmBxqKMhu/HpcNmUNeQMvbvUvEMapjvMBIzE2yGcuCiqxVjUhV7Wk5bsuNJ10LX8P1dEertD2cY1qLI1bl0r7qiPVAxW1zioRQ1aUUSdeur4GxhSnKSnsdhqy4QjLOL4lYH0OsalC8zeEpDG0blaoWxtGCm+C9qTi0//A1wWkB52txUf5Q9blvt/z/LSznWZoLUzNegjWCrihZlKJhxamN2Fb2ha8DCsg2dDFftTavegDKInWQA==,iv:JR9Hz+rmfGeJ+JfDugkI7bzh3wb/o/5CdrzKPXfVTL8=,tag:WFTjxzWBqXBqI/G7nsWscA==,type:str]
    db_pass: ENC[AES256_GCM,data:7GUfkjbPezpIOJ13uR9vV8lWR0+lGNvLHleJuIOoGE6f0/HRVnBDrhFgvnD+qRBD85qYiiUjEG6JtVys5w0lEvh13I1/yNKN5L7PvaG2L7pNFP4q1JHRXQ==,iv:fKdDDkfGhzCeSB/wBcz9YJwJ7pF7hYP8chAJ04GZRDk=,tag:5reYxOEhKg3FyLzz1G6fhA==,type:str]
akkoma:
    dist:
        cookie: ENC[AES256_GCM,data:jwUETD59x+fbJkhrYkJ78ZIzcg/RgpHHgR8yvHupzXMnRxf6yBkPPFl5DVBPmJPl+EZOtnvG864H2s6kBEhuQw==,iv:V8+MpX/IEc57zEfhNGX5f+eMyipraaXDKPDNDOy0Ieo=,tag:o+OwJpfqNXsV1TimYHFacQ==,type:str]
    endpoint:
        secret_base: ENC[AES256_GCM,data:40HuVzeFKKIPJFhm4kqa07Jpo8bPfDeSGcbw2koqyIaqDhMH0oxPiuqFHXY1BmW7gc//lhXFRriOep8/8nCeZw==,iv:/x0ydo2gOPrhIZI7at877bzfFgMpraauozfLq95aHCk=,tag:nJPC8z8OEmOZelAGbm23iw==,type:str]
        salt: ENC[AES256_GCM,data:CEWsnzoFM5s=,iv:aSun7ABJdbDQrFcrGQMM9H1/7d5lJqeMwO08gUYrD2A=,tag:N9+n1wEBiTWla4oa5w9VGA==,type:str]
        live_view:
            salt: ENC[AES256_GCM,data:fXWxl82Hixo=,iv:ZvWKutuMTOm2X8w8a0fOTq+ldrXemayIUY2PUcurY80=,tag:tCm8jHAzuqYY4TbefXJwaQ==,type:str]
    joken_default_signer: ENC[AES256_GCM,data:9fzjNeoAfCFMIw1ZuFioD7y02GGhLSsIuihvN2PMpPqJ/gmHbKDuj4f9a/Sk4kReUZv4J8WWT8W1OdphOblMAQ==,iv:Yk1f/fzzbruW64mvTTeiyTlbrOO/G47CKKfr9BLtQ5g=,tag:vHFVTZ2DEWtJ0ibuwkmo9w==,type:str]
    search:
        meili:
            host_unencrypted: https://megumin.soopy.moe/
            key: ENC[AES256_GCM,data:1V4lF+hF4CPoSea+DBOPqoY9Lj4FaXbjVSNRhH/Fy6u2jTBwr7aIahJVSssG+kuX+keqcV2CSkhYXFECJgyh2Q==,iv:t0kQUCmjhFw8Z2CTmYOPUNFvyiYfsXETU8GSxhRR5KE=,tag:22UDZE6vPxuwQlG1zIP8+A==,type:str]
    vapid:
        pub: ENC[AES256_GCM,data:e/zO2K8KZ/mPLOD4CeF5RttW+pWpsWgMNaPYDWT6K4SK55exJR5J3w7cOncda6PqHilEEelScJ9EivW75gcW8O7vXfThfwR54J5e7RB/4glYIpcvNM10,iv:154BP5EmBqnKyf9BND2laKV3caVxa34MCRzrsg6/dik=,tag:5TpZfDVdIOa4liGvnLpU+g==,type:str]
        key: ENC[AES256_GCM,data:g2KVeQLNWwLbJvWNnIHjM62V/OK1WlPmNA3xhWtVOtSMFK0vypw3bCht9w==,iv:yQLu5CFl73GCojMBa2II6OhLrNNinsiVG1aPOAx+HtM=,tag:1WInqg/+EayT/gRfYfog7Q==,type:str]
    postgres:
        hostname: ENC[AES256_GCM,data:mtlrquvBxn1v,iv:GM2SH4Gkvt8tLG8AYIKxfHTZvB1sT+hgIoqkiViH6Es=,tag:D2EwqZ8mjr55NCb56nimmA==,type:str]
        username: ENC[AES256_GCM,data:PUkjuPSl,iv:OQ6zNmDn0uqKqNKEqOHWY6VBuT/4/CHog7b0Pf0TAPM=,tag:8pdSJ4R0CneqXbemYiuLAA==,type:str]
        password: ENC[AES256_GCM,data:2h6IJLKs/LQMY02b5a3WUvE1NmVu09aMyjrNvZcKlEhNI0ZtLEKW8PM73kXIEFUKmwsRXXbTOve4aEAyVc/c6Q==,iv:UFe/3H/AfTgSlJikHqE1IED3zINjDuOs5niXpGWXGYE=,tag:61S921jS0YbSQx6I8l3evw==,type:str]
    smtp:
        username: ENC[AES256_GCM,data:mvq30+ZAphNMvC/1zT0lUA==,iv:wBXWtRYawOkjumsvTPcKfvL95CCB+RbsEyJv0YUG3WA=,tag:tmfUBlN5i7WwrLxW22ijfw==,type:str]
        password: ENC[AES256_GCM,data:474QGxjidpdW/TT4fGvqo5yt3+SQG4WNVWTbckOF3f6Rg1p53A33fZ/EylLH6b3HLARkY3tYkPh0Z7otRwxagw==,iv:ds8Bg9JSJdNHUXh0FvD5a4pquyRnIXowcsJcVV1TyB4=,tag:jaMgD6WIFNrPM9s6b+mxNw==,type:str]
        relay: ENC[AES256_GCM,data:qRI5jeJwbKs9rc8+iE8=,iv:omnyn+Xa/cjqK+9l5bI573aR2p7UsUvqGX5ZQGf3CD0=,tag:KY+jUTj4z29Aug6V3q0ayg==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:ttEKREoi4hRgsaPu0LRW+ZNvo+m1fLvW12iiSKZ7NWjlC8xotx3brWZp1Yh20Kw+pGLbLgHMAa56/Ku+ZpWejv+ytuCRBs97aS3at5zJ4Y+YW30cXUDgvOTVFYpGZhUQMPTWC8+2BapwTjS2uUa1oAqeDuOPag==,iv:BbBjgsHh1pl904COKCMAh41uI7UH9kHcyy79zKYcM8E=,tag:KE0eW1a3xLi0CjRcKvAPEg==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:cCREYjhlSKsvBxpeiRk=,iv:Jb7OeSnZ/+t9GU22nrPVQZJiybKInDQ6ffcg7jdkLGo=,tag:g6Vy3YXbvapTBtHdmVaHtA==,type:str]
        security: ENC[AES256_GCM,data:cXE26G6sqnw=,iv:CTir/KO8cTDK0eDpa6dugYH694DLDcKG+ygRceaI7g0=,tag:aB3ZFCqrdv6AiokTgsn0Yg==,type:str]
        port: ENC[AES256_GCM,data:yRIA,iv:g5aIKLKIB5++TI9se3a8DAm1TXBtFpraW7ZkuAUMT0Q=,tag:MY4cb8oj3SlrhxElrOuOow==,type:str]
        username: ENC[AES256_GCM,data:KM8nUpQKeW/BisBBntIwRh6JyEapDcsg,iv:5J73NP2SZQtvt3Uh3SemkEVLiQoPp2TpWGcgDbvVA7s=,tag:dS62PH5GC7RxNTrl59495g==,type:str]
        password: ENC[AES256_GCM,data:TOk2N6/omcR854gOaBy2ekdaRzSLJNW+d8MznyEGeb3ThO/iF+x1xeu824CLaDHa+jkogFRCbo1AaTmJske4v3GVMaVfVWiy1eAwfDHbUFy5DbwBkM4Euw==,iv:M47gM1ZU+TgldQqP/PfogBFChDhyK5xckqtVRbAWzxQ=,tag:X+0tyzvNNyj+oeaH7N2Cuw==,type:str]
    database:
        username: ENC[AES256_GCM,data:KnY/tFy2H8aQj4Q=,iv:qPVLau+h4t1SiD5PqwoHjSuCwG/ftH1x+eLhpN5g+nM=,tag:YOvk9iafuE6V3FyqS9Wj2g==,type:str]
        password: ENC[AES256_GCM,data:m4OP2zsn0StyRuKV0NCCcAnBk32AgF50FUD9tQSB161g+88GkulRYaeZisax+eenhq5hQmSNwqRflUl0Tanoa2MxP8OJq7RYC/KC/958oBMHBnCuhlahuUZaHHAJ8n2demzHl/pwrmzVRP8EUACxDq1bRKMbMfD2fIeK2C1Bs74=,iv:yekf7PRi/bwpJ/bLrfSz8nxubJxs1ckJNBxfslnfvl4=,tag:fRzQ45S8clTn7kn915eI1A==,type:str]
    yubico:
        id: ENC[AES256_GCM,data:7Y8ChQw=,iv:I6YWEq8+lpSvVicgnTnXyobK/dLi/hwyYOGUu52q1hU=,tag:TLG3WolHarvFAy3pGlLTiw==,type:str]
        secret: ENC[AES256_GCM,data:oo8OJVqPiy/jSIgZ8ROxGleKKice84gcpD8FDQ==,iv:ovEwbuFtdnnYnr0qpmWrXM3AqmoUsPwe8nIW/4Mkn34=,tag:06pIQShoL4Dt7/kHV/VHlQ==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:4fuFy/ENuETCKZqPbrJmEiuV5AHyGjGqVqOzju+7LRPOE0HB,iv:kakIcF8ZUsdfeH65FfzsF0Vk5GotrDMmzWQF4IQRxhE=,tag:IAkwuarPrkab642f1IN18Q==,type:str]
        installation_key: ENC[AES256_GCM,data:UN7dTMxF24uaDhxLrxtIcZ005rE=,iv:1jk1+5V278evEl/gU/aocOMgXUzAfbFVECG/sQC0s4k=,tag:omWjGroIi/9pADoAPMrHTw==,type:str]
forgejo:
    database:
        pass: ENC[AES256_GCM,data:vYUwjkvLH+3FbrcqXvLIoonQlIIX8m+BRhQa+1Vbn7bOpZok9kSpKEnAvS8+jk08JXXbhs7o4uDGc73h43R6tTvzTpTCsJQ2OOXC8zhG+BUCqm35tLfOHA==,iv:OTogoxwmalk4CiUlQstlER0JVN1YuVhWJgrhGJPYiuw=,tag:687KLEXEtFYkbhioWOqYng==,type:str]
    turnstile:
        secret: ENC[AES256_GCM,data:qPQMudIOVYsACHJQtg5fqISM1UF/YnmDR39Up9JENXN/AbI=,iv:yMnxn15p5HYZSMOCBT30i3gpClyW/2fx8Ytx9sQKLSc=,tag:VuBvI9GJ1tdsKL62mCoBEg==,type:str]
        sitekey: ENC[AES256_GCM,data:09UjSFR6A2Z7fxTVzW5JWVhkhjDREbOK,iv:VaWMEu1QIh4LeauflFjJJgblLyOFkTpb4Db9wip6uY8=,tag:bM7N7C3BpQZxW49PP9Xmjw==,type:str]
    mailing:
        host: ENC[AES256_GCM,data:NWQDlykjSIiRM9nAEBg=,iv:7ksEKqX8nXS4A6M1JH3+FPWoxAP6naB2huwJ7Yc816k=,tag:8nxxgIcJp24yJY9k+xpb8g==,type:str]
        protocol: ENC[AES256_GCM,data:JMbHeWw=,iv:5ryKSzDHl1Vo375IqCnRr2TrcjJCvQgkdHHuIJ0Tk6w=,tag:rbY3eWVvKdHZ+aPjZVJ9aw==,type:str]
        from: ENC[AES256_GCM,data:oHElqJ6js7Om+wj1dfjazXUQfuNZQGjCjzqMzxrFaMLa2Fv9,iv:keQtnPpEdZpoHpWnIE/Dy67QTAWBhE1H1IGbtFOJMtY=,tag:PnaHPaG41ki5e7QJosUCqQ==,type:str]
        user: ENC[AES256_GCM,data:AJ3uJcykhkWv69HzGpgDvZzk4S1uzbCf,iv://IECba3A/MlXv4q0eCI1DXZFF/YxF/U1AHhCrGNd2s=,tag:QHRBBTAVZq/QUR0xSHRKLg==,type:str]
        pass: ENC[AES256_GCM,data:VmMXHF+d4ippStMDjomB6x8aGQLZ4gbacnSb9G4M8sFR9ac5jZUkRUMM6dHjp1Ic1BQHbsND9IZCokAJ0Fp8efqSPFCklweAA53L6oyd4ctpHIqb5/5RzA==,iv:/4e5+aGW/HksRYXXrpbYZgCCWPYD0n2plb/+tNwu9hM=,tag:txofrvCeuNR+Xjk6IjZwkw==,type:str]
lego:
    cf_token: ENC[AES256_GCM,data:HSfXYCZz/mz7NPEPI/7rlO6EZuBhAEJ+lHqUqDLYjO8/DB5OqpqMdQ==,iv:utJunj8wewHFdOaD+EOgpN5/RpXyCdsl5Lr6kBbXsvw=,tag:o+hhZqjftzTnljrbOLR5fQ==,type:str]
grafana:
    oauth2:
        github:
            cid: ENC[AES256_GCM,data:iejPcK2nMaSaYkbijIVzxqvxgV8=,iv:K/WKrdiq9mXaFV33zYQYeYgia/54t6/qCseVGykW/yg=,tag:9g01jiOSKy7QZmS43wzmCA==,type:str]
            cse: ENC[AES256_GCM,data:bLB2WrJdeZU+Z7yeiQ/70Zjz4c05Yh29HQIpV24s+RiJwWDPqBMqTQ==,iv:iNbKhyUIuKtBUVHXdR36KWCueMjQuKIErl8P7intFX8=,tag:aDgZeBFTGWnHFqrtUnQD8g==,type:str]
        gateway:
            cid: ENC[AES256_GCM,data:CwzywsQ=,iv:F8A+gIGPUjziBTuBnhVS9kygzZYjnwFayL6Mx7LBwe4=,tag:U0E6XeqMIt6TPSnx//7zXw==,type:str]
            cse: ENC[AES256_GCM,data:ICnaDiwYHLB/bg/qQcaYj6xQbWRFRZtM9P+id8i8VX0=,iv:1InLcW58sbz9wfp9VnONsqE+iDrhCWhlBBkr13KfN1s=,tag:JneXUqdf6HQJkALJbzEUWQ==,type:str]
vmetrics:
    agent:
        akkoma: ENC[AES256_GCM,data:27j26tzR+QdIAJY4tu6x36QTnDWqqYipdZhx9/fOMQNY71tPuzsal0y/OA==,iv:M5NrIERoQJohFqCRgP3TcwW0OspHMIbZR9x8G7jvI8c=,tag:dUu90xmL5eft2tfUMlwOiA==,type:str]
    auth:
        hosts:
            mail: ENC[AES256_GCM,data:2Y0QcFy3u3cdlxGdxcatlBdGWaNEb56rT1Vy5fQesn5Qmz0gxbMcwVFK8geF6NvaEVRuc8jdBUV1fnre57FeXvx6IFYRMdq//GWHlrJI3ng6TL9O3pH/vdDijXlR6ZQEJoUbwY+fwkChqN4nqofBvhzKf4ICP0YyiEMMrArXAA4Hm/ue6gXdc1xsojl1gCLOOEZgtCNKmX9oJr7xAt5k2e48XzvaBus91IXv2w==,iv:Tm93jST/E4PkSlafzMWBfdOZj7g4J0dzBSeLrS8o4Ow=,tag:uYideP23a0yb4h63m4LRXg==,type:str]
            gateway: ENC[AES256_GCM,data:C5X+YPh8MbxPHSqPhKUK+W1/7V95bUulXwS7XOZ5VFWOKmiVTVMHh/7oAT7gi1H+qyQZx+8mFIkUjIV3Q7xngKG6PIjrvsKaaNn+v1Y6HkJmuA0m3CV5DDGXZSJPijE0SHFfwXyJ6x8pyp2XYz1oNyseJPY/1Y8wkjBO2CNQlf0q5fgXi8wBJRgzjXc2we3Huuaeq4dYB773s5GscPWR4VJ10FbJfBluEeA35Q==,iv:OEzDSEfyx1iAGZeP1b9HO7aIy5P0kWFTcSsneRDni70=,tag:J1QQi5+x4GUdIgQTvGuDRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3qxt6630dzesdclfm3eqgw3uuhwj09dh6typwlwr6clcv0qhfrqgtj2fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZG5YM3ZrdFd0MTl3WFBV
            UnEzSWkwQUM2UlA2bWJMWCtsOTM4b0Q1ZFhVCmVScXljOS91M0puZXl6TmMyOXpW
            V3ZCNmhmejNNaTl6a0xNcG4wa2FEdFUKLS0tIG5FNmFLRHVDdVZuQ3haSlJKY0tt
            NEJZanlNK1htMXRkSUk4UFhDcTgybHMK8VIGHYZ1A2vet/pRmj2BFBzrTuHNKtx+
            od9hra4kJ+uR59FLzv2dQAOAjePvmPQVHg63jOcGEFwg4MgzX21r+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18h7hya5terghrwawgpny28swlat2nqkdrfd4clk0svujqlz9xfusd3zeqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSHR6L2NGZVJwK2M2TEc1
            Y1p0Q3V6OFBxNFB5WWtMQ2JTNGx6S0RaY2dBClBSS2E4UXNnQktTS25JZzJlaU42
            RUFpWW5qckxOU1RVcDh3NnBaNnZXc28KLS0tIGhMT2Z0Zk9QRFRTaXk4SHVlMHow
            RVBMYWppWDFxYXVNOEI2K3JzaFRZNE0KdspMlVcjpEG3lWz7P8TT3fCStaIDAqfN
            uBx4ISi43uttIAuBht9vncyjTNtVWvt3DTtawPYtBgG9LgnaMOikxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T11:54:30Z"
    mac: ENC[AES256_GCM,data:jdL6s+kHZp3WOIBoxgnEqVzV3WVOr4XeH26xmQn5vNqo60A7ndq62NTAivwHv1PQ3cEvCJ4Eui++oFtOF5XGpS7Rgr1hj+6g4fa7lltA32/eFUY0HdMmhmRZqptoMarl7GQjT0vuLfH6oB4aI6Rz1JCyoacrSag2tdD/VO+qNGE=,iv:q9SjpGKnD46L6H4TNYV48L3WWWX83Q098Zk8DQFGTGI=,tag:cebPvLZo8QBufR9myHN0HA==,type:str]
    pgp:
        - created_at: "2024-03-16T15:25:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DAAAAAAAAAAASAQdAwEvYCZ8BQ/Jdx0kow9dcU2Z8Qw9jRjJdqXDobmwaLAQw
            w2bzjGPx2b/8Povu04XUmYAHwj3BS+AOiN0GxJSBbCIOd6/FguR47guI6Rtsu3Qa
            0l4BfsLdIBHLQEDGZomDmS5Gcr7nBcGKtY6eFLC5ysaQCmVaOtpWUTDqVITQjiwz
            rLYPZcpWTXiZbV8sVYGb/StkNXJ/fsr9lpa7FHwbmy9iiA+IIl7UWc5pckOyj8ua
            =1yoz
            -----END PGP MESSAGE-----
          fp: 8F3B277901484C6EA7E63F82D539637D518022C6
    unencrypted_suffix: _unencrypted
    version: 3.8.1
