name: Check and Build configuration

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace .cry files with some bollocks
        run: find . -name "*.cry" -execdir bash -c 'echo some bollocks > {}' \;

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Run nix flake check
        run: nix flake check

      - name: Check with DeterminateSystems/flake-checker-action
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          ignore-missing-flake-lock: false

  build:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - koumakan
          - satori

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
        with:
          extra-conf: |
            fallback = true # why is this not the default?
            connect-timeout = 30
            netrc-file = /etc/nix/netrc
            experimental-features = nix-command flakes

      - name: Setup attic cache
        uses: ryanccn/attic-action@v0.2.1
        with:
          endpoint: https://nonbunary.soopy.moe
          cache: gensokyo-systems
          token: ${{ secrets.ATTIC_TOKEN }}
          skip-push: ${{ github.event_name == 'pull_request' }}

      - name: Build configuration
        run: nix build .#nixosConfigurations."${{ matrix.host }}".config.system.build.toplevel
