name: Check and Build configuration

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace .cry files with some bollocks
        run: find . -name "*.cry" -execdir bash -c 'echo some bollocks > {}' \;

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Run nix flake check
        run: nix flake check

      - name: Check with DeterminateSystems/flake-checker-action
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          ignore-missing-flake-lock: false

  build:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - koumakan

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write Nix netrc file
        run: |
          sudo mkdir -p /etc/nix
          echo "machine nonbunary.soopy.moe password ${access_token}" | sudo tee /etc/nix/netrc > /dev/null
        env:
          access_token: ${{ secrets.ATTIC_ACCESS_TOKEN }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            fallback = true  # why is this not the default?
            connect-timeout = 30
            netrc-file = /etc/nix/netrc
            experimental-features = nix-command flakes
            extra-substituters = https://nonbunary.soopy.moe/gensokyo-systems https://nonbunary.soopy.moe/gensokyo-global
            extra-trusted-public-keys = gensokyo-systems:r/Wx649dPuQrCN9Pgh3Jic526zQNk3oWMqYJHnob/Ok= gensokyo-global:XiCN0D2XeSxF4urFYTprR+1Nr/5hWyydcETwZtPG6Ec=

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Replace .cry files with some bollocks
        run: find . -name "*.cry" -execdir bash -c 'echo some bollocks > {}' \;

      - name: Build configuration
        run: nix build .#nixosConfigurations."${{ matrix.host }}".config.system.build.toplevel

      - name: Setup attic and push to cache
        run: |
          nix run github:zhaofengli/attic#default login nbsm https://nonbunary.soopy.moe ${access_token}
          nix run github:zhaofengli/attic#default push gensokyo-${{ matrix.host }} result
        env:
          access_token: ${{ secrets.ATTIC_ACCESS_TOKEN }}
        continue-on-error: true
