# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
name: "Build documentation"

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Build site
        run: "nix develop .#devShells.x86_64-linux.docs -c mdbook build docs"

      - name: Upload built site as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
